/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include "hardware/gpio.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
#define nimfr_(x, y)
#define nimln_(x, y)

/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(NIM_BOOL, testBit__r8x7Jw63S77y50Bjf5DS9cwbitops)(NU8 v, NI bit);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, pulse__3gK3JPW72sWOe5GpvMphTA)(NU32 pin, NU32 startValue);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NIM_BOOL, testBit__Z9ceN1bVm4QK9cvk9coBv8QFwbitops)(NU16 v, NI bit);
static N_INLINE(NIM_BOOL, testBit__MuFQFU1WRYiqEvaiwJ7gvAbitops)(NU32 v, NI bit);

/* section: NIM_merge_VARS */
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */
static N_INLINE(NIM_BOOL, testBit__r8x7Jw63S77y50Bjf5DS9cwbitops)(NU8 v, NI bit) {
	NIM_BOOL result;
	NU8 mask;
{	result = (NIM_BOOL)0;
	mask = (NU8)((NU32)(((NU8) 1)) << (NU32)(bit));
	result = ((NU8)(v & mask) == mask);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, pulse__3gK3JPW72sWOe5GpvMphTA)(NU32 pin, NU32 startValue) {
	gpio_put(pin, ((NU32) 0));
	gpio_put(pin, ((NU32) 1));
	gpio_put(pin, ((NU32) 0));
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU32)(((NU) (a))) + (NU32)(((NU) (b))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(r ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(r ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		(*res) = r;
	}
	goto LA1_;
	LA5_: ;
	{
		result = NIM_TRUE;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, shiftOut__oh9bttFDj3znjBotTg4Gv8w)(NU32 dataPin, NU32 clockPin, NU8 value) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI bit;
		NI res;
		bit = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				NI TM__l3X4SAN8yAZ7c7rQjE9aTOQ_2;
				if (!(res <= ((NI) 7))) goto LA3;
				bit = res;
				{
					NIM_BOOL T6_;
					if ((bit) < ((NI) 0) || (bit) > ((NI) 7)){ raiseRangeErrorI(bit, ((NI) 0), ((NI) 7)); goto BeforeRet_;
}
					T6_ = (NIM_BOOL)0;
					T6_ = testBit__r8x7Jw63S77y50Bjf5DS9cwbitops(value, ((NI) (bit)));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T6_) goto LA7_;
					gpio_put(dataPin, ((NU32) 1));
				}
				goto LA4_;
				LA7_: ;
				{
					gpio_put(dataPin, ((NU32) 0));
				}
				LA4_: ;
				pulse__3gK3JPW72sWOe5GpvMphTA(clockPin, ((NU32) 0));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (nimAddInt(res, ((NI) 1), &TM__l3X4SAN8yAZ7c7rQjE9aTOQ_2)) { raiseOverflow(); goto BeforeRet_;
};
				res = (NI)(TM__l3X4SAN8yAZ7c7rQjE9aTOQ_2);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, testBit__Z9ceN1bVm4QK9cvk9coBv8QFwbitops)(NU16 v, NI bit) {
	NIM_BOOL result;
	NU16 mask;
{	result = (NIM_BOOL)0;
	mask = (NU16)((NU32)(((NU16) 1)) << (NU32)(bit));
	result = ((NU16)(v & mask) == mask);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, shiftOut__GiW9apWzGLHTCa4iEYxm0KQ)(NU32 dataPin, NU32 clockPin, NU16 value) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI bit;
		NI res;
		bit = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				NI TM__l3X4SAN8yAZ7c7rQjE9aTOQ_3;
				if (!(res <= ((NI) 15))) goto LA3;
				bit = res;
				{
					NIM_BOOL T6_;
					if ((bit) < ((NI) 0) || (bit) > ((NI) 15)){ raiseRangeErrorI(bit, ((NI) 0), ((NI) 15)); goto BeforeRet_;
}
					T6_ = (NIM_BOOL)0;
					T6_ = testBit__Z9ceN1bVm4QK9cvk9coBv8QFwbitops(value, ((NI) (bit)));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T6_) goto LA7_;
					gpio_put(dataPin, ((NU32) 1));
				}
				goto LA4_;
				LA7_: ;
				{
					gpio_put(dataPin, ((NU32) 0));
				}
				LA4_: ;
				pulse__3gK3JPW72sWOe5GpvMphTA(clockPin, ((NU32) 0));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (nimAddInt(res, ((NI) 1), &TM__l3X4SAN8yAZ7c7rQjE9aTOQ_3)) { raiseOverflow(); goto BeforeRet_;
};
				res = (NI)(TM__l3X4SAN8yAZ7c7rQjE9aTOQ_3);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, testBit__MuFQFU1WRYiqEvaiwJ7gvAbitops)(NU32 v, NI bit) {
	NIM_BOOL result;
	NU32 mask;
{	result = (NIM_BOOL)0;
	mask = (NU32)((NU32)(((NU32) 1)) << (NU32)(bit));
	result = ((NU32)(v & mask) == mask);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, shiftOut__e069aaqO5irzbgrm9aIV6Hzw)(NU32 dataPin, NU32 clockPin, NU32 value) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI bit;
		NI res;
		bit = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				NI TM__l3X4SAN8yAZ7c7rQjE9aTOQ_4;
				if (!(res <= ((NI) 31))) goto LA3;
				bit = res;
				{
					NIM_BOOL T6_;
					if ((bit) < ((NI) 0) || (bit) > ((NI) 31)){ raiseRangeErrorI(bit, ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
					T6_ = (NIM_BOOL)0;
					T6_ = testBit__MuFQFU1WRYiqEvaiwJ7gvAbitops(value, ((NI) (bit)));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T6_) goto LA7_;
					gpio_put(dataPin, ((NU32) 1));
				}
				goto LA4_;
				LA7_: ;
				{
					gpio_put(dataPin, ((NU32) 0));
				}
				LA4_: ;
				pulse__3gK3JPW72sWOe5GpvMphTA(clockPin, ((NU32) 0));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (nimAddInt(res, ((NI) 1), &TM__l3X4SAN8yAZ7c7rQjE9aTOQ_4)) { raiseOverflow(); goto BeforeRet_;
};
				res = (NI)(TM__l3X4SAN8yAZ7c7rQjE9aTOQ_4);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
}
