/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "hardware/gpio.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
#define nimfr_(x, y)
#define nimln_(x, y)

/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_Table__CEbiADMtqwDYLcvZbib9b2w tyObject_Table__CEbiADMtqwDYLcvZbib9b2w;
typedef struct tySequence__S0afUuLVxWHsXKUhx366GA tySequence__S0afUuLVxWHsXKUhx366GA;
typedef struct tySequence__S0afUuLVxWHsXKUhx366GA_Content tySequence__S0afUuLVxWHsXKUhx366GA_Content;
typedef struct tyObject_Table__b4vpoerBR7V29ajKx2FDs6A tyObject_Table__b4vpoerBR7V29ajKx2FDs6A;
typedef struct tySequence__XMerIiAQb66xYd9a9cuy80SQ tySequence__XMerIiAQb66xYd9a9cuy80SQ;
typedef struct tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content;
typedef struct tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ;
typedef struct tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyTuple__sUhane4oetnlndJSo6uV6w tyTuple__sUhane4oetnlndJSo6uV6w;
typedef struct tyTuple__YlP5Jit39bfEvee3AJ2q9aGg tyTuple__YlP5Jit39bfEvee3AJ2q9aGg;
typedef struct tySequence__edypeVHoNy9czAu9cukTSm3Q tySequence__edypeVHoNy9czAu9cukTSm3Q;
typedef struct tySequence__edypeVHoNy9czAu9cukTSm3Q_Content tySequence__edypeVHoNy9czAu9cukTSm3Q_Content;
typedef struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA tySequence__9bAGqSvkAaFL9bWjsEPslrFA;
typedef struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tyTuple__ZRdLQPN7dYollpb9cddS68Q tyTuple__ZRdLQPN7dYollpb9cddS68Q;
typedef struct tyTuple__dxJdLbw7JUOttiF9cPJ6IjA tyTuple__dxJdLbw7JUOttiF9cPJ6IjA;

/* section: NIM_merge_TYPES */
struct tySequence__S0afUuLVxWHsXKUhx366GA {
  NI len; tySequence__S0afUuLVxWHsXKUhx366GA_Content* p;
};
struct tyObject_Table__CEbiADMtqwDYLcvZbib9b2w {
tySequence__S0afUuLVxWHsXKUhx366GA data;
NI counter;
};
struct tySequence__XMerIiAQb66xYd9a9cuy80SQ {
  NI len; tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content* p;
};
struct tyObject_Table__b4vpoerBR7V29ajKx2FDs6A {
tySequence__XMerIiAQb66xYd9a9cuy80SQ data;
NI counter;
};
typedef NU8 tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg;
struct tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw {
tyObject_Table__CEbiADMtqwDYLcvZbib9b2w addressPins;
tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg addressSetup;
tyObject_Table__CEbiADMtqwDYLcvZbib9b2w dataPins;
tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg dataSetup;
NU32 outputEnable;
NU32 writeEnable;
NU32 chipEnable;
tyObject_Table__b4vpoerBR7V29ajKx2FDs6A shiftMap;
tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ* shiftPins;
};
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef NU8 tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w;
struct tyTuple__sUhane4oetnlndJSo6uV6w {
tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w Field0;
NU32 Field1;
};
typedef tyTuple__sUhane4oetnlndJSo6uV6w tyArray__I63tMfkPaAZA9arJH0eoj1w[9];
struct tyTuple__YlP5Jit39bfEvee3AJ2q9aGg {
tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w Field0;
NI Field1;
};
typedef tyTuple__YlP5Jit39bfEvee3AJ2q9aGg tyArray__sDzvVtEHS9a8ca7dKvCRXhg[12];
struct tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ {
NU32 data;
NU32 clock;
NU32 latch;
NI shifterBytes;
};
struct tySequence__edypeVHoNy9czAu9cukTSm3Q {
  NI len; tySequence__edypeVHoNy9czAu9cukTSm3Q_Content* p;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA {
  NI len; tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content* p;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
};
struct tyTuple__ZRdLQPN7dYollpb9cddS68Q {
NI Field0;
tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w Field1;
NU32 Field2;
};


#ifndef tySequence__S0afUuLVxWHsXKUhx366GA_Content_PP
#define tySequence__S0afUuLVxWHsXKUhx366GA_Content_PP
struct tySequence__S0afUuLVxWHsXKUhx366GA_Content { NI cap; tyTuple__ZRdLQPN7dYollpb9cddS68Q data[SEQ_DECL_SIZE];};
#endif

      struct tyTuple__dxJdLbw7JUOttiF9cPJ6IjA {
NI Field0;
tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w Field1;
NI Field2;
};


#ifndef tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content_PP
#define tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content_PP
struct tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content { NI cap; tyTuple__dxJdLbw7JUOttiF9cPJ6IjA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
#define tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
struct tySequence__edypeVHoNy9czAu9cukTSm3Q_Content { NI cap; tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
#define tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
struct tySequence__edypeVHoNy9czAu9cukTSm3Q_Content { NI cap; tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
#define tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
struct tySequence__edypeVHoNy9czAu9cukTSm3Q_Content { NI cap; tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
#define tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
struct tySequence__edypeVHoNy9czAu9cukTSm3Q_Content { NI cap; tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
#define tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content { NI cap; NU32 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
#define tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content { NI cap; NU32 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
#define tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
struct tySequence__edypeVHoNy9czAu9cukTSm3Q_Content { NI cap; tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__S0afUuLVxWHsXKUhx366GA_Content_PP
#define tySequence__S0afUuLVxWHsXKUhx366GA_Content_PP
struct tySequence__S0afUuLVxWHsXKUhx366GA_Content { NI cap; tyTuple__ZRdLQPN7dYollpb9cddS68Q data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content_PP
#define tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content_PP
struct tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content { NI cap; tyTuple__dxJdLbw7JUOttiF9cPJ6IjA data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w, toTable__tw3SS9cdRQLkHcWNF8ibn2A)(tyTuple__sUhane4oetnlndJSo6uV6w* pairs, NI pairsLen_0);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A, toTable__uJbp00KSwsgQ9at44qzyaCA)(tyTuple__YlP5Jit39bfEvee3AJ2q9aGg* pairs, NI pairsLen_0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObjUninit)(NI size, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, newEEPROM__2N4SUM09aRJ3MerCg9aPMpWw)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w pinMap, tyObject_Table__b4vpoerBR7V29ajKx2FDs6A shiftMap, tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ* shiftPins, tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw* Result);
N_LIB_PRIVATE N_NIMCALL(void, validateEEPROM__9a32l0bG6PXqbVn2DbRSYBQ)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w pinMap, tyObject_Table__b4vpoerBR7V29ajKx2FDs6A shiftMap, tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ* shiftPins);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__hI3U2smIPAy9aJLZUctJ7sQ)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key);
N_LIB_PRIVATE N_NIMCALL(void, add__GzUH6O0SjRuWHzfOn1f8Tw)(tySequence__edypeVHoNy9czAu9cukTSm3Q* x, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w value);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__JHpRzcF21xoNQYgBrsWWkg)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringV2 msg);
static N_INLINE(NIM_BOOL, contains__euKUSGoRAiFSSauF1RMdtwsystem)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* a, NI aLen_0, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w item);
static N_INLINE(NI, find__Mx6kBeiWXyaSZ9c3wKZA1fAsystem)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* a, NI aLen_0, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w item);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w, max__uzMVnGTMOUt5oPTqbZlJ8w)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* x, NI xLen_0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___DSAPP3F10saUnzfSrl2Q2A)(tySequence__edypeVHoNy9czAu9cukTSm3Q x, tySequence__edypeVHoNy9czAu9cukTSm3Q y);
N_LIB_PRIVATE N_NIMCALL(tySequence__edypeVHoNy9czAu9cukTSm3Q, deduplicate__Ts9cgRykKmyvsc9brXQifXBw)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* s, NI sLen_0, NIM_BOOL isSorted);
N_LIB_PRIVATE N_NIMCALL(NI, len__PAYg5d1hn6UVJNVIuJVZlA)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t);
N_LIB_PRIVATE N_NIMCALL(void, add__lY5DLRz4X2A2isf2LBd6tQ)(tySequence__9bAGqSvkAaFL9bWjsEPslrFA* x, NU32 value);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___xG9c4bgU9bPyp4lp8VsxF5Sw)(tySequence__9bAGqSvkAaFL9bWjsEPslrFA x, tySequence__9bAGqSvkAaFL9bWjsEPslrFA y);
N_LIB_PRIVATE N_NIMCALL(tySequence__9bAGqSvkAaFL9bWjsEPslrFA, deduplicate__HKntiik9czuNpOlIyPbbFUQ)(NU32* s, NI sLen_0, NIM_BOOL isSorted);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___GdYovzyz9cvmRV9aK4h9a2piA)(tySequence__9bAGqSvkAaFL9bWjsEPslrFA* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___IlJSuVMKrFhfOcKQWcYQXQ)(tySequence__edypeVHoNy9czAu9cukTSm3Q* dest);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKeyOrPut__F8ewLFe7IWn5AKwlJOfbKw)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w* t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NU32 val);
N_LIB_PRIVATE N_NIMCALL(NU32, X5BX5D___izypgEXDrOPhvdwKMbE2zw)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___71gLqJJRAXmB7dO800Kngg)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A* dest, tyObject_Table__b4vpoerBR7V29ajKx2FDs6A src);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___tB0UasZGInHb3JJUEVb0IQ)(tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ** dest, tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ* src);
static N_INLINE(void, nimIncRef)(void* p);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___Xwzl9cs7b3c4aRHlsZ0Mh7A)(tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ* dest);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___nKP2x9cUu59a2GFPeZhMgNkw)(tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___O8Va9cr5zuMR80E1G5hQtag)(tySequence__S0afUuLVxWHsXKUhx366GA* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___9bWzf0v8OmYlwSMXdUYENEg)(tySequence__XMerIiAQb66xYd9a9cuy80SQ* dest);
static N_INLINE(void, print__UUnZ3sMEKzCq1Hl3GQIHXgpicostdlib)(NCSTRING s);
N_LIB_PRIVATE N_NIMCALL(void, writeEEPROM__AFzodz8r7BixDUv79cqnCsg)(tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw* eeprom, NI address, NI data);
N_LIB_PRIVATE N_NIMCALL(void, setInputs__ZEyXVzX0Jjh4Lm2m3u0kqg)(tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw* eeprom, NI address, NIM_BOOL oe, NIM_BOOL we, NIM_BOOL ce);
N_LIB_PRIVATE N_NIMCALL(NI, roof___M1yk6GvJhRrReRZgYouX8g)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(NI, len__CFEeD1cbzlG3EqLWcLD4eg)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w t);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(NIM_BOOL, isFilled__5Qpmu5QqwDY0esVXn6wf7wtables)(NI hcode);
static N_INLINE(NIM_BOOL, testBit__xQ0UxJYZQBHsfFh8l32Cwwbitops)(NI v, NI bit);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res);
static N_INLINE(NF, toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem)(NI i);
static N_INLINE(NF, abs__BRaAqinz6OWTHkALb4oj6Qsystem)(NF x);
N_LIB_PRIVATE N_NIMCALL(NI, getOrDefault__rJcaoBQ5Dqs3bvDKIAnm9aA)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NI default_0);
static N_INLINE(void, setBit__vSyO019bzxNbOxIELRXKYjAbitops)(NI* v, NI bit);
static N_INLINE(void, setMask__2tLl5NGxkOJmt6UtOu9aUCgbitops)(NI* v, NI mask);
static N_INLINE(void, clearBit__vSyO019bzxNbOxIELRXKYjA_2bitops)(NI* v, NI bit);
static N_INLINE(void, clearMask__2tLl5NGxkOJmt6UtOu9aUCg_2bitops)(NI* v, NI mask);
N_LIB_PRIVATE N_NIMCALL(NI, X5BX5D___E3nu0mxbUgUihx3VzztAZQ)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key);
N_LIB_PRIVATE N_NIMCALL(void, shiftOut__oh9bttFDj3znjBotTg4Gv8w)(NU32 dataPin, NU32 clockPin, NU8 value);
N_LIB_PRIVATE N_NIMCALL(void, pulse__3gK3JPW72sWOe5GpvMphTA)(NU32 pin, NU32 startValue);
N_LIB_PRIVATE N_NIMCALL(void, shiftOut__GiW9apWzGLHTCa4iEYxm0KQ)(NU32 dataPin, NU32 clockPin, NU16 value);
N_LIB_PRIVATE N_NIMCALL(void, shiftOut__e069aaqO5irzbgrm9aIV6Hzw)(NU32 dataPin, NU32 clockPin, NU32 value);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___M2d4UEGH9cZOvte6rEhvUTQ)(NU64 x);
N_LIB_PRIVATE N_NIMCALL(NU8, readEEPROM__fg3FnZOkcs9cAYqFI1VAy2A)(tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw* eeprom, NI address);
static N_INLINE(void, setBit__XwPFzY0nKw9aMJz1uiqKS8gbitops)(NU8* v, NI bit);
static N_INLINE(void, setMask__RWQ9atjq3mwVbUkjPu2R4xgbitops)(NU8* v, NU8 mask);
static N_INLINE(void, clearBit__XwPFzY0nKw9aMJz1uiqKS8g_2bitops)(NU8* v, NI bit);
static N_INLINE(void, clearMask__RWQ9atjq3mwVbUkjPu2R4xg_2bitops)(NU8* v, NU8 mask);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___xeif2zsreB9c0lcrdaotS8w)(tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ** dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___XCKmUiS3Ov3AJGom9cXECmg)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___1eV9bfPFgzYvCGm9bXLSWubw)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w* dest);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);

/* section: NIM_merge_DATA */
static NIM_CONST tyArray__I63tMfkPaAZA9arJH0eoj1w TM__c0pjnlBjpnggBqxewNeRCw_2 = {{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 16),
((NU32) 15)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 17),
((NU32) 14)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 18),
((NU32) 13)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 19),
((NU32) 20)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 20),
((NU32) 21)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 21),
((NU32) 22)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 22),
((NU32) 26)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 23),
((NU32) 27)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 26),
((NU32) 19)}
}
;
static NIM_CONST tyArray__sDzvVtEHS9a8ca7dKvCRXhg TM__c0pjnlBjpnggBqxewNeRCw_3 = {{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 0),
((NI) 0)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 1),
((NI) 1)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 2),
((NI) 2)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 3),
((NI) 3)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 4),
((NI) 4)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 5),
((NI) 5)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 6),
((NI) 6)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 7),
((NI) 7)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 8),
((NI) 8)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 9),
((NI) 9)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 10),
((NI) 10)}
,
{((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 25),
((NI) -1)}
}
;
static const struct {
  NI cap; tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w data[16];
} TM__c0pjnlBjpnggBqxewNeRCw_4 = {16 | NIM_STRLIT_FLAG, {((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 0),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 1),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 2),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 3),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 4),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 5),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 6),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 7),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 8),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 9),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 10),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 11),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 12),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 13),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 14),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 15)}};
N_LIB_PRIVATE NIM_CONST tySequence__edypeVHoNy9czAu9cukTSm3Q addresses__zUbLMYQ4q3tJuFiG1gURhw = {16, (tySequence__edypeVHoNy9czAu9cukTSm3Q_Content*)&TM__c0pjnlBjpnggBqxewNeRCw_4};
static const struct {
  NI cap; NIM_CHAR data[90+1];
} TM__c0pjnlBjpnggBqxewNeRCw_6 = { 90 | NIM_STRLIT_FLAG, "iterators.nim(204, 11) `len(a) == L` the length of the seq chan"
"ged while iterating over it" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_7 = {90, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_6};
static const struct {
  NI cap; NIM_CHAR data[27+1];
} TM__c0pjnlBjpnggBqxewNeRCw_11 = { 27 | NIM_STRLIT_FLAG, "Address Pin A0 not defined!" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__c0pjnlBjpnggBqxewNeRCw_10 = {{27, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_11}}
;
static const struct {
  NI cap; NIM_CHAR data[47+1];
} TM__c0pjnlBjpnggBqxewNeRCw_14 = { 47 | NIM_STRLIT_FLAG, "There is a dicontinuity in defined address pins" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__c0pjnlBjpnggBqxewNeRCw_13 = {{47, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_14}}
;
static const struct {
  NI cap; NIM_CHAR data[48+1];
} TM__c0pjnlBjpnggBqxewNeRCw_16 = { 48 | NIM_STRLIT_FLAG, "There are duplicates in the defined address pins" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__c0pjnlBjpnggBqxewNeRCw_15 = {{48, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_16}}
;
static const struct {
  NI cap; tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w data[8];
} TM__c0pjnlBjpnggBqxewNeRCw_17 = {8 | NIM_STRLIT_FLAG, {((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 16),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 17),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 18),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 19),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 20),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 21),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 22),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 23)}};
N_LIB_PRIVATE NIM_CONST tySequence__edypeVHoNy9czAu9cukTSm3Q dataLines__UTJphx4h3En9cbm5536bhkA = {8, (tySequence__edypeVHoNy9czAu9cukTSm3Q_Content*)&TM__c0pjnlBjpnggBqxewNeRCw_17};
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_19 = {90, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_6};
static const struct {
  NI cap; NIM_CHAR data[80+1];
} TM__c0pjnlBjpnggBqxewNeRCw_21 = { 80 | NIM_STRLIT_FLAG, "Incorrectly defined data pins, should be IO0 .. IO7 (without du"
"plicates or gaps)" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__c0pjnlBjpnggBqxewNeRCw_20 = {{80, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_21}}
;
static const struct {
  NI cap; NIM_CHAR data[29+1];
} TM__c0pjnlBjpnggBqxewNeRCw_23 = { 29 | NIM_STRLIT_FLAG, "Output Enable pin not defined" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__c0pjnlBjpnggBqxewNeRCw_22 = {{29, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_23}}
;
static const struct {
  NI cap; NIM_CHAR data[28+1];
} TM__c0pjnlBjpnggBqxewNeRCw_25 = { 28 | NIM_STRLIT_FLAG, "Write Enable pin not defined" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__c0pjnlBjpnggBqxewNeRCw_24 = {{28, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_25}}
;
static const struct {
  NI cap; NIM_CHAR data[45+1];
} TM__c0pjnlBjpnggBqxewNeRCw_27 = { 45 | NIM_STRLIT_FLAG, "shiftPins (clock, data, latch) must be unique" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__c0pjnlBjpnggBqxewNeRCw_26 = {{45, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_27}}
;
static const struct {
  NI cap; NIM_CHAR data[68+1];
} TM__c0pjnlBjpnggBqxewNeRCw_29 = { 68 | NIM_STRLIT_FLAG, "invalid number of shifterBytes. Should be between 1 and 4, incl"
"usive" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__c0pjnlBjpnggBqxewNeRCw_28 = {{68, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_29}}
;
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__c0pjnlBjpnggBqxewNeRCw_30 = { 2 | NIM_STRLIT_FLAG, "A0" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_31 = {2, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_30};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__c0pjnlBjpnggBqxewNeRCw_32 = { 2 | NIM_STRLIT_FLAG, "A1" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_33 = {2, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_32};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__c0pjnlBjpnggBqxewNeRCw_34 = { 2 | NIM_STRLIT_FLAG, "A2" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_35 = {2, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_34};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__c0pjnlBjpnggBqxewNeRCw_36 = { 2 | NIM_STRLIT_FLAG, "A3" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_37 = {2, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_36};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__c0pjnlBjpnggBqxewNeRCw_38 = { 2 | NIM_STRLIT_FLAG, "A4" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_39 = {2, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_38};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__c0pjnlBjpnggBqxewNeRCw_40 = { 2 | NIM_STRLIT_FLAG, "A5" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_41 = {2, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_40};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__c0pjnlBjpnggBqxewNeRCw_42 = { 2 | NIM_STRLIT_FLAG, "A6" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_43 = {2, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_42};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__c0pjnlBjpnggBqxewNeRCw_44 = { 2 | NIM_STRLIT_FLAG, "A7" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_45 = {2, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_44};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__c0pjnlBjpnggBqxewNeRCw_46 = { 2 | NIM_STRLIT_FLAG, "A8" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_47 = {2, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_46};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__c0pjnlBjpnggBqxewNeRCw_48 = { 2 | NIM_STRLIT_FLAG, "A9" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_49 = {2, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_48};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__c0pjnlBjpnggBqxewNeRCw_50 = { 3 | NIM_STRLIT_FLAG, "A10" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_51 = {3, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_50};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__c0pjnlBjpnggBqxewNeRCw_52 = { 3 | NIM_STRLIT_FLAG, "A11" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_53 = {3, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_52};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__c0pjnlBjpnggBqxewNeRCw_54 = { 3 | NIM_STRLIT_FLAG, "A12" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_55 = {3, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_54};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__c0pjnlBjpnggBqxewNeRCw_56 = { 3 | NIM_STRLIT_FLAG, "A13" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_57 = {3, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_56};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__c0pjnlBjpnggBqxewNeRCw_58 = { 3 | NIM_STRLIT_FLAG, "A14" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_59 = {3, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_58};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__c0pjnlBjpnggBqxewNeRCw_60 = { 3 | NIM_STRLIT_FLAG, "A15" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_61 = {3, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_60};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__c0pjnlBjpnggBqxewNeRCw_62 = { 3 | NIM_STRLIT_FLAG, "IO0" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_63 = {3, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_62};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__c0pjnlBjpnggBqxewNeRCw_64 = { 3 | NIM_STRLIT_FLAG, "IO1" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_65 = {3, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_64};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__c0pjnlBjpnggBqxewNeRCw_66 = { 3 | NIM_STRLIT_FLAG, "IO2" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_67 = {3, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_66};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__c0pjnlBjpnggBqxewNeRCw_68 = { 3 | NIM_STRLIT_FLAG, "IO3" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_69 = {3, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_68};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__c0pjnlBjpnggBqxewNeRCw_70 = { 3 | NIM_STRLIT_FLAG, "IO4" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_71 = {3, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_70};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__c0pjnlBjpnggBqxewNeRCw_72 = { 3 | NIM_STRLIT_FLAG, "IO5" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_73 = {3, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_72};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__c0pjnlBjpnggBqxewNeRCw_74 = { 3 | NIM_STRLIT_FLAG, "IO6" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_75 = {3, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_74};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__c0pjnlBjpnggBqxewNeRCw_76 = { 3 | NIM_STRLIT_FLAG, "IO7" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_77 = {3, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_76};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__c0pjnlBjpnggBqxewNeRCw_78 = { 2 | NIM_STRLIT_FLAG, "CE" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_79 = {2, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_78};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__c0pjnlBjpnggBqxewNeRCw_80 = { 2 | NIM_STRLIT_FLAG, "OE" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_81 = {2, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_80};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__c0pjnlBjpnggBqxewNeRCw_82 = { 2 | NIM_STRLIT_FLAG, "WE" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_83 = {2, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_82};
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_85 = {90, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_6};
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_89 = {90, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_6};
static const struct {
  NI cap; tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w data[3];
} TM__c0pjnlBjpnggBqxewNeRCw_90 = {3 | NIM_STRLIT_FLAG, {((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 25),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 26),
((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 24)}};
N_LIB_PRIVATE NIM_CONST tySequence__edypeVHoNy9czAu9cukTSm3Q enablers__U7SgZoQgJJy8KXtRCl7tTg = {3, (tySequence__edypeVHoNy9czAu9cukTSm3Q_Content*)&TM__c0pjnlBjpnggBqxewNeRCw_90};
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_92 = {90, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_6};
static const struct {
  NI cap; NIM_CHAR data[39+1];
} TM__c0pjnlBjpnggBqxewNeRCw_94 = { 39 | NIM_STRLIT_FLAG, "address is not within range of A0 .. An" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__c0pjnlBjpnggBqxewNeRCw_93 = {{39, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_94}}
;
static const struct {
  NI cap; NIM_CHAR data[89+1];
} TM__c0pjnlBjpnggBqxewNeRCw_95 = { 89 | NIM_STRLIT_FLAG, "tables.nim(681, 13) `len(t) == L` the length of the table chang"
"ed while iterating over it" };
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_96 = {89, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_95};
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_104 = {89, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_95};
static const struct {
  NI cap; NIM_CHAR data[33+1];
} TM__c0pjnlBjpnggBqxewNeRCw_119 = { 33 | NIM_STRLIT_FLAG, "invalid number of shift registers" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__c0pjnlBjpnggBqxewNeRCw_118 = {{33, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_119}}
;
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_121 = {89, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_95};
static const NimStringV2 TM__c0pjnlBjpnggBqxewNeRCw_125 = {89, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_95};
static const struct {
  NI cap; NIM_CHAR data[47+1];
} TM__c0pjnlBjpnggBqxewNeRCw_128 = { 47 | NIM_STRLIT_FLAG, "shift-in of data values currently not supported" };
static NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA TM__c0pjnlBjpnggBqxewNeRCw_127 = {{47, (NimStrPayload*)&TM__c0pjnlBjpnggBqxewNeRCw_128}}
;

/* section: NIM_merge_VARS */
N_LIB_PRIVATE tyObject_Table__CEbiADMtqwDYLcvZbib9b2w pinMap__nWL09cjZkGUAfFHC82bWQFQ;
N_LIB_PRIVATE tyObject_Table__b4vpoerBR7V29ajKx2FDs6A shiftMap__a9bcn9a5YPM0d83f5REsZbCQ;
N_LIB_PRIVATE tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ* shiftPins__tYc1Rmup5CeRa2UC4ttoIQ;
N_LIB_PRIVATE tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw x__YqNzq7zoy9cL9bW410IV0pMQ;
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;
N_LIB_PRIVATE NIM_CONST NU32 dataPin__xexpqFNhJGeyhnIHp9cvbdA = ((NU32) 16);
N_LIB_PRIVATE NIM_CONST NU32 clockPin__13DRswXbXcQah9a4nPb7sGQ = ((NU32) 18);
N_LIB_PRIVATE NIM_CONST NU32 latchPin__xPI6gUZhj2ywmtuH4hkT5g = ((NU32) 17);
N_LIB_PRIVATE NIM_CONST NI bytes__6EmxNhWJVTcGMZl7IPMdCQ = ((NI) 2);
N_LIB_PRIVATE NIM_CONST NI address__OmUAEETUpMtFg7DoTNZGXg = ((NI) 0);
N_LIB_PRIVATE NIM_CONST NI data__Eib8oILtRl5e32yWiS4JQw = ((NI) 43);

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU32)(((NU) (a))) + (NU32)(((NU) (b))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(r ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(r ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		(*res) = r;
	}
	goto LA1_;
	LA5_: ;
	{
		result = NIM_TRUE;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, find__Mx6kBeiWXyaSZ9c3wKZA1fAsystem)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* a, NI aLen_0, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w item) {
	NI result;
{	result = (NI)0;
	result = ((NI) 0);
	{
		tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* i;
		NI i_2;
		i = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w*)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI TM__c0pjnlBjpnggBqxewNeRCw_8;
				NI TM__c0pjnlBjpnggBqxewNeRCw_9;
				if (!(i_2 < aLen_0)) goto LA3;
				if ((NU)(i_2) >= (NU)(aLen_0)){ raiseIndexError2(i_2,aLen_0-1); goto BeforeRet_;
}
				i = (&a[i_2]);
				{
					if (!((*i) == item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				if (nimAddInt(result, ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_8)) { raiseOverflow(); goto BeforeRet_;
};
				result = (NI)(TM__c0pjnlBjpnggBqxewNeRCw_8);
				if (nimAddInt(i_2, ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_9)) { raiseOverflow(); goto BeforeRet_;
};
				i_2 = (NI)(TM__c0pjnlBjpnggBqxewNeRCw_9);
			} LA3: ;
		}
	}
	result = ((NI) -1);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, contains__euKUSGoRAiFSSauF1RMdtwsystem)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* a, NI aLen_0, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w item) {
	NIM_BOOL result;
	NI T1_;
{	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = find__Mx6kBeiWXyaSZ9c3wKZA1fAsystem(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, validateEEPROM__9a32l0bG6PXqbVn2DbRSYBQ)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w pinMap, tyObject_Table__b4vpoerBR7V29ajKx2FDs6A shiftMap, tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ* shiftPins) {
	tySequence__edypeVHoNy9czAu9cukTSm3Q addressList;
	tySequence__edypeVHoNy9czAu9cukTSm3Q colontmpD_;
	tySequence__edypeVHoNy9czAu9cukTSm3Q dataList;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	addressList.len = 0; addressList.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	dataList.len = 0; dataList.p = NIM_NIL;
	{
		tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* i;
		NI i_2;
		NI L;
		i = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w*)0;
		i_2 = ((NI) 0);
		L = ((NI) 16);
		{
			while (1) {
				NI TM__c0pjnlBjpnggBqxewNeRCw_5;
				if (!(i_2 < L)) goto LA4;
				if ((NU)(i_2) >= (NU)addresses__zUbLMYQ4q3tJuFiG1gURhw.len){ raiseIndexError2(i_2,addresses__zUbLMYQ4q3tJuFiG1gURhw.len-1); goto LA1_;
}
				i = (&addresses__zUbLMYQ4q3tJuFiG1gURhw.p->data[i_2]);
				{
					NIM_BOOL T7_;
					tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w colontmpD__2;
					T7_ = (NIM_BOOL)0;
					T7_ = contains__hI3U2smIPAy9aJLZUctJ7sQ(pinMap, (*i));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					if (!T7_) goto LA8_;
					colontmpD__2 = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
					colontmpD__2 = (*i);
					add__GzUH6O0SjRuWHzfOn1f8Tw((&addressList), colontmpD__2);
				}
				LA8_: ;
				{
					NIM_BOOL T12_;
					tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w colontmpD__3;
					T12_ = (NIM_BOOL)0;
					T12_ = contains__JHpRzcF21xoNQYgBrsWWkg(shiftMap, (*i));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					if (!T12_) goto LA13_;
					colontmpD__3 = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
					colontmpD__3 = (*i);
					add__GzUH6O0SjRuWHzfOn1f8Tw((&addressList), colontmpD__3);
				}
				LA13_: ;
				if (nimAddInt(i_2, ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_5)) { raiseOverflow(); goto LA1_;
};
				i_2 = (NI)(TM__c0pjnlBjpnggBqxewNeRCw_5);
				{
					if (!!((((NI) 16) == L))) goto LA17_;
					failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__c0pjnlBjpnggBqxewNeRCw_7);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
				LA17_: ;
			} LA4: ;
		}
	}
	{
		NIM_BOOL T21_;
		T21_ = (NIM_BOOL)0;
		T21_ = contains__euKUSGoRAiFSSauF1RMdtwsystem(addressList.p->data, addressList.len, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 0));
		if (!!(T21_)) goto LA22_;
		echoBinSafe(TM__c0pjnlBjpnggBqxewNeRCw_10, 1);
		exit(((NI) 1));
	}
	LA22_: ;
	{
		NI T26_;
		tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w T27_;
		NI TM__c0pjnlBjpnggBqxewNeRCw_12;
		T26_ = addressList.len;
		T27_ = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
		T27_ = max__uzMVnGTMOUt5oPTqbZlJ8w(addressList.p->data, addressList.len);
		if (nimAddInt(((NI) (T27_)), ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_12)) { raiseOverflow(); goto LA1_;
};
		if (!!((T26_ == (NI)(TM__c0pjnlBjpnggBqxewNeRCw_12)))) goto LA28_;
		echoBinSafe(TM__c0pjnlBjpnggBqxewNeRCw_13, 1);
		exit(((NI) 1));
	}
	LA28_: ;
	{
		tySequence__edypeVHoNy9czAu9cukTSm3Q T32_;
		NIM_BOOL T33_;
		T32_.len = 0; T32_.p = NIM_NIL;
		T32_ = addressList;
		colontmpD_ = deduplicate__Ts9cgRykKmyvsc9brXQifXBw(addressList.p->data, addressList.len, NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T33_ = (NIM_BOOL)0;
		T33_ = eqeq___DSAPP3F10saUnzfSrl2Q2A(T32_, colontmpD_);
		if (!!(T33_)) goto LA34_;
		echoBinSafe(TM__c0pjnlBjpnggBqxewNeRCw_15, 1);
		exit(((NI) 1));
	}
	LA34_: ;
	{
		tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* i_3;
		NI i_4;
		NI L_2;
		i_3 = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w*)0;
		i_4 = ((NI) 0);
		L_2 = ((NI) 8);
		{
			while (1) {
				NI TM__c0pjnlBjpnggBqxewNeRCw_18;
				if (!(i_4 < L_2)) goto LA38;
				if ((NU)(i_4) >= (NU)dataLines__UTJphx4h3En9cbm5536bhkA.len){ raiseIndexError2(i_4,dataLines__UTJphx4h3En9cbm5536bhkA.len-1); goto LA1_;
}
				i_3 = (&dataLines__UTJphx4h3En9cbm5536bhkA.p->data[i_4]);
				{
					NIM_BOOL T41_;
					tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w colontmpD__4;
					T41_ = (NIM_BOOL)0;
					T41_ = contains__hI3U2smIPAy9aJLZUctJ7sQ(pinMap, (*i_3));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					if (!T41_) goto LA42_;
					colontmpD__4 = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
					colontmpD__4 = (*i_3);
					add__GzUH6O0SjRuWHzfOn1f8Tw((&dataList), colontmpD__4);
				}
				LA42_: ;
				{
					NIM_BOOL T46_;
					tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w colontmpD__5;
					T46_ = (NIM_BOOL)0;
					T46_ = contains__JHpRzcF21xoNQYgBrsWWkg(shiftMap, (*i_3));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					if (!T46_) goto LA47_;
					colontmpD__5 = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
					colontmpD__5 = (*i_3);
					add__GzUH6O0SjRuWHzfOn1f8Tw((&dataList), colontmpD__5);
				}
				LA47_: ;
				if (nimAddInt(i_4, ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_18)) { raiseOverflow(); goto LA1_;
};
				i_4 = (NI)(TM__c0pjnlBjpnggBqxewNeRCw_18);
				{
					if (!!((((NI) 8) == L_2))) goto LA51_;
					failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__c0pjnlBjpnggBqxewNeRCw_19);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
				LA51_: ;
			} LA38: ;
		}
	}
	{
		NIM_BOOL T55_;
		T55_ = (NIM_BOOL)0;
		T55_ = eqeq___DSAPP3F10saUnzfSrl2Q2A(dataList, dataLines__UTJphx4h3En9cbm5536bhkA);
		if (!!(T55_)) goto LA56_;
		echoBinSafe(TM__c0pjnlBjpnggBqxewNeRCw_20, 1);
		exit(((NI) 1));
	}
	LA56_: ;
	{
		NIM_BOOL T60_;
		T60_ = (NIM_BOOL)0;
		T60_ = contains__hI3U2smIPAy9aJLZUctJ7sQ(pinMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 25));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (T60_) goto LA61_;
		T60_ = contains__JHpRzcF21xoNQYgBrsWWkg(shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 25));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		LA61_: ;
		if (!!(T60_)) goto LA62_;
		echoBinSafe(TM__c0pjnlBjpnggBqxewNeRCw_22, 1);
		exit(((NI) 1));
	}
	LA62_: ;
	{
		NIM_BOOL T66_;
		T66_ = (NIM_BOOL)0;
		T66_ = contains__hI3U2smIPAy9aJLZUctJ7sQ(pinMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 26));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (T66_) goto LA67_;
		T66_ = contains__JHpRzcF21xoNQYgBrsWWkg(shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 26));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		LA67_: ;
		if (!!(T66_)) goto LA68_;
		echoBinSafe(TM__c0pjnlBjpnggBqxewNeRCw_24, 1);
		exit(((NI) 1));
	}
	LA68_: ;
	{
		NI T72_;
		tySequence__9bAGqSvkAaFL9bWjsEPslrFA pins;
		NU32 colontmpD__6;
		NU32 colontmpD__7;
		NU32 colontmpD__8;
		tySequence__9bAGqSvkAaFL9bWjsEPslrFA colontmpD__9;
		T72_ = (NI)0;
		T72_ = len__PAYg5d1hn6UVJNVIuJVZlA(shiftMap);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!!((T72_ == ((NI) 0)))) goto LA73_;
		pins.len = 0; pins.p = NIM_NIL;
		colontmpD__6 = (NU32)0;
		colontmpD__7 = (NU32)0;
		colontmpD__8 = (NU32)0;
		colontmpD__9.len = 0; colontmpD__9.p = NIM_NIL;
		colontmpD__6 = (*shiftPins).data;
		add__lY5DLRz4X2A2isf2LBd6tQ((&pins), colontmpD__6);
		colontmpD__7 = (*shiftPins).clock;
		add__lY5DLRz4X2A2isf2LBd6tQ((&pins), colontmpD__7);
		colontmpD__8 = (*shiftPins).latch;
		add__lY5DLRz4X2A2isf2LBd6tQ((&pins), colontmpD__8);
		{
			tySequence__9bAGqSvkAaFL9bWjsEPslrFA T78_;
			NIM_BOOL T79_;
			T78_.len = 0; T78_.p = NIM_NIL;
			T78_ = pins;
			colontmpD__9 = deduplicate__HKntiik9czuNpOlIyPbbFUQ(pins.p->data, pins.len, NIM_FALSE);
			if (NIM_UNLIKELY(*nimErr_)) goto LA75_;
			T79_ = (NIM_BOOL)0;
			T79_ = eqeq___xG9c4bgU9bPyp4lp8VsxF5Sw(T78_, colontmpD__9);
			if (!!(T79_)) goto LA80_;
			echoBinSafe(TM__c0pjnlBjpnggBqxewNeRCw_26, 1);
			exit(((NI) 1));
		}
		LA80_: ;
		{
			NIM_BOOL T84_;
			T84_ = (NIM_BOOL)0;
			T84_ = (((NI) 4) < (*shiftPins).shifterBytes);
			if (T84_) goto LA85_;
			T84_ = ((*shiftPins).shifterBytes < ((NI) 1));
			LA85_: ;
			if (!T84_) goto LA86_;
			echoBinSafe(TM__c0pjnlBjpnggBqxewNeRCw_28, 1);
			exit(((NI) 1));
		}
		LA86_: ;
		{
			LA75_:;
		}
		{
			eqdestroy___GdYovzyz9cvmRV9aK4h9a2piA((&colontmpD__9));
			eqdestroy___GdYovzyz9cvmRV9aK4h9a2piA((&pins));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	LA73_: ;
	{
		LA1_:;
	}
	{
		eqdestroy___IlJSuVMKrFhfOcKQWcYQXQ((&dataList));
		eqdestroy___IlJSuVMKrFhfOcKQWcYQXQ((&colontmpD_));
		eqdestroy___IlJSuVMKrFhfOcKQWcYQXQ((&addressList));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___qYzpYseuMj9cCKH1yCYQR2Q)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w e) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	switch (e) {
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 0):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_31;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 1):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_33;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 2):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_35;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 3):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_37;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 4):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_39;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 5):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_41;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 6):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_43;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 7):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_45;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 8):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_47;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 9):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_49;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 10):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_51;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 11):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_53;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 12):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_55;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 13):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_57;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 14):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_59;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 15):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_61;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 16):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_63;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 17):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_65;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 18):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_67;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 19):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_69;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 20):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_71;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 21):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_73;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 22):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_75;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 23):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_77;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 24):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_79;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 25):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_81;
	}
	break;
	case ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 26):
	{
		result = TM__c0pjnlBjpnggBqxewNeRCw_83;
	}
	break;
	}
	return result;
}
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(void, nimIncRef)(void* p) {
	NI T1_;
	NI TM__c0pjnlBjpnggBqxewNeRCw_86;
{	T1_ = (NI)0;
	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (p)), ((NI) 4));
	if (nimAddInt((*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T1_))).rc, ((NI) 8), &TM__c0pjnlBjpnggBqxewNeRCw_86)) { raiseOverflow(); goto BeforeRet_;
};
	(*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T1_))).rc = (NI)(TM__c0pjnlBjpnggBqxewNeRCw_86);
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU32)(((NU) (a))) - (NU32)(((NU) (b))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(r ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(r ^ (NI)((NU32) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		(*res) = r;
	}
	goto LA1_;
	LA5_: ;
	{
		result = NIM_TRUE;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (p)), ((NI) 4));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI) -8)) == ((NI) 0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			NI TM__c0pjnlBjpnggBqxewNeRCw_87;
			if (nimSubInt((*cell).rc, ((NI) 8), &TM__c0pjnlBjpnggBqxewNeRCw_87)) { raiseOverflow(); goto BeforeRet_;
};
			(*cell).rc = (NI)(TM__c0pjnlBjpnggBqxewNeRCw_87);
		}
		LA6_: ;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___Xwzl9cs7b3c4aRHlsZ0Mh7A)(tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ* dest) {
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___tB0UasZGInHb3JJUEVb0IQ)(tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ** dest, tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ* src) {
	{
		if (!src) goto LA3_;
		nimIncRef(src);
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest));
		if (!T7_) goto LA8_;
		eqdestroy___Xwzl9cs7b3c4aRHlsZ0Mh7A((*dest));
		nimRawDispose((*dest), ((NI) 4));
	}
	LA8_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___nKP2x9cUu59a2GFPeZhMgNkw)(tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw* dest) {
	eqdestroy___O8Va9cr5zuMR80E1G5hQtag((&(*dest).addressPins.data));
	eqdestroy___O8Va9cr5zuMR80E1G5hQtag((&(*dest).dataPins.data));
	eqdestroy___9bWzf0v8OmYlwSMXdUYENEg((&(*dest).shiftMap.data));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest).shiftPins);
		if (!T3_) goto LA4_;
		eqdestroy___Xwzl9cs7b3c4aRHlsZ0Mh7A((*dest).shiftPins);
		nimRawDispose((*dest).shiftPins, ((NI) 4));
	}
	LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, newEEPROM__2N4SUM09aRJ3MerCg9aPMpWw)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w pinMap, tyObject_Table__b4vpoerBR7V29ajKx2FDs6A shiftMap, tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ* shiftPins, tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw* Result) {
	tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw x;
	NIM_BOOL shifter;
	NIM_BOOL discrete;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw));
	nimZeroMem((void*)(&x), sizeof(tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw));
	validateEEPROM__9a32l0bG6PXqbVn2DbRSYBQ(pinMap, shiftMap, shiftPins);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	shifter = (NIM_BOOL)0;
	discrete = (NIM_BOOL)0;
	{
		tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* i;
		NI i_2;
		NI L;
		i = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w*)0;
		i_2 = ((NI) 0);
		L = ((NI) 16);
		{
			while (1) {
				NI TM__c0pjnlBjpnggBqxewNeRCw_84;
				if (!(i_2 < L)) goto LA4;
				if ((NU)(i_2) >= (NU)addresses__zUbLMYQ4q3tJuFiG1gURhw.len){ raiseIndexError2(i_2,addresses__zUbLMYQ4q3tJuFiG1gURhw.len-1); goto LA1_;
}
				i = (&addresses__zUbLMYQ4q3tJuFiG1gURhw.p->data[i_2]);
				{
					NIM_BOOL T7_;
					tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w T10_;
					NU32 T11_;
					NIM_BOOL T12_;
					T7_ = (NIM_BOOL)0;
					T7_ = contains__hI3U2smIPAy9aJLZUctJ7sQ(pinMap, (*i));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					if (!T7_) goto LA8_;
					discrete = NIM_TRUE;
					T10_ = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
					T10_ = (*i);
					T11_ = (NU32)0;
					T11_ = X5BX5D___izypgEXDrOPhvdwKMbE2zw(pinMap, (*i));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					T12_ = (NIM_BOOL)0;
					T12_ = hasKeyOrPut__F8ewLFe7IWn5AKwlJOfbKw((&x.addressPins), T10_, T11_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					(void)(T12_);
				}
				LA8_: ;
				{
					NIM_BOOL T15_;
					NIM_BOOL T18_;
					T15_ = (NIM_BOOL)0;
					T15_ = contains__JHpRzcF21xoNQYgBrsWWkg(shiftMap, (*i));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					if (!T15_) goto LA16_;
					shifter = NIM_TRUE;
					T18_ = (NIM_BOOL)0;
					T18_ = hasKeyOrPut__F8ewLFe7IWn5AKwlJOfbKw((&x.addressPins), (*i), (*shiftPins).data);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					(void)(T18_);
				}
				LA16_: ;
				if (nimAddInt(i_2, ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_84)) { raiseOverflow(); goto LA1_;
};
				i_2 = (NI)(TM__c0pjnlBjpnggBqxewNeRCw_84);
				{
					if (!!((((NI) 16) == L))) goto LA21_;
					failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__c0pjnlBjpnggBqxewNeRCw_85);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
				LA21_: ;
			} LA4: ;
		}
	}
	{
		NIM_BOOL T25_;
		T25_ = (NIM_BOOL)0;
		T25_ = shifter;
		if (!(T25_)) goto LA26_;
		T25_ = discrete;
		LA26_: ;
		if (!T25_) goto LA27_;
		x.addressSetup = ((tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg) 2);
		eqcopy___71gLqJJRAXmB7dO800Kngg((&x.shiftMap), shiftMap);
		eqcopy___tB0UasZGInHb3JJUEVb0IQ(&x.shiftPins, shiftPins);
	}
	goto LA23_;
	LA27_: ;
	{
		if (!shifter) goto LA30_;
		x.addressSetup = ((tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg) 1);
		eqcopy___71gLqJJRAXmB7dO800Kngg((&x.shiftMap), shiftMap);
		eqcopy___tB0UasZGInHb3JJUEVb0IQ(&x.shiftPins, shiftPins);
	}
	goto LA23_;
	LA30_: ;
	{
		x.addressSetup = ((tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg) 0);
	}
	LA23_: ;
	shifter = NIM_FALSE;
	discrete = NIM_FALSE;
	{
		tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* i_3;
		NI i_4;
		NI L_2;
		i_3 = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w*)0;
		i_4 = ((NI) 0);
		L_2 = ((NI) 8);
		{
			while (1) {
				NI TM__c0pjnlBjpnggBqxewNeRCw_88;
				if (!(i_4 < L_2)) goto LA35;
				if ((NU)(i_4) >= (NU)dataLines__UTJphx4h3En9cbm5536bhkA.len){ raiseIndexError2(i_4,dataLines__UTJphx4h3En9cbm5536bhkA.len-1); goto LA1_;
}
				i_3 = (&dataLines__UTJphx4h3En9cbm5536bhkA.p->data[i_4]);
				{
					NIM_BOOL T38_;
					tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w T41_;
					NU32 T42_;
					NIM_BOOL T43_;
					T38_ = (NIM_BOOL)0;
					T38_ = contains__hI3U2smIPAy9aJLZUctJ7sQ(pinMap, (*i_3));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					if (!T38_) goto LA39_;
					discrete = NIM_TRUE;
					T41_ = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
					T41_ = (*i_3);
					T42_ = (NU32)0;
					T42_ = X5BX5D___izypgEXDrOPhvdwKMbE2zw(pinMap, (*i_3));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					T43_ = (NIM_BOOL)0;
					T43_ = hasKeyOrPut__F8ewLFe7IWn5AKwlJOfbKw((&x.dataPins), T41_, T42_);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					(void)(T43_);
				}
				LA39_: ;
				{
					NIM_BOOL T46_;
					NIM_BOOL T49_;
					T46_ = (NIM_BOOL)0;
					T46_ = contains__JHpRzcF21xoNQYgBrsWWkg(shiftMap, (*i_3));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					if (!T46_) goto LA47_;
					shifter = NIM_TRUE;
					eqcopy___71gLqJJRAXmB7dO800Kngg((&x.shiftMap), shiftMap);
					eqcopy___tB0UasZGInHb3JJUEVb0IQ(&x.shiftPins, shiftPins);
					T49_ = (NIM_BOOL)0;
					T49_ = hasKeyOrPut__F8ewLFe7IWn5AKwlJOfbKw((&x.dataPins), (*i_3), (*shiftPins).data);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					(void)(T49_);
				}
				LA47_: ;
				if (nimAddInt(i_4, ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_88)) { raiseOverflow(); goto LA1_;
};
				i_4 = (NI)(TM__c0pjnlBjpnggBqxewNeRCw_88);
				{
					if (!!((((NI) 8) == L_2))) goto LA52_;
					failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__c0pjnlBjpnggBqxewNeRCw_89);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
				LA52_: ;
			} LA35: ;
		}
	}
	{
		NIM_BOOL T56_;
		T56_ = (NIM_BOOL)0;
		T56_ = shifter;
		if (!(T56_)) goto LA57_;
		T56_ = discrete;
		LA57_: ;
		if (!T56_) goto LA58_;
		x.dataSetup = ((tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg) 2);
		eqcopy___71gLqJJRAXmB7dO800Kngg((&x.shiftMap), shiftMap);
		eqcopy___tB0UasZGInHb3JJUEVb0IQ(&x.shiftPins, shiftPins);
	}
	goto LA54_;
	LA58_: ;
	{
		if (!shifter) goto LA61_;
		x.dataSetup = ((tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg) 1);
		eqcopy___71gLqJJRAXmB7dO800Kngg((&x.shiftMap), shiftMap);
		eqcopy___tB0UasZGInHb3JJUEVb0IQ(&x.shiftPins, shiftPins);
	}
	goto LA54_;
	LA61_: ;
	{
		x.dataSetup = ((tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg) 0);
	}
	LA54_: ;
	{
		tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* i_5;
		NI i_6;
		NI L_3;
		i_5 = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w*)0;
		i_6 = ((NI) 0);
		L_3 = ((NI) 3);
		{
			while (1) {
				NI TM__c0pjnlBjpnggBqxewNeRCw_91;
				if (!(i_6 < L_3)) goto LA66;
				if ((NU)(i_6) >= (NU)enablers__U7SgZoQgJJy8KXtRCl7tTg.len){ raiseIndexError2(i_6,enablers__U7SgZoQgJJy8KXtRCl7tTg.len-1); goto LA1_;
}
				i_5 = (&enablers__U7SgZoQgJJy8KXtRCl7tTg.p->data[i_6]);
				{
					NIM_BOOL T69_;
					T69_ = (NIM_BOOL)0;
					T69_ = contains__hI3U2smIPAy9aJLZUctJ7sQ(pinMap, (*i_5));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					if (!T69_) goto LA70_;
					{
						NU32 T76_;
						if (!((*i_5) == ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 25))) goto LA74_;
						T76_ = (NU32)0;
						T76_ = X5BX5D___izypgEXDrOPhvdwKMbE2zw(pinMap, (*i_5));
						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
						x.outputEnable = T76_;
					}
					goto LA72_;
					LA74_: ;
					{
						NU32 T80_;
						if (!((*i_5) == ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 26))) goto LA78_;
						T80_ = (NU32)0;
						T80_ = X5BX5D___izypgEXDrOPhvdwKMbE2zw(pinMap, (*i_5));
						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
						x.writeEnable = T80_;
					}
					goto LA72_;
					LA78_: ;
					{
						NU32 T84_;
						if (!((*i_5) == ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 24))) goto LA82_;
						T84_ = (NU32)0;
						T84_ = X5BX5D___izypgEXDrOPhvdwKMbE2zw(pinMap, (*i_5));
						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
						x.chipEnable = T84_;
					}
					goto LA72_;
					LA82_: ;
					LA72_: ;
				}
				LA70_: ;
				{
					NIM_BOOL T87_;
					T87_ = (NIM_BOOL)0;
					T87_ = contains__JHpRzcF21xoNQYgBrsWWkg(shiftMap, (*i_5));
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
					if (!T87_) goto LA88_;
					{
						if (!((*i_5) == ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 25))) goto LA92_;
						x.outputEnable = (*shiftPins).data;
					}
					goto LA90_;
					LA92_: ;
					{
						if (!((*i_5) == ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 26))) goto LA95_;
						x.writeEnable = (*shiftPins).data;
					}
					goto LA90_;
					LA95_: ;
					{
						if (!((*i_5) == ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 24))) goto LA98_;
						x.chipEnable = (*shiftPins).data;
					}
					goto LA90_;
					LA98_: ;
					LA90_: ;
					eqcopy___71gLqJJRAXmB7dO800Kngg((&x.shiftMap), shiftMap);
					eqcopy___tB0UasZGInHb3JJUEVb0IQ(&x.shiftPins, shiftPins);
				}
				LA88_: ;
				if (nimAddInt(i_6, ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_91)) { raiseOverflow(); goto LA1_;
};
				i_6 = (NI)(TM__c0pjnlBjpnggBqxewNeRCw_91);
				{
					if (!!((((NI) 3) == L_3))) goto LA102_;
					failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__c0pjnlBjpnggBqxewNeRCw_92);
					if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				}
				LA102_: ;
			} LA66: ;
		}
	}
	(*Result) = x;
	nimZeroMem((void*)(&x), sizeof(tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw));
	eqdestroy___nKP2x9cUu59a2GFPeZhMgNkw((&x));
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		eqdestroy___nKP2x9cUu59a2GFPeZhMgNkw((&x));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, print__UUnZ3sMEKzCq1Hl3GQIHXgpicostdlib)(NCSTRING s) {
	int T1_;
	T1_ = (int)0;
	T1_ = printf(s);
}
static N_INLINE(NIM_BOOL, isFilled__5Qpmu5QqwDY0esVXn6wf7wtables)(NI hcode) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = !((hcode == ((NI) 0)));
	return result;
}
static N_INLINE(NIM_BOOL, testBit__xQ0UxJYZQBHsfFh8l32Cwwbitops)(NI v, NI bit) {
	NIM_BOOL result;
	NI mask;
{	result = (NIM_BOOL)0;
	mask = (NI)((NU32)(((NI) 1)) << (NU32)(bit));
	result = ((NI)(v & mask) == mask);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NF, toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem)(NI i) {
	NF result;
	result = (NF)0;
	result = ((NF) (i));
	return result;
}
static N_INLINE(NF, abs__BRaAqinz6OWTHkALb4oj6Qsystem)(NF x) {
	NF result;
	NF colontmpD_;
	NF colontmpD__2;
	result = (NF)0;
	colontmpD_ = (NF)0;
	colontmpD__2 = (NF)0;
	{
		if (!(x < 0.0)) goto LA3_;
		colontmpD_ = -(x);
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		colontmpD__2 = x;
		result = colontmpD__2;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	NI r;
	NF floatProd;
	NF T1_;
	NF T2_;
	NF resAsFloat;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU32)(((NU) (a))) * (NU32)(((NU) (b))))));
	T1_ = (NF)0;
	T1_ = toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem(a);
	T2_ = (NF)0;
	T2_ = toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem(b);
	floatProd = ((NF)(T1_) * (NF)(T2_));
	resAsFloat = toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem(r);
	{
		if (!(resAsFloat == floatProd)) goto LA5_;
		(*res) = r;
	}
	goto LA3_;
	LA5_: ;
	{
		{
			NF T10_;
			NF T11_;
			T10_ = (NF)0;
			T10_ = abs__BRaAqinz6OWTHkALb4oj6Qsystem(((NF)(resAsFloat) - (NF)(floatProd)));
			T11_ = (NF)0;
			T11_ = abs__BRaAqinz6OWTHkALb4oj6Qsystem(floatProd);
			if (!(((NF)(3.2000000000000000e+01) * (NF)(T10_)) <= T11_)) goto LA12_;
			(*res) = r;
		}
		goto LA8_;
		LA12_: ;
		{
			result = NIM_TRUE;
		}
		LA8_: ;
	}
	LA3_: ;
	return result;
}
static N_INLINE(void, setMask__2tLl5NGxkOJmt6UtOu9aUCgbitops)(NI* v, NI mask) {
	(*v) = (NI)((*v) | mask);
}
static N_INLINE(void, setBit__vSyO019bzxNbOxIELRXKYjAbitops)(NI* v, NI bit) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	setMask__2tLl5NGxkOJmt6UtOu9aUCgbitops(v, (NI)((NU32)(((NI) 1)) << (NU32)(bit)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, clearMask__2tLl5NGxkOJmt6UtOu9aUCg_2bitops)(NI* v, NI mask) {
	(*v) = (NI)((*v) & (NI)((NU32) ~(mask)));
}
static N_INLINE(void, clearBit__vSyO019bzxNbOxIELRXKYjA_2bitops)(NI* v, NI bit) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	clearMask__2tLl5NGxkOJmt6UtOu9aUCg_2bitops(v, (NI)((NU32)(((NI) 1)) << (NU32)(bit)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, setInputs__ZEyXVzX0Jjh4Lm2m3u0kqg)(tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw* eeprom, NI address, NIM_BOOL oe, NIM_BOOL we, NIM_BOOL ce) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		NI T4_;
		NI T5_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NI)0;
		T4_ = len__CFEeD1cbzlG3EqLWcLD4eg((*eeprom).addressPins);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if ((T4_) < ((NI) 0) || (T4_) > ((NI) 2147483647)){ raiseRangeErrorI(T4_, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		T5_ = (NI)0;
		T5_ = roof___M1yk6GvJhRrReRZgYouX8g(((NI) 2), ((NI) (T4_)));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T3_ = (T5_ < address);
		if (T3_) goto LA6_;
		T3_ = (address < ((NI) 0));
		LA6_: ;
		if (!T3_) goto LA7_;
		echoBinSafe(TM__c0pjnlBjpnggBqxewNeRCw_93, 1);
	}
	LA7_: ;
	{
		NIM_BOOL T11_;
		T11_ = (NIM_BOOL)0;
		T11_ = ((*eeprom).addressSetup == ((tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg) 0));
		if (T11_) goto LA12_;
		T11_ = ((*eeprom).addressSetup == ((tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg) 2));
		LA12_: ;
		if (!T11_) goto LA13_;
		{
			tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key;
			NU32 value;
			NI L;
			key = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
			value = (NU32)0;
			L = len__CFEeD1cbzlG3EqLWcLD4eg((*eeprom).addressPins);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			{
				NI h;
				NI colontmp_;
				NI T17_;
				NI res;
				h = (NI)0;
				colontmp_ = (NI)0;
				T17_ = ((*eeprom).addressPins.data.len-1);
				colontmp_ = T17_;
				res = ((NI) 0);
				{
					while (1) {
						NI TM__c0pjnlBjpnggBqxewNeRCw_97;
						if (!(res <= colontmp_)) goto LA19;
						h = res;
						{
							NIM_BOOL T22_;
							if ((NU)(h) >= (NU)(*eeprom).addressPins.data.len){ raiseIndexError2(h,(*eeprom).addressPins.data.len-1); goto BeforeRet_;
}
							T22_ = (NIM_BOOL)0;
							T22_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables((*eeprom).addressPins.data.p->data[h].Field0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!T22_) goto LA23_;
							if ((NU)(h) >= (NU)(*eeprom).addressPins.data.len){ raiseIndexError2(h,(*eeprom).addressPins.data.len-1); goto BeforeRet_;
}
							key = (*eeprom).addressPins.data.p->data[h].Field1;
							if ((NU)(h) >= (NU)(*eeprom).addressPins.data.len){ raiseIndexError2(h,(*eeprom).addressPins.data.len-1); goto BeforeRet_;
}
							value = (*eeprom).addressPins.data.p->data[h].Field2;
							{
								NIM_BOOL T27_;
								NU32 T30_;
								NU32 T31_;
								T27_ = (NIM_BOOL)0;
								T27_ = contains__JHpRzcF21xoNQYgBrsWWkg((*eeprom).shiftMap, key);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								if (!!(T27_)) goto LA28_;
								T30_ = (NU32)0;
								T30_ = X5BX5D___izypgEXDrOPhvdwKMbE2zw((*eeprom).addressPins, key);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								gpio_init(T30_);
								T31_ = (NU32)0;
								T31_ = X5BX5D___izypgEXDrOPhvdwKMbE2zw((*eeprom).addressPins, key);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								gpio_set_dir(T31_, NIM_TRUE);
								{
									NIM_BOOL T34_;
									NU32 T37_;
									if ((((NI) (key))) < ((NI) 0) || (((NI) (key))) > ((NI) 31)){ raiseRangeErrorI(((NI) (key)), ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
									T34_ = (NIM_BOOL)0;
									T34_ = testBit__xQ0UxJYZQBHsfFh8l32Cwwbitops(address, ((NI) (((NI) (key)))));
									if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
									if (!T34_) goto LA35_;
									T37_ = (NU32)0;
									T37_ = X5BX5D___izypgEXDrOPhvdwKMbE2zw((*eeprom).addressPins, key);
									if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
									gpio_put(T37_, ((NU32) 1));
								}
								goto LA32_;
								LA35_: ;
								{
									NU32 T39_;
									T39_ = (NU32)0;
									T39_ = X5BX5D___izypgEXDrOPhvdwKMbE2zw((*eeprom).addressPins, key);
									if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
									gpio_put(T39_, ((NU32) 0));
								}
								LA32_: ;
							}
							LA28_: ;
							{
								NI T42_;
								T42_ = (NI)0;
								T42_ = len__CFEeD1cbzlG3EqLWcLD4eg((*eeprom).addressPins);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								if (!!((T42_ == L))) goto LA43_;
								failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__c0pjnlBjpnggBqxewNeRCw_96);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							}
							LA43_: ;
						}
						LA23_: ;
						if (nimAddInt(res, ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_97)) { raiseOverflow(); goto BeforeRet_;
};
						res = (NI)(TM__c0pjnlBjpnggBqxewNeRCw_97);
					} LA19: ;
				}
			}
		}
		{
			NIM_BOOL T47_;
			T47_ = (NIM_BOOL)0;
			T47_ = contains__JHpRzcF21xoNQYgBrsWWkg((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 25));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T47_)) goto LA48_;
			gpio_init((*eeprom).outputEnable);
			gpio_put((*eeprom).outputEnable, ((NU32) 1));
			gpio_set_dir((*eeprom).outputEnable, NIM_TRUE);
			{
				if (!oe) goto LA52_;
				gpio_put((*eeprom).outputEnable, ((NU32) 0));
			}
			goto LA50_;
			LA52_: ;
			{
				gpio_put((*eeprom).outputEnable, ((NU32) 1));
			}
			LA50_: ;
		}
		LA48_: ;
		{
			NIM_BOOL T57_;
			T57_ = (NIM_BOOL)0;
			T57_ = contains__JHpRzcF21xoNQYgBrsWWkg((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 26));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T57_)) goto LA58_;
			gpio_init((*eeprom).writeEnable);
			gpio_put((*eeprom).writeEnable, ((NU32) 1));
			gpio_set_dir((*eeprom).writeEnable, NIM_TRUE);
			{
				if (!we) goto LA62_;
				gpio_put((*eeprom).chipEnable, ((NU32) 0));
			}
			goto LA60_;
			LA62_: ;
			{
				gpio_put((*eeprom).chipEnable, ((NU32) 1));
			}
			LA60_: ;
		}
		LA58_: ;
		{
			NIM_BOOL T67_;
			T67_ = (NIM_BOOL)0;
			T67_ = contains__JHpRzcF21xoNQYgBrsWWkg((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 24));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!!(T67_)) goto LA68_;
			gpio_init((*eeprom).chipEnable);
			gpio_put((*eeprom).chipEnable, ((NU32) 1));
			gpio_set_dir((*eeprom).chipEnable, NIM_TRUE);
			{
				if (!ce) goto LA72_;
				gpio_put((*eeprom).chipEnable, ((NU32) 0));
			}
			goto LA70_;
			LA72_: ;
			{
				gpio_put((*eeprom).chipEnable, ((NU32) 1));
			}
			LA70_: ;
		}
		LA68_: ;
	}
	LA13_: ;
	{
		NIM_BOOL T77_;
		NI word;
		NI pos;
		NI max;
		NI TM__c0pjnlBjpnggBqxewNeRCw_98;
		NI TM__c0pjnlBjpnggBqxewNeRCw_99;
		T77_ = (NIM_BOOL)0;
		T77_ = ((*eeprom).addressSetup == ((tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg) 1));
		if (T77_) goto LA78_;
		T77_ = ((*eeprom).addressSetup == ((tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg) 2));
		LA78_: ;
		if (!T77_) goto LA79_;
		gpio_init((*(*eeprom).shiftPins).data);
		gpio_init((*(*eeprom).shiftPins).clock);
		gpio_init((*(*eeprom).shiftPins).latch);
		gpio_set_dir((*(*eeprom).shiftPins).data, NIM_TRUE);
		gpio_set_dir((*(*eeprom).shiftPins).clock, NIM_TRUE);
		gpio_set_dir((*(*eeprom).shiftPins).latch, NIM_TRUE);
		word = (NI)0;
		pos = (NI)0;
		if (nimMulInt((*(*eeprom).shiftPins).shifterBytes, ((NI) 8), &TM__c0pjnlBjpnggBqxewNeRCw_98)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimSubInt((NI)(TM__c0pjnlBjpnggBqxewNeRCw_98), ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_99)) { raiseOverflow(); goto BeforeRet_;
};
		max = (NI)(TM__c0pjnlBjpnggBqxewNeRCw_99);
		{
			tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key_2;
			NU32 value_2;
			NI L_2;
			key_2 = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
			value_2 = (NU32)0;
			L_2 = len__CFEeD1cbzlG3EqLWcLD4eg((*eeprom).addressPins);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			{
				NI h_2;
				NI colontmp__2;
				NI T83_;
				NI res_2;
				h_2 = (NI)0;
				colontmp__2 = (NI)0;
				T83_ = ((*eeprom).addressPins.data.len-1);
				colontmp__2 = T83_;
				res_2 = ((NI) 0);
				{
					while (1) {
						NI TM__c0pjnlBjpnggBqxewNeRCw_105;
						if (!(res_2 <= colontmp__2)) goto LA85;
						h_2 = res_2;
						{
							NIM_BOOL T88_;
							if ((NU)(h_2) >= (NU)(*eeprom).addressPins.data.len){ raiseIndexError2(h_2,(*eeprom).addressPins.data.len-1); goto BeforeRet_;
}
							T88_ = (NIM_BOOL)0;
							T88_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables((*eeprom).addressPins.data.p->data[h_2].Field0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!T88_) goto LA89_;
							if ((NU)(h_2) >= (NU)(*eeprom).addressPins.data.len){ raiseIndexError2(h_2,(*eeprom).addressPins.data.len-1); goto BeforeRet_;
}
							key_2 = (*eeprom).addressPins.data.p->data[h_2].Field1;
							if ((NU)(h_2) >= (NU)(*eeprom).addressPins.data.len){ raiseIndexError2(h_2,(*eeprom).addressPins.data.len-1); goto BeforeRet_;
}
							value_2 = (*eeprom).addressPins.data.p->data[h_2].Field2;
							{
								NIM_BOOL T93_;
								T93_ = (NIM_BOOL)0;
								T93_ = contains__JHpRzcF21xoNQYgBrsWWkg((*eeprom).shiftMap, key_2);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								if (!T93_) goto LA94_;
								pos = getOrDefault__rJcaoBQ5Dqs3bvDKIAnm9aA((*eeprom).shiftMap, key_2, ((NI) 0));
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								{
									if (!(((NI) 0) <= pos)) goto LA98_;
									{
										NIM_BOOL T102_;
										NI TM__c0pjnlBjpnggBqxewNeRCw_100;
										if ((((NI) (key_2))) < ((NI) 0) || (((NI) (key_2))) > ((NI) 31)){ raiseRangeErrorI(((NI) (key_2)), ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
										T102_ = (NIM_BOOL)0;
										T102_ = testBit__xQ0UxJYZQBHsfFh8l32Cwwbitops(address, ((NI) (((NI) (key_2)))));
										if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
										if (!T102_) goto LA103_;
										if (nimSubInt(max, pos, &TM__c0pjnlBjpnggBqxewNeRCw_100)) { raiseOverflow(); goto BeforeRet_;
};
										if (((NI)(TM__c0pjnlBjpnggBqxewNeRCw_100)) < ((NI) 0) || ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_100)) > ((NI) 31)){ raiseRangeErrorI((NI)(TM__c0pjnlBjpnggBqxewNeRCw_100), ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
										setBit__vSyO019bzxNbOxIELRXKYjAbitops((&word), ((NI) ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_100))));
										if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
									}
									goto LA100_;
									LA103_: ;
									{
										NI TM__c0pjnlBjpnggBqxewNeRCw_101;
										if (nimSubInt(max, pos, &TM__c0pjnlBjpnggBqxewNeRCw_101)) { raiseOverflow(); goto BeforeRet_;
};
										if (((NI)(TM__c0pjnlBjpnggBqxewNeRCw_101)) < ((NI) 0) || ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_101)) > ((NI) 31)){ raiseRangeErrorI((NI)(TM__c0pjnlBjpnggBqxewNeRCw_101), ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
										clearBit__vSyO019bzxNbOxIELRXKYjA_2bitops((&word), ((NI) ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_101))));
										if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
									}
									LA100_: ;
								}
								goto LA96_;
								LA98_: ;
								{
									{
										NIM_BOOL T109_;
										NI TM__c0pjnlBjpnggBqxewNeRCw_102;
										if ((((NI) (key_2))) < ((NI) 0) || (((NI) (key_2))) > ((NI) 31)){ raiseRangeErrorI(((NI) (key_2)), ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
										T109_ = (NIM_BOOL)0;
										T109_ = testBit__xQ0UxJYZQBHsfFh8l32Cwwbitops(address, ((NI) (((NI) (key_2)))));
										if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
										if (!T109_) goto LA110_;
										if (nimMulInt(pos, ((NI) -1), &TM__c0pjnlBjpnggBqxewNeRCw_102)) { raiseOverflow(); goto BeforeRet_;
};
										if (((NI)(TM__c0pjnlBjpnggBqxewNeRCw_102)) < ((NI) 0) || ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_102)) > ((NI) 31)){ raiseRangeErrorI((NI)(TM__c0pjnlBjpnggBqxewNeRCw_102), ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
										setBit__vSyO019bzxNbOxIELRXKYjAbitops((&word), ((NI) ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_102))));
										if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
									}
									goto LA107_;
									LA110_: ;
									{
										NI TM__c0pjnlBjpnggBqxewNeRCw_103;
										if (nimMulInt(pos, ((NI) -1), &TM__c0pjnlBjpnggBqxewNeRCw_103)) { raiseOverflow(); goto BeforeRet_;
};
										if (((NI)(TM__c0pjnlBjpnggBqxewNeRCw_103)) < ((NI) 0) || ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_103)) > ((NI) 31)){ raiseRangeErrorI((NI)(TM__c0pjnlBjpnggBqxewNeRCw_103), ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
										clearBit__vSyO019bzxNbOxIELRXKYjA_2bitops((&word), ((NI) ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_103))));
										if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
									}
									LA107_: ;
								}
								LA96_: ;
							}
							LA94_: ;
							{
								NI T115_;
								T115_ = (NI)0;
								T115_ = len__CFEeD1cbzlG3EqLWcLD4eg((*eeprom).addressPins);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								if (!!((T115_ == L_2))) goto LA116_;
								failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__c0pjnlBjpnggBqxewNeRCw_104);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							}
							LA116_: ;
						}
						LA89_: ;
						if (nimAddInt(res_2, ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_105)) { raiseOverflow(); goto BeforeRet_;
};
						res_2 = (NI)(TM__c0pjnlBjpnggBqxewNeRCw_105);
					} LA85: ;
				}
			}
		}
		{
			NIM_BOOL T120_;
			T120_ = (NIM_BOOL)0;
			T120_ = contains__JHpRzcF21xoNQYgBrsWWkg((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 25));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T120_) goto LA121_;
			{
				NI T125_;
				T125_ = (NI)0;
				T125_ = X5BX5D___E3nu0mxbUgUihx3VzztAZQ((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 25));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(((NI) 0) <= T125_)) goto LA126_;
				{
					NI T132_;
					if (!oe) goto LA130_;
					T132_ = (NI)0;
					T132_ = X5BX5D___E3nu0mxbUgUihx3VzztAZQ((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 25));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if ((T132_) < ((NI) 0) || (T132_) > ((NI) 31)){ raiseRangeErrorI(T132_, ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
					clearBit__vSyO019bzxNbOxIELRXKYjA_2bitops((&word), ((NI) (T132_)));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				goto LA128_;
				LA130_: ;
				{
					NI T134_;
					T134_ = (NI)0;
					T134_ = X5BX5D___E3nu0mxbUgUihx3VzztAZQ((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 25));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if ((T134_) < ((NI) 0) || (T134_) > ((NI) 31)){ raiseRangeErrorI(T134_, ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
					setBit__vSyO019bzxNbOxIELRXKYjAbitops((&word), ((NI) (T134_)));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				LA128_: ;
			}
			goto LA123_;
			LA126_: ;
			{
				{
					NI T140_;
					NI TM__c0pjnlBjpnggBqxewNeRCw_106;
					NI TM__c0pjnlBjpnggBqxewNeRCw_107;
					if (!oe) goto LA138_;
					T140_ = (NI)0;
					T140_ = X5BX5D___E3nu0mxbUgUihx3VzztAZQ((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 25));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (nimMulInt(T140_, ((NI) -1), &TM__c0pjnlBjpnggBqxewNeRCw_106)) { raiseOverflow(); goto BeforeRet_;
};
					if (nimSubInt((NI)(TM__c0pjnlBjpnggBqxewNeRCw_106), ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_107)) { raiseOverflow(); goto BeforeRet_;
};
					if (((NI)(TM__c0pjnlBjpnggBqxewNeRCw_107)) < ((NI) 0) || ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_107)) > ((NI) 31)){ raiseRangeErrorI((NI)(TM__c0pjnlBjpnggBqxewNeRCw_107), ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
					clearBit__vSyO019bzxNbOxIELRXKYjA_2bitops((&word), ((NI) ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_107))));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				goto LA136_;
				LA138_: ;
				{
					NI T142_;
					NI TM__c0pjnlBjpnggBqxewNeRCw_108;
					NI TM__c0pjnlBjpnggBqxewNeRCw_109;
					T142_ = (NI)0;
					T142_ = X5BX5D___E3nu0mxbUgUihx3VzztAZQ((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 25));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (nimMulInt(T142_, ((NI) -1), &TM__c0pjnlBjpnggBqxewNeRCw_108)) { raiseOverflow(); goto BeforeRet_;
};
					if (nimSubInt((NI)(TM__c0pjnlBjpnggBqxewNeRCw_108), ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_109)) { raiseOverflow(); goto BeforeRet_;
};
					if (((NI)(TM__c0pjnlBjpnggBqxewNeRCw_109)) < ((NI) 0) || ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_109)) > ((NI) 31)){ raiseRangeErrorI((NI)(TM__c0pjnlBjpnggBqxewNeRCw_109), ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
					setBit__vSyO019bzxNbOxIELRXKYjAbitops((&word), ((NI) ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_109))));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				LA136_: ;
			}
			LA123_: ;
		}
		LA121_: ;
		{
			NIM_BOOL T145_;
			T145_ = (NIM_BOOL)0;
			T145_ = contains__JHpRzcF21xoNQYgBrsWWkg((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 26));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T145_) goto LA146_;
			{
				NI T150_;
				T150_ = (NI)0;
				T150_ = X5BX5D___E3nu0mxbUgUihx3VzztAZQ((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 26));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(((NI) 0) <= T150_)) goto LA151_;
				{
					NI T157_;
					if (!we) goto LA155_;
					T157_ = (NI)0;
					T157_ = X5BX5D___E3nu0mxbUgUihx3VzztAZQ((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 26));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if ((T157_) < ((NI) 0) || (T157_) > ((NI) 31)){ raiseRangeErrorI(T157_, ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
					clearBit__vSyO019bzxNbOxIELRXKYjA_2bitops((&word), ((NI) (T157_)));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				goto LA153_;
				LA155_: ;
				{
					NI T159_;
					T159_ = (NI)0;
					T159_ = X5BX5D___E3nu0mxbUgUihx3VzztAZQ((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 26));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if ((T159_) < ((NI) 0) || (T159_) > ((NI) 31)){ raiseRangeErrorI(T159_, ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
					setBit__vSyO019bzxNbOxIELRXKYjAbitops((&word), ((NI) (T159_)));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				LA153_: ;
			}
			goto LA148_;
			LA151_: ;
			{
				{
					NI T165_;
					NI TM__c0pjnlBjpnggBqxewNeRCw_110;
					NI TM__c0pjnlBjpnggBqxewNeRCw_111;
					if (!we) goto LA163_;
					T165_ = (NI)0;
					T165_ = X5BX5D___E3nu0mxbUgUihx3VzztAZQ((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 26));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (nimMulInt(T165_, ((NI) -1), &TM__c0pjnlBjpnggBqxewNeRCw_110)) { raiseOverflow(); goto BeforeRet_;
};
					if (nimSubInt((NI)(TM__c0pjnlBjpnggBqxewNeRCw_110), ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_111)) { raiseOverflow(); goto BeforeRet_;
};
					if (((NI)(TM__c0pjnlBjpnggBqxewNeRCw_111)) < ((NI) 0) || ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_111)) > ((NI) 31)){ raiseRangeErrorI((NI)(TM__c0pjnlBjpnggBqxewNeRCw_111), ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
					clearBit__vSyO019bzxNbOxIELRXKYjA_2bitops((&word), ((NI) ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_111))));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				goto LA161_;
				LA163_: ;
				{
					NI T167_;
					NI TM__c0pjnlBjpnggBqxewNeRCw_112;
					NI TM__c0pjnlBjpnggBqxewNeRCw_113;
					T167_ = (NI)0;
					T167_ = X5BX5D___E3nu0mxbUgUihx3VzztAZQ((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 26));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (nimMulInt(T167_, ((NI) -1), &TM__c0pjnlBjpnggBqxewNeRCw_112)) { raiseOverflow(); goto BeforeRet_;
};
					if (nimSubInt((NI)(TM__c0pjnlBjpnggBqxewNeRCw_112), ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_113)) { raiseOverflow(); goto BeforeRet_;
};
					if (((NI)(TM__c0pjnlBjpnggBqxewNeRCw_113)) < ((NI) 0) || ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_113)) > ((NI) 31)){ raiseRangeErrorI((NI)(TM__c0pjnlBjpnggBqxewNeRCw_113), ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
					setBit__vSyO019bzxNbOxIELRXKYjAbitops((&word), ((NI) ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_113))));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				LA161_: ;
			}
			LA148_: ;
		}
		LA146_: ;
		{
			NIM_BOOL T170_;
			T170_ = (NIM_BOOL)0;
			T170_ = contains__JHpRzcF21xoNQYgBrsWWkg((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 24));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T170_) goto LA171_;
			{
				NI T175_;
				T175_ = (NI)0;
				T175_ = X5BX5D___E3nu0mxbUgUihx3VzztAZQ((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 24));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(((NI) 0) <= T175_)) goto LA176_;
				{
					NI T182_;
					if (!ce) goto LA180_;
					T182_ = (NI)0;
					T182_ = X5BX5D___E3nu0mxbUgUihx3VzztAZQ((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 24));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if ((T182_) < ((NI) 0) || (T182_) > ((NI) 31)){ raiseRangeErrorI(T182_, ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
					clearBit__vSyO019bzxNbOxIELRXKYjA_2bitops((&word), ((NI) (T182_)));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				goto LA178_;
				LA180_: ;
				{
					NI T184_;
					T184_ = (NI)0;
					T184_ = X5BX5D___E3nu0mxbUgUihx3VzztAZQ((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 24));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if ((T184_) < ((NI) 0) || (T184_) > ((NI) 31)){ raiseRangeErrorI(T184_, ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
					setBit__vSyO019bzxNbOxIELRXKYjAbitops((&word), ((NI) (T184_)));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				LA178_: ;
			}
			goto LA173_;
			LA176_: ;
			{
				{
					NI T190_;
					NI TM__c0pjnlBjpnggBqxewNeRCw_114;
					NI TM__c0pjnlBjpnggBqxewNeRCw_115;
					if (!ce) goto LA188_;
					T190_ = (NI)0;
					T190_ = X5BX5D___E3nu0mxbUgUihx3VzztAZQ((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 24));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (nimMulInt(T190_, ((NI) -1), &TM__c0pjnlBjpnggBqxewNeRCw_114)) { raiseOverflow(); goto BeforeRet_;
};
					if (nimSubInt((NI)(TM__c0pjnlBjpnggBqxewNeRCw_114), ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_115)) { raiseOverflow(); goto BeforeRet_;
};
					if (((NI)(TM__c0pjnlBjpnggBqxewNeRCw_115)) < ((NI) 0) || ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_115)) > ((NI) 31)){ raiseRangeErrorI((NI)(TM__c0pjnlBjpnggBqxewNeRCw_115), ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
					clearBit__vSyO019bzxNbOxIELRXKYjA_2bitops((&word), ((NI) ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_115))));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				goto LA186_;
				LA188_: ;
				{
					NI T192_;
					NI TM__c0pjnlBjpnggBqxewNeRCw_116;
					NI TM__c0pjnlBjpnggBqxewNeRCw_117;
					T192_ = (NI)0;
					T192_ = X5BX5D___E3nu0mxbUgUihx3VzztAZQ((*eeprom).shiftMap, ((tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w) 24));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (nimMulInt(T192_, ((NI) -1), &TM__c0pjnlBjpnggBqxewNeRCw_116)) { raiseOverflow(); goto BeforeRet_;
};
					if (nimSubInt((NI)(TM__c0pjnlBjpnggBqxewNeRCw_116), ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_117)) { raiseOverflow(); goto BeforeRet_;
};
					if (((NI)(TM__c0pjnlBjpnggBqxewNeRCw_117)) < ((NI) 0) || ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_117)) > ((NI) 31)){ raiseRangeErrorI((NI)(TM__c0pjnlBjpnggBqxewNeRCw_117), ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
					setBit__vSyO019bzxNbOxIELRXKYjAbitops((&word), ((NI) ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_117))));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				LA186_: ;
			}
			LA173_: ;
		}
		LA171_: ;
		{
			NU8 output;
			if (!((*(*eeprom).shiftPins).shifterBytes == ((NI) 1))) goto LA195_;
			output = ((NU8) (word));
			shiftOut__oh9bttFDj3znjBotTg4Gv8w((*(*eeprom).shiftPins).data, (*(*eeprom).shiftPins).clock, output);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			pulse__3gK3JPW72sWOe5GpvMphTA((*(*eeprom).shiftPins).latch, ((NU32) 0));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA193_;
		LA195_: ;
		{
			NU16 output_2;
			if (!((*(*eeprom).shiftPins).shifterBytes == ((NI) 2))) goto LA198_;
			output_2 = ((NU16) (word));
			shiftOut__GiW9apWzGLHTCa4iEYxm0KQ((*(*eeprom).shiftPins).data, (*(*eeprom).shiftPins).clock, output_2);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			pulse__3gK3JPW72sWOe5GpvMphTA((*(*eeprom).shiftPins).latch, ((NU32) 0));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA193_;
		LA198_: ;
		{
			NU16 outputLower;
			NU8 outputUpper;
			if (!((*(*eeprom).shiftPins).shifterBytes == ((NI) 3))) goto LA201_;
			outputLower = ((NU16) (word));
			outputUpper = ((NU8) ((NI)((NI32)(address) >> (NU32)(((NI) 16)))));
			shiftOut__GiW9apWzGLHTCa4iEYxm0KQ((*(*eeprom).shiftPins).data, (*(*eeprom).shiftPins).clock, outputLower);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			pulse__3gK3JPW72sWOe5GpvMphTA((*(*eeprom).shiftPins).latch, ((NU32) 0));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			shiftOut__oh9bttFDj3znjBotTg4Gv8w((*(*eeprom).shiftPins).data, (*(*eeprom).shiftPins).clock, outputUpper);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			pulse__3gK3JPW72sWOe5GpvMphTA((*(*eeprom).shiftPins).latch, ((NU32) 0));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA193_;
		LA201_: ;
		{
			NU32 output_3;
			if (!((*(*eeprom).shiftPins).shifterBytes == ((NI) 4))) goto LA204_;
			output_3 = ((NU32) (word));
			shiftOut__e069aaqO5irzbgrm9aIV6Hzw((*(*eeprom).shiftPins).data, (*(*eeprom).shiftPins).clock, output_3);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			pulse__3gK3JPW72sWOe5GpvMphTA((*(*eeprom).shiftPins).latch, ((NU32) 0));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA193_;
		LA204_: ;
		{
			echoBinSafe(TM__c0pjnlBjpnggBqxewNeRCw_118, 1);
			exit(((NI) 1));
		}
		LA193_: ;
	}
	LA79_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, writeEEPROM__AFzodz8r7BixDUv79cqnCsg)(tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw* eeprom, NI address, NI data) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	sleep_ms(((NU32) 10));
	setInputs__ZEyXVzX0Jjh4Lm2m3u0kqg(eeprom, address, NIM_FALSE, NIM_FALSE, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key;
		NU32 value;
		NI L;
		key = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
		value = (NU32)0;
		L = len__CFEeD1cbzlG3EqLWcLD4eg((*eeprom).dataPins);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			NI h;
			NI colontmp_;
			NI T3_;
			NI res;
			h = (NI)0;
			colontmp_ = (NI)0;
			T3_ = ((*eeprom).dataPins.data.len-1);
			colontmp_ = T3_;
			res = ((NI) 0);
			{
				while (1) {
					NI TM__c0pjnlBjpnggBqxewNeRCw_122;
					if (!(res <= colontmp_)) goto LA5;
					h = res;
					{
						NIM_BOOL T8_;
						if ((NU)(h) >= (NU)(*eeprom).dataPins.data.len){ raiseIndexError2(h,(*eeprom).dataPins.data.len-1); goto BeforeRet_;
}
						T8_ = (NIM_BOOL)0;
						T8_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables((*eeprom).dataPins.data.p->data[h].Field0);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						if (!T8_) goto LA9_;
						if ((NU)(h) >= (NU)(*eeprom).dataPins.data.len){ raiseIndexError2(h,(*eeprom).dataPins.data.len-1); goto BeforeRet_;
}
						key = (*eeprom).dataPins.data.p->data[h].Field1;
						if ((NU)(h) >= (NU)(*eeprom).dataPins.data.len){ raiseIndexError2(h,(*eeprom).dataPins.data.len-1); goto BeforeRet_;
}
						value = (*eeprom).dataPins.data.p->data[h].Field2;
						gpio_init(value);
						gpio_set_dir(value, NIM_TRUE);
						{
							NI TM__c0pjnlBjpnggBqxewNeRCw_120;
							NIM_BOOL T13_;
							if (nimSubInt(((NI) (key)), ((NI) 16), &TM__c0pjnlBjpnggBqxewNeRCw_120)) { raiseOverflow(); goto BeforeRet_;
};
							if (((NI)(TM__c0pjnlBjpnggBqxewNeRCw_120)) < ((NI) 0) || ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_120)) > ((NI) 31)){ raiseRangeErrorI((NI)(TM__c0pjnlBjpnggBqxewNeRCw_120), ((NI) 0), ((NI) 31)); goto BeforeRet_;
}
							T13_ = (NIM_BOOL)0;
							T13_ = testBit__xQ0UxJYZQBHsfFh8l32Cwwbitops(data, ((NI) ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_120))));
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!T13_) goto LA14_;
							gpio_put(value, ((NU32) 1));
						}
						goto LA11_;
						LA14_: ;
						{
							gpio_put(value, ((NU32) 0));
						}
						LA11_: ;
						{
							NI T19_;
							T19_ = (NI)0;
							T19_ = len__CFEeD1cbzlG3EqLWcLD4eg((*eeprom).dataPins);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!!((T19_ == L))) goto LA20_;
							failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__c0pjnlBjpnggBqxewNeRCw_121);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						}
						LA20_: ;
					}
					LA9_: ;
					if (nimAddInt(res, ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_122)) { raiseOverflow(); goto BeforeRet_;
};
					res = (NI)(TM__c0pjnlBjpnggBqxewNeRCw_122);
				} LA5: ;
			}
		}
	}
	sleep_ms(((NU32) 10));
	setInputs__ZEyXVzX0Jjh4Lm2m3u0kqg(eeprom, address, NIM_FALSE, NIM_TRUE, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	sleep_ms(((NU32) 2));
	setInputs__ZEyXVzX0Jjh4Lm2m3u0kqg(eeprom, address, NIM_FALSE, NIM_FALSE, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	sleep_ms(((NU32) 10));
	}BeforeRet_: ;
}
static N_INLINE(void, setMask__RWQ9atjq3mwVbUkjPu2R4xgbitops)(NU8* v, NU8 mask) {
	(*v) = (NU8)((*v) | mask);
}
static N_INLINE(void, setBit__XwPFzY0nKw9aMJz1uiqKS8gbitops)(NU8* v, NI bit) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	setMask__RWQ9atjq3mwVbUkjPu2R4xgbitops(v, (NU8)((NU32)(((NU8) 1)) << (NU32)(bit)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, clearMask__RWQ9atjq3mwVbUkjPu2R4xg_2bitops)(NU8* v, NU8 mask) {
	(*v) = (NU8)((*v) & (NU8)((NU8) ~(mask)));
}
static N_INLINE(void, clearBit__XwPFzY0nKw9aMJz1uiqKS8g_2bitops)(NU8* v, NI bit) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	clearMask__RWQ9atjq3mwVbUkjPu2R4xg_2bitops(v, (NU8)((NU32)(((NU8) 1)) << (NU32)(bit)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NU8, readEEPROM__fg3FnZOkcs9cAYqFI1VAy2A)(tyObject_EEPROM__NGYt8NFdbBfBTnbRmmAOdw* eeprom, NI address) {
	NU8 result;
	NU8 data;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU8)0;
	sleep_ms(((NU32) 10));
	setInputs__ZEyXVzX0Jjh4Lm2m3u0kqg(eeprom, address, NIM_TRUE, NIM_FALSE, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	data = (NU8)0;
	{
		if (!((*eeprom).dataSetup == ((tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg) 0))) goto LA3_;
		{
			tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key;
			NU32 value;
			NI L;
			key = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
			value = (NU32)0;
			L = len__CFEeD1cbzlG3EqLWcLD4eg((*eeprom).dataPins);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			{
				NI h;
				NI colontmp_;
				NI T7_;
				NI res;
				h = (NI)0;
				colontmp_ = (NI)0;
				T7_ = ((*eeprom).dataPins.data.len-1);
				colontmp_ = T7_;
				res = ((NI) 0);
				{
					while (1) {
						NI TM__c0pjnlBjpnggBqxewNeRCw_126;
						if (!(res <= colontmp_)) goto LA9;
						h = res;
						{
							NIM_BOOL T12_;
							NU32 T15_;
							NU32 T16_;
							if ((NU)(h) >= (NU)(*eeprom).dataPins.data.len){ raiseIndexError2(h,(*eeprom).dataPins.data.len-1); goto BeforeRet_;
}
							T12_ = (NIM_BOOL)0;
							T12_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables((*eeprom).dataPins.data.p->data[h].Field0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!T12_) goto LA13_;
							if ((NU)(h) >= (NU)(*eeprom).dataPins.data.len){ raiseIndexError2(h,(*eeprom).dataPins.data.len-1); goto BeforeRet_;
}
							key = (*eeprom).dataPins.data.p->data[h].Field1;
							if ((NU)(h) >= (NU)(*eeprom).dataPins.data.len){ raiseIndexError2(h,(*eeprom).dataPins.data.len-1); goto BeforeRet_;
}
							value = (*eeprom).dataPins.data.p->data[h].Field2;
							T15_ = (NU32)0;
							T15_ = X5BX5D___izypgEXDrOPhvdwKMbE2zw((*eeprom).dataPins, key);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							gpio_init(T15_);
							T16_ = (NU32)0;
							T16_ = X5BX5D___izypgEXDrOPhvdwKMbE2zw((*eeprom).dataPins, key);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							gpio_set_dir(T16_, NIM_FALSE);
							{
								NU32 T19_;
								NU32 T20_;
								NI TM__c0pjnlBjpnggBqxewNeRCw_123;
								T19_ = (NU32)0;
								T19_ = X5BX5D___izypgEXDrOPhvdwKMbE2zw((*eeprom).dataPins, key);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								T20_ = (NU32)0;
								T20_ = gpio_get(T19_);
								if (!(T20_ == ((NU32) 1))) goto LA21_;
								if (nimSubInt(((NI) (key)), ((NI) 16), &TM__c0pjnlBjpnggBqxewNeRCw_123)) { raiseOverflow(); goto BeforeRet_;
};
								if (((NI)(TM__c0pjnlBjpnggBqxewNeRCw_123)) < ((NI) 0) || ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_123)) > ((NI) 7)){ raiseRangeErrorI((NI)(TM__c0pjnlBjpnggBqxewNeRCw_123), ((NI) 0), ((NI) 7)); goto BeforeRet_;
}
								setBit__XwPFzY0nKw9aMJz1uiqKS8gbitops((&data), ((NI) ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_123))));
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							}
							goto LA17_;
							LA21_: ;
							{
								NI TM__c0pjnlBjpnggBqxewNeRCw_124;
								if (nimSubInt(((NI) (key)), ((NI) 16), &TM__c0pjnlBjpnggBqxewNeRCw_124)) { raiseOverflow(); goto BeforeRet_;
};
								if (((NI)(TM__c0pjnlBjpnggBqxewNeRCw_124)) < ((NI) 0) || ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_124)) > ((NI) 7)){ raiseRangeErrorI((NI)(TM__c0pjnlBjpnggBqxewNeRCw_124), ((NI) 0), ((NI) 7)); goto BeforeRet_;
}
								clearBit__XwPFzY0nKw9aMJz1uiqKS8g_2bitops((&data), ((NI) ((NI)(TM__c0pjnlBjpnggBqxewNeRCw_124))));
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							}
							LA17_: ;
							{
								NI T26_;
								T26_ = (NI)0;
								T26_ = len__CFEeD1cbzlG3EqLWcLD4eg((*eeprom).dataPins);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								if (!!((T26_ == L))) goto LA27_;
								failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__c0pjnlBjpnggBqxewNeRCw_125);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							}
							LA27_: ;
						}
						LA13_: ;
						if (nimAddInt(res, ((NI) 1), &TM__c0pjnlBjpnggBqxewNeRCw_126)) { raiseOverflow(); goto BeforeRet_;
};
						res = (NI)(TM__c0pjnlBjpnggBqxewNeRCw_126);
					} LA9: ;
				}
			}
		}
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T30_;
		T30_ = (NIM_BOOL)0;
		T30_ = ((*eeprom).dataSetup == ((tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg) 2));
		if (T30_) goto LA31_;
		T30_ = ((*eeprom).dataSetup == ((tyEnum_SetupKind__tEjjCRsB1QA9bnZP9cmDD3Bg) 1));
		LA31_: ;
		if (!T30_) goto LA32_;
		echoBinSafe(TM__c0pjnlBjpnggBqxewNeRCw_127, 1);
		exit(((NI) 1));
	}
	goto LA1_;
	LA32_: ;
	LA1_: ;
	setInputs__ZEyXVzX0Jjh4Lm2m3u0kqg(eeprom, address, NIM_FALSE, NIM_FALSE, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	sleep_ms(((NU32) 10));
	result = data;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {
	NCSTRING result;
	result = (NCSTRING)0;
	{
		if (!(s.len == ((NI) 0))) goto LA3_;
		result = "";
	}
	goto LA1_;
	LA3_: ;
	{
		result = ((NCSTRING) ((*s.p).data));
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___xeif2zsreB9c0lcrdaotS8w)(tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ** dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest));
		if (!T3_) goto LA4_;
		eqdestroy___Xwzl9cs7b3c4aRHlsZ0Mh7A((*dest));
		nimRawDispose((*dest), ((NI) 4));
	}
	LA4_: ;
}
static N_INLINE(void, initStackBottomWith)(void* locals) {
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	systemDatInit000();
	systemInit000();
	(*inner)();
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	NU32 colontmpD_;
	NU32 colontmpD__2;
	NU32 colontmpD__3;
	NI colontmpD__4;
	NimStringV2 colontmpD__5;
	tyObject_Table__CEbiADMtqwDYLcvZbib9b2w T2_;
	tyObject_Table__b4vpoerBR7V29ajKx2FDs6A T3_;
	tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ* T4_;
	NU8 T5_;
NIM_BOOL* nimErr_;
nimErr_ = nimErrorFlag();
	colontmpD_ = (NU32)0;
	colontmpD__2 = (NU32)0;
	colontmpD__3 = (NU32)0;
	colontmpD__4 = (NI)0;
	colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
	stdio_init_all();
	nimZeroMem((void*)(&T2_), sizeof(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w));
	T2_ = toTable__tw3SS9cdRQLkHcWNF8ibn2A(TM__c0pjnlBjpnggBqxewNeRCw_2, 9);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	pinMap__nWL09cjZkGUAfFHC82bWQFQ = T2_;
	nimZeroMem((void*)(&T3_), sizeof(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A));
	T3_ = toTable__uJbp00KSwsgQ9at44qzyaCA(TM__c0pjnlBjpnggBqxewNeRCw_3, 12);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	shiftMap__a9bcn9a5YPM0d83f5REsZbCQ = T3_;
	T4_ = (tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ*)0;
	T4_ = (tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ*) nimNewObjUninit(sizeof(tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ), NIM_ALIGNOF(tyObject_ShiftPinscolonObjectType___5Xod6o0x8StSwfuqHA9avmQ));
	colontmpD_ = dataPin__xexpqFNhJGeyhnIHp9cvbdA;
	(*T4_).data = colontmpD_;
	colontmpD__2 = clockPin__13DRswXbXcQah9a4nPb7sGQ;
	(*T4_).clock = colontmpD__2;
	colontmpD__3 = latchPin__xPI6gUZhj2ywmtuH4hkT5g;
	(*T4_).latch = colontmpD__3;
	colontmpD__4 = bytes__6EmxNhWJVTcGMZl7IPMdCQ;
	(*T4_).shifterBytes = colontmpD__4;
	shiftPins__tYc1Rmup5CeRa2UC4ttoIQ = T4_;
	newEEPROM__2N4SUM09aRJ3MerCg9aPMpWw(pinMap__nWL09cjZkGUAfFHC82bWQFQ, shiftMap__a9bcn9a5YPM0d83f5REsZbCQ, shiftPins__tYc1Rmup5CeRa2UC4ttoIQ, (&x__YqNzq7zoy9cL9bW410IV0pMQ));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	print__UUnZ3sMEKzCq1Hl3GQIHXgpicostdlib("\012");
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	sleep_ms(((NU32) 5000));
	print__UUnZ3sMEKzCq1Hl3GQIHXgpicostdlib("\012");
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	sleep_ms(((NU32) 1000));
	print__UUnZ3sMEKzCq1Hl3GQIHXgpicostdlib("\012");
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	writeEEPROM__AFzodz8r7BixDUv79cqnCsg((&x__YqNzq7zoy9cL9bW410IV0pMQ), address__OmUAEETUpMtFg7DoTNZGXg, data__Eib8oILtRl5e32yWiS4JQw);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T5_ = (NU8)0;
	T5_ = readEEPROM__fg3FnZOkcs9cAYqFI1VAy2A((&x__YqNzq7zoy9cL9bW410IV0pMQ), address__OmUAEETUpMtFg7DoTNZGXg);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD__5 = dollar___M2d4UEGH9cZOvte6rEhvUTQ(((NU64) (T5_)));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	print__UUnZ3sMEKzCq1Hl3GQIHXgpicostdlib(nimToCStringConv(colontmpD__5));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__5));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___nKP2x9cUu59a2GFPeZhMgNkw((&x__YqNzq7zoy9cL9bW410IV0pMQ));
	eqdestroy___xeif2zsreB9c0lcrdaotS8w(&shiftPins__tYc1Rmup5CeRa2UC4ttoIQ);
	eqdestroy___XCKmUiS3Ov3AJGom9cXECmg((&shiftMap__a9bcn9a5YPM0d83f5REsZbCQ));
	eqdestroy___1eV9bfPFgzYvCGm9bXLSWubw((&pinMap__nWL09cjZkGUAfFHC82bWQFQ));
	BeforeRet_: ;
	nimTestErrorFlag();
}
}

