/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
#define nimfr_(x, y)
#define nimln_(x, y)

/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyObject_Table__CEbiADMtqwDYLcvZbib9b2w tyObject_Table__CEbiADMtqwDYLcvZbib9b2w;
typedef struct tySequence__S0afUuLVxWHsXKUhx366GA tySequence__S0afUuLVxWHsXKUhx366GA;
typedef struct tySequence__S0afUuLVxWHsXKUhx366GA_Content tySequence__S0afUuLVxWHsXKUhx366GA_Content;
typedef struct tyTuple__sUhane4oetnlndJSo6uV6w tyTuple__sUhane4oetnlndJSo6uV6w;
typedef struct tyTuple__ZRdLQPN7dYollpb9cddS68Q tyTuple__ZRdLQPN7dYollpb9cddS68Q;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Table__b4vpoerBR7V29ajKx2FDs6A tyObject_Table__b4vpoerBR7V29ajKx2FDs6A;
typedef struct tySequence__XMerIiAQb66xYd9a9cuy80SQ tySequence__XMerIiAQb66xYd9a9cuy80SQ;
typedef struct tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content;
typedef struct tyTuple__YlP5Jit39bfEvee3AJ2q9aGg tyTuple__YlP5Jit39bfEvee3AJ2q9aGg;
typedef struct tyTuple__dxJdLbw7JUOttiF9cPJ6IjA tyTuple__dxJdLbw7JUOttiF9cPJ6IjA;
typedef struct tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;

/* section: NIM_merge_TYPES */
struct tySequence__S0afUuLVxWHsXKUhx366GA {
  NI len; tySequence__S0afUuLVxWHsXKUhx366GA_Content* p;
};
struct tyObject_Table__CEbiADMtqwDYLcvZbib9b2w {
tySequence__S0afUuLVxWHsXKUhx366GA data;
NI counter;
};
typedef NU8 tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w;
struct tyTuple__ZRdLQPN7dYollpb9cddS68Q {
NI Field0;
tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w Field1;
NU32 Field2;
};
struct tyTuple__sUhane4oetnlndJSo6uV6w {
tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w Field0;
NU32 Field1;
};
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
struct tySequence__XMerIiAQb66xYd9a9cuy80SQ {
  NI len; tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content* p;
};
struct tyObject_Table__b4vpoerBR7V29ajKx2FDs6A {
tySequence__XMerIiAQb66xYd9a9cuy80SQ data;
NI counter;
};
struct tyTuple__dxJdLbw7JUOttiF9cPJ6IjA {
NI Field0;
tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w Field1;
NI Field2;
};
struct tyTuple__YlP5Jit39bfEvee3AJ2q9aGg {
tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w Field0;
NI Field1;
};
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
void* typeInfoV1;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag {
  tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw Sup;
};


#ifndef tySequence__S0afUuLVxWHsXKUhx366GA_Content_PP
#define tySequence__S0afUuLVxWHsXKUhx366GA_Content_PP
struct tySequence__S0afUuLVxWHsXKUhx366GA_Content { NI cap; tyTuple__ZRdLQPN7dYollpb9cddS68Q data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__S0afUuLVxWHsXKUhx366GA_Content_PP
#define tySequence__S0afUuLVxWHsXKUhx366GA_Content_PP
struct tySequence__S0afUuLVxWHsXKUhx366GA_Content { NI cap; tyTuple__ZRdLQPN7dYollpb9cddS68Q data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content_PP
#define tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content_PP
struct tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content { NI cap; tyTuple__dxJdLbw7JUOttiF9cPJ6IjA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content_PP
#define tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content_PP
struct tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content { NI cap; tyTuple__dxJdLbw7JUOttiF9cPJ6IjA data[SEQ_DECL_SIZE];};
#endif

      struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w, initTable__RhcVITKUmXOoY2SDMzP8Bw)(NI initialSize);
static N_INLINE(NI, slotsNeeded__FcRgKUN9amY9amPIUGFlJjUgtables)(NI count);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__v2qC0V55wqa9bmqc7eHTz8A)(NI x);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res);
static N_INLINE(NF, toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem)(NI i);
static N_INLINE(NF, abs__BRaAqinz6OWTHkALb4oj6Qsystem)(NF x);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize, NI elemAlign);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___1QwebcIfDGRrW3t9bdowWXw)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w* t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NU32 val);
static N_INLINE(NI, rawGet__pY6329cH3wTIej7zDOgE3yQtables)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NI* hc);
static N_INLINE(NI, hash__vJQB9bmX39a11rxW9aidkQeHAhashes)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w x);
static N_INLINE(NI, hashWangYi1__AN9c8V1UY1ZE7b8ldNRftRQhashes)(NU64 x);
static N_INLINE(NU64, hiXorLo__wWqo9alrSZddOyokrApfNaQhashes)(NU64 a, NU64 b);
static N_INLINE(NU64, hiXorLoFallback64__wWqo9alrSZddOyokrApfNaQ_2hashes)(NU64 a, NU64 b);
static N_INLINE(NIM_BOOL, isFilled__5Qpmu5QqwDY0esVXn6wf7wtables)(NI hcode);
static N_INLINE(NI, nextTry__rkF6R1GhqjFh3qSAPaT2Cwtables)(NI h, NI maxHash);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res);
static N_INLINE(NIM_BOOL, mustRehash__6m9c9aGZCHlzvoeJejdnnlaAtables)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w t);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A)(NimStringV2 msg);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__VrFCrpvPVOUUlueujCvaJQ)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__OfpP58edMt0ohK9cVOloPWA)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w* t, tySequence__S0afUuLVxWHsXKUhx366GA* data, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NU32 val, NI hc, NI h);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___O8Va9cr5zuMR80E1G5hQtag)(tySequence__S0afUuLVxWHsXKUhx366GA* dest);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p, NI align);
static N_INLINE(NI, rawGetKnownHC__yLIR5XDrIRat41h9alZrgnAtables)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NI hc);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A, initTable__XsZ73Q3Zb8V8xRoIjyQTIg)(NI initialSize);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___kQhVO9cJlowpXAxnPDtUfqQ)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A* t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NI val);
static N_INLINE(NI, rawGet__ja1IrNE5a39arNB35Q5H8ngtables)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NI* hc);
static N_INLINE(NIM_BOOL, mustRehash__56Xgyo0V5kt1PzE9bOPSlxgtables)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__WOeTGOAKT7X5lAUM5POpaw)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__tTZreT7XhmgKhb0pjcgcmg)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A* t, tySequence__XMerIiAQb66xYd9a9cuy80SQ* data, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NI val, NI hc, NI h);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___9bWzf0v8OmYlwSMXdUYENEg)(tySequence__XMerIiAQb66xYd9a9cuy80SQ* dest);
static N_INLINE(NI, rawGetKnownHC__lmmOzZMGWYfQ5PbBuDGqCgtables)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NI hc);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__hI3U2smIPAy9aJLZUctJ7sQ_2)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__JHpRzcF21xoNQYgBrsWWkg_2)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___qYzpYseuMj9cCKH1yCYQR2Q)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w e);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___1Zp2RxHLXcmaoTqnxTPf9cw)(tySequence__XMerIiAQb66xYd9a9cuy80SQ* dest, tySequence__XMerIiAQb66xYd9a9cuy80SQ src);
N_LIB_PRIVATE N_NIMCALL(void, setLen__y5G129bGEFh1qNKyeVIxRtg)(tySequence__XMerIiAQb66xYd9a9cuy80SQ* s, NI newlen);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[47+1];
} TM__4SoG2KRQy3oMm9aUzSLtGrA_7 = { 47 | NIM_STRLIT_FLAG, "hashcommon.nim(34, 9) `\012t.counter < t.dataLen` " };
static const NimStringV2 TM__4SoG2KRQy3oMm9aUzSLtGrA_8 = {47, (NimStrPayload*)&TM__4SoG2KRQy3oMm9aUzSLtGrA_7};
static const NimStringV2 TM__4SoG2KRQy3oMm9aUzSLtGrA_19 = {47, (NimStrPayload*)&TM__4SoG2KRQy3oMm9aUzSLtGrA_7};
extern TNimTypeV2 NTIv2__t7nhKLvXTQS9cS8ByJU9bIag_;
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__4SoG2KRQy3oMm9aUzSLtGrA_31 = { 15 | NIM_STRLIT_FLAG, "key not found: " };
static const NimStringV2 TM__4SoG2KRQy3oMm9aUzSLtGrA_32 = {15, (NimStrPayload*)&TM__4SoG2KRQy3oMm9aUzSLtGrA_31};
static const NimStringV2 TM__4SoG2KRQy3oMm9aUzSLtGrA_35 = {15, (NimStrPayload*)&TM__4SoG2KRQy3oMm9aUzSLtGrA_31};

/* section: NIM_merge_VARS */
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NF, toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem)(NI i) {
	NF result;
	result = (NF)0;
	result = ((NF) (i));
	return result;
}
static N_INLINE(NF, abs__BRaAqinz6OWTHkALb4oj6Qsystem)(NF x) {
	NF result;
	NF colontmpD_;
	NF colontmpD__2;
	result = (NF)0;
	colontmpD_ = (NF)0;
	colontmpD__2 = (NF)0;
	{
		if (!(x < 0.0)) goto LA3_;
		colontmpD_ = -(x);
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		colontmpD__2 = x;
		result = colontmpD__2;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	NI r;
	NF floatProd;
	NF T1_;
	NF T2_;
	NF resAsFloat;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU32)(((NU) (a))) * (NU32)(((NU) (b))))));
	T1_ = (NF)0;
	T1_ = toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem(a);
	T2_ = (NF)0;
	T2_ = toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem(b);
	floatProd = ((NF)(T1_) * (NF)(T2_));
	resAsFloat = toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem(r);
	{
		if (!(resAsFloat == floatProd)) goto LA5_;
		(*res) = r;
	}
	goto LA3_;
	LA5_: ;
	{
		{
			NF T10_;
			NF T11_;
			T10_ = (NF)0;
			T10_ = abs__BRaAqinz6OWTHkALb4oj6Qsystem(((NF)(resAsFloat) - (NF)(floatProd)));
			T11_ = (NF)0;
			T11_ = abs__BRaAqinz6OWTHkALb4oj6Qsystem(floatProd);
			if (!(((NF)(3.2000000000000000e+01) * (NF)(T10_)) <= T11_)) goto LA12_;
			(*res) = r;
		}
		goto LA8_;
		LA12_: ;
		{
			result = NIM_TRUE;
		}
		LA8_: ;
	}
	LA3_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a == ((NI) (-2147483647 -1)));
		if (!(T3_)) goto LA4_;
		T3_ = (b == ((NI) -1));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA5_: ;
	{
		(*res) = (NI)(a / b);
	}
	LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU32)(((NU) (a))) + (NU32)(((NU) (b))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(r ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(r ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		(*res) = r;
	}
	goto LA1_;
	LA5_: ;
	{
		result = NIM_TRUE;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, slotsNeeded__FcRgKUN9amY9amPIUGFlJjUgtables)(NI count) {
	NI result;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_2;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_3;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_4;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	if (nimMulInt(((NI) (count)), ((NI) 3), &TM__4SoG2KRQy3oMm9aUzSLtGrA_2)) { raiseOverflow(); goto BeforeRet_;
};
	if (((NI) 2) == 0){ raiseDivByZero(); goto BeforeRet_;
}
	if (nimDivInt((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_2), ((NI) 2), &TM__4SoG2KRQy3oMm9aUzSLtGrA_3)) { raiseOverflow(); goto BeforeRet_;
};
	if (nimAddInt((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_3), ((NI) 4), &TM__4SoG2KRQy3oMm9aUzSLtGrA_4)) { raiseOverflow(); goto BeforeRet_;
};
	result = nextPowerOfTwo__v2qC0V55wqa9bmqc7eHTz8A((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_4));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w, initTable__RhcVITKUmXOoY2SDMzP8Bw)(NI initialSize) {
	tyObject_Table__CEbiADMtqwDYLcvZbib9b2w result;
	NI correctSizeX60gensym0_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w));
	if ((initialSize) < ((NI) 0) || (initialSize) > ((NI) 2147483647)){ raiseRangeErrorI(initialSize, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	correctSizeX60gensym0_ = slotsNeeded__FcRgKUN9amY9amPIUGFlJjUgtables(((NI) (initialSize)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.counter = ((NI) 0);
	if ((correctSizeX60gensym0_) < ((NI) 0) || (correctSizeX60gensym0_) > ((NI) 2147483647)){ raiseRangeErrorI(correctSizeX60gensym0_, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	result.data.len = ((NI) (correctSizeX60gensym0_)); result.data.p = (tySequence__S0afUuLVxWHsXKUhx366GA_Content*) newSeqPayload(((NI) (correctSizeX60gensym0_)), sizeof(tyTuple__ZRdLQPN7dYollpb9cddS68Q), NIM_ALIGNOF(tyTuple__ZRdLQPN7dYollpb9cddS68Q));
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU64, hiXorLoFallback64__wWqo9alrSZddOyokrApfNaQ_2hashes)(NU64 a, NU64 b) {
	NU64 result;
	NU64 colontmpD_;
	NU64 colontmpD__2;
	NU64 colontmpD__3;
	NU64 colontmpD__4;
	NU64 aH;
	NU64 aL;
	NU64 bH;
	NU64 bL;
	NU64 rHH;
	NU64 rHL;
	NU64 rLH;
	NU64 rLL;
	NU64 t;
	NU64 c;
	NU64 lo;
	NU64 T6_;
	NU64 hi;
{	result = (NU64)0;
	colontmpD_ = (NU64)0;
	colontmpD__2 = (NU64)0;
	colontmpD__3 = (NU64)0;
	colontmpD__4 = (NU64)0;
	aH = (NU64)((NU64)(a) >> (NU64)(((NI) 32)));
	aL = (NU64)(a & 4294967295ULL);
	bH = (NU64)((NU64)(b) >> (NU64)(((NI) 32)));
	bL = (NU64)(b & 4294967295ULL);
	rHH = (NU64)((NU64)(aH) * (NU64)(bH));
	rHL = (NU64)((NU64)(aH) * (NU64)(bL));
	rLH = (NU64)((NU64)(aL) * (NU64)(bH));
	rLL = (NU64)((NU64)(aL) * (NU64)(bL));
	t = (NU64)((NU64)(rLL) + (NU64)((NU64)((NU64)(rHL) << (NU64)(((NI) 32)))));
	{
		if (!((NU64)(t) < (NU64)(rLL))) goto LA3_;
		colontmpD_ = 1ULL;
		c = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		colontmpD__2 = 0ULL;
		c = colontmpD__2;
	}
	LA1_: ;
	lo = (NU64)((NU64)(t) + (NU64)((NU64)((NU64)(rLH) << (NU64)(((NI) 32)))));
	T6_ = (NU64)0;
	{
		if (!((NU64)(lo) < (NU64)(t))) goto LA9_;
		colontmpD__3 = 1ULL;
		T6_ = colontmpD__3;
	}
	goto LA7_;
	LA9_: ;
	{
		colontmpD__4 = 0ULL;
		T6_ = colontmpD__4;
	}
	LA7_: ;
	c += T6_;
	hi = (NU64)((NU64)((NU64)((NU64)((NU64)((NU64)(rHH) + (NU64)((NU64)((NU64)(rHL) >> (NU64)(((NI) 32)))))) + (NU64)((NU64)((NU64)(rLH) >> (NU64)(((NI) 32)))))) + (NU64)(c));
	result = (NU64)(hi ^ lo);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU64, hiXorLo__wWqo9alrSZddOyokrApfNaQhashes)(NU64 a, NU64 b) {
	NU64 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU64)0;
	result = hiXorLoFallback64__wWqo9alrSZddOyokrApfNaQ_2hashes(a, b);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, hashWangYi1__AN9c8V1UY1ZE7b8ldNRftRQhashes)(NU64 x) {
	NI result;
	NU64 T1_;
	NU64 T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	T1_ = (NU64)0;
	T1_ = hiXorLo__wWqo9alrSZddOyokrApfNaQhashes(11562461410679940143ULL, (NU64)(x ^ 16646288086500911323ULL));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (NU64)0;
	T2_ = hiXorLo__wWqo9alrSZddOyokrApfNaQhashes(T1_, 16952864883938283885ULL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NI) (T2_));
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, hash__vJQB9bmX39a11rxW9aidkQeHAhashes)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w x) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	result = hashWangYi1__AN9c8V1UY1ZE7b8ldNRftRQhashes(((NU64) (x)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, isFilled__5Qpmu5QqwDY0esVXn6wf7wtables)(NI hcode) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = !((hcode == ((NI) 0)));
	return result;
}
static N_INLINE(NI, nextTry__rkF6R1GhqjFh3qSAPaT2Cwtables)(NI h, NI maxHash) {
	NI result;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_5;
{	result = (NI)0;
	if (nimAddInt(h, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_5)) { raiseOverflow(); goto BeforeRet_;
};
	result = (NI)((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_5) & maxHash);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU32)(((NU) (a))) - (NU32)(((NU) (b))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(r ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(r ^ (NI)((NU32) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		(*res) = r;
	}
	goto LA1_;
	LA5_: ;
	{
		result = NIM_TRUE;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, rawGet__pY6329cH3wTIej7zDOgE3yQtables)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NI* hc) {
	NI result;
	NI T1_;
	NI h;
	NI T11_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_6;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	T1_ = (NI)0;
	T1_ = hash__vJQB9bmX39a11rxW9aidkQeHAhashes(key);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc) = T1_;
	{
		if (!((*hc) == ((NI) 0))) goto LA4_;
		(*hc) = ((NI) 314159265);
	}
	LA4_: ;
	{
		NI T8_;
		T8_ = t.data.len;
		if (!(T8_ == ((NI) 0))) goto LA9_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (t.data.len-1);
	h = (NI)((*hc) & T11_);
	{
		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;
}
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables(t.data.p->data[h].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;
}
				T17_ = (t.data.p->data[h].Field0 == (*hc));
				if (!(T17_)) goto LA18_;
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;
}
				T17_ = (t.data.p->data[h].Field1 == key);
				LA18_: ;
				if (!T17_) goto LA19_;
				result = h;
				goto BeforeRet_;
			}
			LA19_: ;
			T21_ = (t.data.len-1);
			h = nextTry__rkF6R1GhqjFh3qSAPaT2Cwtables(h, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	if (nimSubInt(((NI) -1), h, &TM__4SoG2KRQy3oMm9aUzSLtGrA_6)) { raiseOverflow(); goto BeforeRet_;
};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_6);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__6m9c9aGZCHlzvoeJejdnnlaAtables)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w t) {
	NIM_BOOL result;
	NIM_BOOL T6_;
	NI T7_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_9;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_10;
	NI T9_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_11;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	{
		NI T3_;
		T3_ = t.data.len;
		if (!!((t.counter < T3_))) goto LA4_;
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__4SoG2KRQy3oMm9aUzSLtGrA_8);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA4_: ;
	T6_ = (NIM_BOOL)0;
	T7_ = t.data.len;
	if (nimMulInt(T7_, ((NI) 2), &TM__4SoG2KRQy3oMm9aUzSLtGrA_9)) { raiseOverflow(); goto BeforeRet_;
};
	if (nimMulInt(t.counter, ((NI) 3), &TM__4SoG2KRQy3oMm9aUzSLtGrA_10)) { raiseOverflow(); goto BeforeRet_;
};
	T6_ = ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_9) < (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_10));
	if (T6_) goto LA8_;
	T9_ = t.data.len;
	if (nimSubInt(T9_, t.counter, &TM__4SoG2KRQy3oMm9aUzSLtGrA_11)) { raiseOverflow(); goto BeforeRet_;
};
	T6_ = ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_11) < ((NI) 4));
	LA8_: ;
	result = T6_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__OfpP58edMt0ohK9cVOloPWA)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w* t, tySequence__S0afUuLVxWHsXKUhx366GA* data, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NU32 val, NI hc, NI h) {
{	if ((NU)(h) >= (NU)(*data).len){ raiseIndexError2(h,(*data).len-1); goto BeforeRet_;
}
	(*data).p->data[h].Field1 = key;
	if ((NU)(h) >= (NU)(*data).len){ raiseIndexError2(h,(*data).len-1); goto BeforeRet_;
}
	(*data).p->data[h].Field2 = val;
	if ((NU)(h) >= (NU)(*data).len){ raiseIndexError2(h,(*data).len-1); goto BeforeRet_;
}
	(*data).p->data[h].Field0 = hc;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___O8Va9cr5zuMR80E1G5hQtag)(tySequence__S0afUuLVxWHsXKUhx366GA* dest) {
	NI colontmp_;
	colontmp_ = ((NI) 0);
	{
		while (1) {
			NI T3_;
			T3_ = (*dest).len;
			if (!(colontmp_ < T3_)) goto LA2;
			colontmp_ += ((NI) 1);
		} LA2: ;
	}
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc((*dest).p, NIM_ALIGNOF(tyTuple__ZRdLQPN7dYollpb9cddS68Q));
}
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__VrFCrpvPVOUUlueujCvaJQ)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w* t) {
	tySequence__S0afUuLVxWHsXKUhx366GA n;
	NI T1_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_12;
	tySequence__S0afUuLVxWHsXKUhx366GA T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	n.len = 0; n.p = NIM_NIL;
	T1_ = (*t).data.len;
	if (nimMulInt(T1_, ((NI) 2), &TM__4SoG2KRQy3oMm9aUzSLtGrA_12)) { raiseOverflow(); goto BeforeRet_;
};
	if (((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_12)) < ((NI) 0) || ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_12)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_12), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	n.len = ((NI) ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_12))); n.p = (tySequence__S0afUuLVxWHsXKUhx366GA_Content*) newSeqPayload(((NI) ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_12))), sizeof(tyTuple__ZRdLQPN7dYollpb9cddS68Q), NIM_ALIGNOF(tyTuple__ZRdLQPN7dYollpb9cddS68Q));
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = (*t).data;
	(*t).data = n;
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T4_ = (n.len-1);
		colontmp_ = T4_;
		res = ((NI) 0);
		{
			while (1) {
				NI eh;
				NI TM__4SoG2KRQy3oMm9aUzSLtGrA_13;
				if (!(res <= colontmp_)) goto LA6;
				i = res;
				if ((NU)(i) >= (NU)n.len){ raiseIndexError2(i,n.len-1); goto BeforeRet_;
}
				eh = n.p->data[i].Field0;
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					tyObject_Table__CEbiADMtqwDYLcvZbib9b2w* T17_;
					tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w T18_;
					tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w T19_;
					NU32 T20_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables(eh);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T9_) goto LA10_;
					T12_ = ((*t).data.len-1);
					j = (NI)(eh & T12_);
					{
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							if ((NU)(j) >= (NU)(*t).data.len){ raiseIndexError2(j,(*t).data.len-1); goto BeforeRet_;
}
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables((*t).data.p->data[j].Field0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!T15_) goto LA14;
							T16_ = ((*t).data.len-1);
							j = nextTry__rkF6R1GhqjFh3qSAPaT2Cwtables(j, T16_);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						} LA14: ;
					}
					T17_ = (tyObject_Table__CEbiADMtqwDYLcvZbib9b2w*)0;
					T17_ = t;
					if ((NU)(i) >= (NU)n.len){ raiseIndexError2(i,n.len-1); goto BeforeRet_;
}
					T18_ = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
					T18_ = n.p->data[i].Field1;
					n.p->data[i].Field1 = 0;
					T19_ = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
					T19_ = T18_;
					if ((NU)(i) >= (NU)n.len){ raiseIndexError2(i,n.len-1); goto BeforeRet_;
}
					T20_ = (NU32)0;
					T20_ = n.p->data[i].Field2;
					n.p->data[i].Field2 = 0;
					rawInsert__OfpP58edMt0ohK9cVOloPWA(T17_, (&(*t).data), T19_, T20_, eh, j);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				LA10_: ;
				if (nimAddInt(res, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_13)) { raiseOverflow(); goto BeforeRet_;
};
				res = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_13);
			} LA6: ;
		}
	}
	eqdestroy___O8Va9cr5zuMR80E1G5hQtag((&n));
	}BeforeRet_: ;
}
static N_INLINE(NI, rawGetKnownHC__yLIR5XDrIRat41h9alZrgnAtables)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NI hc) {
	NI result;
	NI h;
	NI T6_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_14;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		NI T3_;
		T3_ = t.data.len;
		if (!(T3_ == ((NI) 0))) goto LA4_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA4_: ;
	T6_ = (t.data.len-1);
	h = (NI)(hc & T6_);
	{
		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;
}
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables(t.data.p->data[h].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T9_) goto LA8;
			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;
}
				T12_ = (t.data.p->data[h].Field0 == hc);
				if (!(T12_)) goto LA13_;
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;
}
				T12_ = (t.data.p->data[h].Field1 == key);
				LA13_: ;
				if (!T12_) goto LA14_;
				result = h;
				goto BeforeRet_;
			}
			LA14_: ;
			T16_ = (t.data.len-1);
			h = nextTry__rkF6R1GhqjFh3qSAPaT2Cwtables(h, T16_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA8: ;
	}
	if (nimSubInt(((NI) -1), h, &TM__4SoG2KRQy3oMm9aUzSLtGrA_14)) { raiseOverflow(); goto BeforeRet_;
};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_14);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___1QwebcIfDGRrW3t9bdowWXw)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w* t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NU32 val) {
	NI hc;
	NI index;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI T3_;
		NI correctSizeX60gensym69_;
		T3_ = (*t).data.len;
		if (!(T3_ == ((NI) 0))) goto LA4_;
		correctSizeX60gensym69_ = slotsNeeded__FcRgKUN9amY9amPIUGFlJjUgtables(((NI) 32));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*t).counter = ((NI) 0);
		if ((correctSizeX60gensym69_) < ((NI) 0) || (correctSizeX60gensym69_) > ((NI) 2147483647)){ raiseRangeErrorI(correctSizeX60gensym69_, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		(*t).data.len = ((NI) (correctSizeX60gensym69_)); (*t).data.p = (tySequence__S0afUuLVxWHsXKUhx366GA_Content*) newSeqPayload(((NI) (correctSizeX60gensym69_)), sizeof(tyTuple__ZRdLQPN7dYollpb9cddS68Q), NIM_ALIGNOF(tyTuple__ZRdLQPN7dYollpb9cddS68Q));
	}
	LA4_: ;
	hc = (NI)0;
	index = rawGet__pY6329cH3wTIej7zDOgE3yQtables((*t), key, (&hc));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(((NI) 0) <= index)) goto LA8_;
		if ((NU)(index) >= (NU)(*t).data.len){ raiseIndexError2(index,(*t).data.len-1); goto BeforeRet_;
}
		(*t).data.p->data[index].Field2 = val;
	}
	goto LA6_;
	LA8_: ;
	{
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_15;
		tyObject_Table__CEbiADMtqwDYLcvZbib9b2w* T21_;
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_16;
		{
			NI T13_;
			NI correctSizeX60gensym72_;
			T13_ = (*t).data.len;
			if (!(T13_ == ((NI) 0))) goto LA14_;
			correctSizeX60gensym72_ = slotsNeeded__FcRgKUN9amY9amPIUGFlJjUgtables(((NI) 32));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			(*t).counter = ((NI) 0);
			if ((correctSizeX60gensym72_) < ((NI) 0) || (correctSizeX60gensym72_) > ((NI) 2147483647)){ raiseRangeErrorI(correctSizeX60gensym72_, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			(*t).data.len = ((NI) (correctSizeX60gensym72_)); (*t).data.p = (tySequence__S0afUuLVxWHsXKUhx366GA_Content*) newSeqPayload(((NI) (correctSizeX60gensym72_)), sizeof(tyTuple__ZRdLQPN7dYollpb9cddS68Q), NIM_ALIGNOF(tyTuple__ZRdLQPN7dYollpb9cddS68Q));
		}
		LA14_: ;
		{
			NIM_BOOL T18_;
			T18_ = (NIM_BOOL)0;
			T18_ = mustRehash__6m9c9aGZCHlzvoeJejdnnlaAtables((*t));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T18_) goto LA19_;
			enlarge__VrFCrpvPVOUUlueujCvaJQ(t);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			index = rawGetKnownHC__yLIR5XDrIRat41h9alZrgnAtables((*t), key, hc);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		LA19_: ;
		if (nimSubInt(((NI) -1), index, &TM__4SoG2KRQy3oMm9aUzSLtGrA_15)) { raiseOverflow(); goto BeforeRet_;
};
		index = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_15);
		T21_ = (tyObject_Table__CEbiADMtqwDYLcvZbib9b2w*)0;
		T21_ = t;
		rawInsert__OfpP58edMt0ohK9cVOloPWA(T21_, (&(*t).data), key, val, hc, index);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt((*t).counter, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_16)) { raiseOverflow(); goto BeforeRet_;
};
		(*t).counter = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_16);
	}
	LA6_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w, toTable__tw3SS9cdRQLkHcWNF8ibn2A)(tyTuple__sUhane4oetnlndJSo6uV6w* pairs, NI pairsLen_0) {
	tyObject_Table__CEbiADMtqwDYLcvZbib9b2w result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w));
	result = initTable__RhcVITKUmXOoY2SDMzP8Bw(pairsLen_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* key;
		NU32* val;
		NI i;
		key = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w*)0;
		val = (NU32*)0;
		i = ((NI) 0);
		{
			while (1) {
				NU32 colontmpD_;
				NI TM__4SoG2KRQy3oMm9aUzSLtGrA_17;
				if (!(i < pairsLen_0)) goto LA3;
				colontmpD_ = (NU32)0;
				if ((NU)(i) >= (NU)(pairsLen_0)){ raiseIndexError2(i,pairsLen_0-1); goto BeforeRet_;
}
				key = (&pairs[i].Field0);
				if ((NU)(i) >= (NU)(pairsLen_0)){ raiseIndexError2(i,pairsLen_0-1); goto BeforeRet_;
}
				val = (&pairs[i].Field1);
				colontmpD_ = (*val);
				X5BX5Deq___1QwebcIfDGRrW3t9bdowWXw((&result), (*key), colontmpD_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (nimAddInt(i, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_17)) { raiseOverflow(); goto BeforeRet_;
};
				i = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_17);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A, initTable__XsZ73Q3Zb8V8xRoIjyQTIg)(NI initialSize) {
	tyObject_Table__b4vpoerBR7V29ajKx2FDs6A result;
	NI correctSizeX60gensym2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A));
	if ((initialSize) < ((NI) 0) || (initialSize) > ((NI) 2147483647)){ raiseRangeErrorI(initialSize, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	correctSizeX60gensym2_ = slotsNeeded__FcRgKUN9amY9amPIUGFlJjUgtables(((NI) (initialSize)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result.counter = ((NI) 0);
	if ((correctSizeX60gensym2_) < ((NI) 0) || (correctSizeX60gensym2_) > ((NI) 2147483647)){ raiseRangeErrorI(correctSizeX60gensym2_, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	result.data.len = ((NI) (correctSizeX60gensym2_)); result.data.p = (tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content*) newSeqPayload(((NI) (correctSizeX60gensym2_)), sizeof(tyTuple__dxJdLbw7JUOttiF9cPJ6IjA), NIM_ALIGNOF(tyTuple__dxJdLbw7JUOttiF9cPJ6IjA));
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, rawGet__ja1IrNE5a39arNB35Q5H8ngtables)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NI* hc) {
	NI result;
	NI T1_;
	NI h;
	NI T11_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_18;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	T1_ = (NI)0;
	T1_ = hash__vJQB9bmX39a11rxW9aidkQeHAhashes(key);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc) = T1_;
	{
		if (!((*hc) == ((NI) 0))) goto LA4_;
		(*hc) = ((NI) 314159265);
	}
	LA4_: ;
	{
		NI T8_;
		T8_ = t.data.len;
		if (!(T8_ == ((NI) 0))) goto LA9_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (t.data.len-1);
	h = (NI)((*hc) & T11_);
	{
		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;
}
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables(t.data.p->data[h].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;
}
				T17_ = (t.data.p->data[h].Field0 == (*hc));
				if (!(T17_)) goto LA18_;
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;
}
				T17_ = (t.data.p->data[h].Field1 == key);
				LA18_: ;
				if (!T17_) goto LA19_;
				result = h;
				goto BeforeRet_;
			}
			LA19_: ;
			T21_ = (t.data.len-1);
			h = nextTry__rkF6R1GhqjFh3qSAPaT2Cwtables(h, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	if (nimSubInt(((NI) -1), h, &TM__4SoG2KRQy3oMm9aUzSLtGrA_18)) { raiseOverflow(); goto BeforeRet_;
};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_18);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__56Xgyo0V5kt1PzE9bOPSlxgtables)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t) {
	NIM_BOOL result;
	NIM_BOOL T6_;
	NI T7_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_20;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_21;
	NI T9_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_22;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	{
		NI T3_;
		T3_ = t.data.len;
		if (!!((t.counter < T3_))) goto LA4_;
		failedAssertImpl__W9cjVocn1tjhW7p7xohJj6A(TM__4SoG2KRQy3oMm9aUzSLtGrA_19);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA4_: ;
	T6_ = (NIM_BOOL)0;
	T7_ = t.data.len;
	if (nimMulInt(T7_, ((NI) 2), &TM__4SoG2KRQy3oMm9aUzSLtGrA_20)) { raiseOverflow(); goto BeforeRet_;
};
	if (nimMulInt(t.counter, ((NI) 3), &TM__4SoG2KRQy3oMm9aUzSLtGrA_21)) { raiseOverflow(); goto BeforeRet_;
};
	T6_ = ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_20) < (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_21));
	if (T6_) goto LA8_;
	T9_ = t.data.len;
	if (nimSubInt(T9_, t.counter, &TM__4SoG2KRQy3oMm9aUzSLtGrA_22)) { raiseOverflow(); goto BeforeRet_;
};
	T6_ = ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_22) < ((NI) 4));
	LA8_: ;
	result = T6_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__tTZreT7XhmgKhb0pjcgcmg)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A* t, tySequence__XMerIiAQb66xYd9a9cuy80SQ* data, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NI val, NI hc, NI h) {
{	if ((NU)(h) >= (NU)(*data).len){ raiseIndexError2(h,(*data).len-1); goto BeforeRet_;
}
	(*data).p->data[h].Field1 = key;
	if ((NU)(h) >= (NU)(*data).len){ raiseIndexError2(h,(*data).len-1); goto BeforeRet_;
}
	(*data).p->data[h].Field2 = val;
	if ((NU)(h) >= (NU)(*data).len){ raiseIndexError2(h,(*data).len-1); goto BeforeRet_;
}
	(*data).p->data[h].Field0 = hc;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___9bWzf0v8OmYlwSMXdUYENEg)(tySequence__XMerIiAQb66xYd9a9cuy80SQ* dest) {
	NI colontmp_;
	colontmp_ = ((NI) 0);
	{
		while (1) {
			NI T3_;
			T3_ = (*dest).len;
			if (!(colontmp_ < T3_)) goto LA2;
			colontmp_ += ((NI) 1);
		} LA2: ;
	}
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc((*dest).p, NIM_ALIGNOF(tyTuple__dxJdLbw7JUOttiF9cPJ6IjA));
}
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__WOeTGOAKT7X5lAUM5POpaw)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A* t) {
	tySequence__XMerIiAQb66xYd9a9cuy80SQ n;
	NI T1_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_23;
	tySequence__XMerIiAQb66xYd9a9cuy80SQ T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	n.len = 0; n.p = NIM_NIL;
	T1_ = (*t).data.len;
	if (nimMulInt(T1_, ((NI) 2), &TM__4SoG2KRQy3oMm9aUzSLtGrA_23)) { raiseOverflow(); goto BeforeRet_;
};
	if (((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_23)) < ((NI) 0) || ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_23)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_23), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	n.len = ((NI) ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_23))); n.p = (tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content*) newSeqPayload(((NI) ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_23))), sizeof(tyTuple__dxJdLbw7JUOttiF9cPJ6IjA), NIM_ALIGNOF(tyTuple__dxJdLbw7JUOttiF9cPJ6IjA));
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = (*t).data;
	(*t).data = n;
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T4_ = (n.len-1);
		colontmp_ = T4_;
		res = ((NI) 0);
		{
			while (1) {
				NI eh;
				NI TM__4SoG2KRQy3oMm9aUzSLtGrA_24;
				if (!(res <= colontmp_)) goto LA6;
				i = res;
				if ((NU)(i) >= (NU)n.len){ raiseIndexError2(i,n.len-1); goto BeforeRet_;
}
				eh = n.p->data[i].Field0;
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					tyObject_Table__b4vpoerBR7V29ajKx2FDs6A* T17_;
					tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w T18_;
					tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w T19_;
					NI T20_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables(eh);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T9_) goto LA10_;
					T12_ = ((*t).data.len-1);
					j = (NI)(eh & T12_);
					{
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							if ((NU)(j) >= (NU)(*t).data.len){ raiseIndexError2(j,(*t).data.len-1); goto BeforeRet_;
}
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables((*t).data.p->data[j].Field0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!T15_) goto LA14;
							T16_ = ((*t).data.len-1);
							j = nextTry__rkF6R1GhqjFh3qSAPaT2Cwtables(j, T16_);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						} LA14: ;
					}
					T17_ = (tyObject_Table__b4vpoerBR7V29ajKx2FDs6A*)0;
					T17_ = t;
					if ((NU)(i) >= (NU)n.len){ raiseIndexError2(i,n.len-1); goto BeforeRet_;
}
					T18_ = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
					T18_ = n.p->data[i].Field1;
					n.p->data[i].Field1 = 0;
					T19_ = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
					T19_ = T18_;
					if ((NU)(i) >= (NU)n.len){ raiseIndexError2(i,n.len-1); goto BeforeRet_;
}
					T20_ = (NI)0;
					T20_ = n.p->data[i].Field2;
					n.p->data[i].Field2 = 0;
					rawInsert__tTZreT7XhmgKhb0pjcgcmg(T17_, (&(*t).data), T19_, T20_, eh, j);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				LA10_: ;
				if (nimAddInt(res, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_24)) { raiseOverflow(); goto BeforeRet_;
};
				res = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_24);
			} LA6: ;
		}
	}
	eqdestroy___9bWzf0v8OmYlwSMXdUYENEg((&n));
	}BeforeRet_: ;
}
static N_INLINE(NI, rawGetKnownHC__lmmOzZMGWYfQ5PbBuDGqCgtables)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NI hc) {
	NI result;
	NI h;
	NI T6_;
	NI TM__4SoG2KRQy3oMm9aUzSLtGrA_25;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		NI T3_;
		T3_ = t.data.len;
		if (!(T3_ == ((NI) 0))) goto LA4_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA4_: ;
	T6_ = (t.data.len-1);
	h = (NI)(hc & T6_);
	{
		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;
}
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__5Qpmu5QqwDY0esVXn6wf7wtables(t.data.p->data[h].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T9_) goto LA8;
			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;
}
				T12_ = (t.data.p->data[h].Field0 == hc);
				if (!(T12_)) goto LA13_;
				if ((NU)(h) >= (NU)t.data.len){ raiseIndexError2(h,t.data.len-1); goto BeforeRet_;
}
				T12_ = (t.data.p->data[h].Field1 == key);
				LA13_: ;
				if (!T12_) goto LA14_;
				result = h;
				goto BeforeRet_;
			}
			LA14_: ;
			T16_ = (t.data.len-1);
			h = nextTry__rkF6R1GhqjFh3qSAPaT2Cwtables(h, T16_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA8: ;
	}
	if (nimSubInt(((NI) -1), h, &TM__4SoG2KRQy3oMm9aUzSLtGrA_25)) { raiseOverflow(); goto BeforeRet_;
};
	result = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_25);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___kQhVO9cJlowpXAxnPDtUfqQ)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A* t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NI val) {
	NI hc;
	NI index;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI T3_;
		NI correctSizeX60gensym75_;
		T3_ = (*t).data.len;
		if (!(T3_ == ((NI) 0))) goto LA4_;
		correctSizeX60gensym75_ = slotsNeeded__FcRgKUN9amY9amPIUGFlJjUgtables(((NI) 32));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*t).counter = ((NI) 0);
		if ((correctSizeX60gensym75_) < ((NI) 0) || (correctSizeX60gensym75_) > ((NI) 2147483647)){ raiseRangeErrorI(correctSizeX60gensym75_, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		(*t).data.len = ((NI) (correctSizeX60gensym75_)); (*t).data.p = (tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content*) newSeqPayload(((NI) (correctSizeX60gensym75_)), sizeof(tyTuple__dxJdLbw7JUOttiF9cPJ6IjA), NIM_ALIGNOF(tyTuple__dxJdLbw7JUOttiF9cPJ6IjA));
	}
	LA4_: ;
	hc = (NI)0;
	index = rawGet__ja1IrNE5a39arNB35Q5H8ngtables((*t), key, (&hc));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(((NI) 0) <= index)) goto LA8_;
		if ((NU)(index) >= (NU)(*t).data.len){ raiseIndexError2(index,(*t).data.len-1); goto BeforeRet_;
}
		(*t).data.p->data[index].Field2 = val;
	}
	goto LA6_;
	LA8_: ;
	{
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_26;
		tyObject_Table__b4vpoerBR7V29ajKx2FDs6A* T21_;
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_27;
		{
			NI T13_;
			NI correctSizeX60gensym78_;
			T13_ = (*t).data.len;
			if (!(T13_ == ((NI) 0))) goto LA14_;
			correctSizeX60gensym78_ = slotsNeeded__FcRgKUN9amY9amPIUGFlJjUgtables(((NI) 32));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			(*t).counter = ((NI) 0);
			if ((correctSizeX60gensym78_) < ((NI) 0) || (correctSizeX60gensym78_) > ((NI) 2147483647)){ raiseRangeErrorI(correctSizeX60gensym78_, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			(*t).data.len = ((NI) (correctSizeX60gensym78_)); (*t).data.p = (tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content*) newSeqPayload(((NI) (correctSizeX60gensym78_)), sizeof(tyTuple__dxJdLbw7JUOttiF9cPJ6IjA), NIM_ALIGNOF(tyTuple__dxJdLbw7JUOttiF9cPJ6IjA));
		}
		LA14_: ;
		{
			NIM_BOOL T18_;
			T18_ = (NIM_BOOL)0;
			T18_ = mustRehash__56Xgyo0V5kt1PzE9bOPSlxgtables((*t));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T18_) goto LA19_;
			enlarge__WOeTGOAKT7X5lAUM5POpaw(t);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			index = rawGetKnownHC__lmmOzZMGWYfQ5PbBuDGqCgtables((*t), key, hc);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		LA19_: ;
		if (nimSubInt(((NI) -1), index, &TM__4SoG2KRQy3oMm9aUzSLtGrA_26)) { raiseOverflow(); goto BeforeRet_;
};
		index = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_26);
		T21_ = (tyObject_Table__b4vpoerBR7V29ajKx2FDs6A*)0;
		T21_ = t;
		rawInsert__tTZreT7XhmgKhb0pjcgcmg(T21_, (&(*t).data), key, val, hc, index);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt((*t).counter, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_27)) { raiseOverflow(); goto BeforeRet_;
};
		(*t).counter = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_27);
	}
	LA6_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A, toTable__uJbp00KSwsgQ9at44qzyaCA)(tyTuple__YlP5Jit39bfEvee3AJ2q9aGg* pairs, NI pairsLen_0) {
	tyObject_Table__b4vpoerBR7V29ajKx2FDs6A result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A));
	result = initTable__XsZ73Q3Zb8V8xRoIjyQTIg(pairsLen_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* key;
		NI* val;
		NI i;
		key = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w*)0;
		val = (NI*)0;
		i = ((NI) 0);
		{
			while (1) {
				NI colontmpD_;
				NI TM__4SoG2KRQy3oMm9aUzSLtGrA_28;
				if (!(i < pairsLen_0)) goto LA3;
				colontmpD_ = (NI)0;
				if ((NU)(i) >= (NU)(pairsLen_0)){ raiseIndexError2(i,pairsLen_0-1); goto BeforeRet_;
}
				key = (&pairs[i].Field0);
				if ((NU)(i) >= (NU)(pairsLen_0)){ raiseIndexError2(i,pairsLen_0-1); goto BeforeRet_;
}
				val = (&pairs[i].Field1);
				colontmpD_ = (*val);
				X5BX5Deq___kQhVO9cJlowpXAxnPDtUfqQ((&result), (*key), colontmpD_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (nimAddInt(i, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_28)) { raiseOverflow(); goto BeforeRet_;
};
				i = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_28);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__hI3U2smIPAy9aJLZUctJ7sQ_2)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key) {
	NIM_BOOL result;
	NI hc;
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	hc = (NI)0;
	T1_ = (NI)0;
	T1_ = rawGet__pY6329cH3wTIej7zDOgE3yQtables(t, key, (&hc));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI) 0) <= T1_);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__hI3U2smIPAy9aJLZUctJ7sQ)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	result = hasKey__hI3U2smIPAy9aJLZUctJ7sQ_2(t, key);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__JHpRzcF21xoNQYgBrsWWkg_2)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key) {
	NIM_BOOL result;
	NI hc;
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	hc = (NI)0;
	T1_ = (NI)0;
	T1_ = rawGet__ja1IrNE5a39arNB35Q5H8ngtables(t, key, (&hc));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI) 0) <= T1_);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__JHpRzcF21xoNQYgBrsWWkg)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	result = hasKey__JHpRzcF21xoNQYgBrsWWkg_2(t, key);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, len__PAYg5d1hn6UVJNVIuJVZlA)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t) {
	NI result;
	result = (NI)0;
	result = t.counter;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKeyOrPut__F8ewLFe7IWn5AKwlJOfbKw)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w* t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NU32 val) {
	NIM_BOOL result;
	NI hc;
	NI index;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	{
		NI T3_;
		NI correctSizeX60gensym28_;
		T3_ = (*t).data.len;
		if (!(T3_ == ((NI) 0))) goto LA4_;
		correctSizeX60gensym28_ = slotsNeeded__FcRgKUN9amY9amPIUGFlJjUgtables(((NI) 32));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*t).counter = ((NI) 0);
		if ((correctSizeX60gensym28_) < ((NI) 0) || (correctSizeX60gensym28_) > ((NI) 2147483647)){ raiseRangeErrorI(correctSizeX60gensym28_, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		(*t).data.len = ((NI) (correctSizeX60gensym28_)); (*t).data.p = (tySequence__S0afUuLVxWHsXKUhx366GA_Content*) newSeqPayload(((NI) (correctSizeX60gensym28_)), sizeof(tyTuple__ZRdLQPN7dYollpb9cddS68Q), NIM_ALIGNOF(tyTuple__ZRdLQPN7dYollpb9cddS68Q));
	}
	LA4_: ;
	hc = (NI)0;
	index = rawGet__pY6329cH3wTIej7zDOgE3yQtables((*t), key, (&hc));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NU32 colontmpD_;
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_29;
		tyObject_Table__CEbiADMtqwDYLcvZbib9b2w* T20_;
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_30;
		if (!(index < ((NI) 0))) goto LA8_;
		colontmpD_ = (NU32)0;
		result = NIM_FALSE;
		{
			NI T12_;
			NI correctSizeX60gensym31_;
			T12_ = (*t).data.len;
			if (!(T12_ == ((NI) 0))) goto LA13_;
			correctSizeX60gensym31_ = slotsNeeded__FcRgKUN9amY9amPIUGFlJjUgtables(((NI) 32));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			(*t).counter = ((NI) 0);
			if ((correctSizeX60gensym31_) < ((NI) 0) || (correctSizeX60gensym31_) > ((NI) 2147483647)){ raiseRangeErrorI(correctSizeX60gensym31_, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			(*t).data.len = ((NI) (correctSizeX60gensym31_)); (*t).data.p = (tySequence__S0afUuLVxWHsXKUhx366GA_Content*) newSeqPayload(((NI) (correctSizeX60gensym31_)), sizeof(tyTuple__ZRdLQPN7dYollpb9cddS68Q), NIM_ALIGNOF(tyTuple__ZRdLQPN7dYollpb9cddS68Q));
		}
		LA13_: ;
		{
			NIM_BOOL T17_;
			T17_ = (NIM_BOOL)0;
			T17_ = mustRehash__6m9c9aGZCHlzvoeJejdnnlaAtables((*t));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T17_) goto LA18_;
			enlarge__VrFCrpvPVOUUlueujCvaJQ(t);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			index = rawGetKnownHC__yLIR5XDrIRat41h9alZrgnAtables((*t), key, hc);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		LA18_: ;
		if (nimSubInt(((NI) -1), index, &TM__4SoG2KRQy3oMm9aUzSLtGrA_29)) { raiseOverflow(); goto BeforeRet_;
};
		index = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_29);
		T20_ = (tyObject_Table__CEbiADMtqwDYLcvZbib9b2w*)0;
		T20_ = t;
		colontmpD_ = val;
		rawInsert__OfpP58edMt0ohK9cVOloPWA(T20_, (&(*t).data), key, colontmpD_, hc, index);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (nimAddInt((*t).counter, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_30)) { raiseOverflow(); goto BeforeRet_;
};
		(*t).counter = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_30);
	}
	goto LA6_;
	LA8_: ;
	{
		result = NIM_TRUE;
	}
	LA6_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {
{	{
		void* T5_;
		void* T6_;
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_33;
		NI TM__4SoG2KRQy3oMm9aUzSLtGrA_34;
		if (!(((NI) 0) < src.len)) goto LA3_;
		T5_ = (void*)0;
		T5_ = ((void*) ((&(*(*dest).p).data[(*dest).len])));
		T6_ = (void*)0;
		T6_ = ((void*) ((&(*src.p).data[((NI) 0)])));
		if (nimAddInt(src.len, ((NI) 1), &TM__4SoG2KRQy3oMm9aUzSLtGrA_33)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_33)) < ((NI) 0) || ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_33)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_33), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(T5_, T6_, ((NI) ((NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_33))));
		if (nimAddInt((*dest).len, src.len, &TM__4SoG2KRQy3oMm9aUzSLtGrA_34)) { raiseOverflow(); goto BeforeRet_;
};
		(*dest).len = (NI)(TM__4SoG2KRQy3oMm9aUzSLtGrA_34);
	}
	LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NU32, X5BX5D___izypgEXDrOPhvdwKMbE2zw)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key) {
	NU32 result;
	NI hcX60gensym20_;
	NI indexX60gensym20_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU32)0;
	hcX60gensym20_ = (NI)0;
	indexX60gensym20_ = rawGet__pY6329cH3wTIej7zDOgE3yQtables(t, key, (&hcX60gensym20_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(((NI) 0) <= indexX60gensym20_)) goto LA3_;
		if ((NU)(indexX60gensym20_) >= (NU)t.data.len){ raiseIndexError2(indexX60gensym20_,t.data.len-1); goto BeforeRet_;
}
		result = t.data.p->data[indexX60gensym20_].Field2;
	}
	goto LA1_;
	LA3_: ;
	{
		NimStringV2 colontmpD_;
		tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag* T7_;
		NimStringV2 T8_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		T7_ = (tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag*)0;
		T7_ = (tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag*) nimNewObj(sizeof(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag), NIM_ALIGNOF(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag));
		(*T7_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__t7nhKLvXTQS9cS8ByJU9bIag_);
		(*T7_).Sup.Sup.Sup.name = "KeyError";
		T8_.len = 0; T8_.p = NIM_NIL;
		colontmpD_ = dollar___qYzpYseuMj9cCKH1yCYQR2Q(key);
		T8_ = rawNewString(colontmpD_.len + 15);
appendString((&T8_), TM__4SoG2KRQy3oMm9aUzSLtGrA_32);
appendString((&T8_), colontmpD_);
		(*T7_).Sup.Sup.Sup.message = T8_;
		(*T7_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "KeyError", "[]", "tables.nim", 262);
		goto LA6_;
		{
			LA6_:;
		}
		{
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___1Zp2RxHLXcmaoTqnxTPf9cw)(tySequence__XMerIiAQb66xYd9a9cuy80SQ* dest, tySequence__XMerIiAQb66xYd9a9cuy80SQ src) {
	NI T1_;
	NI colontmp_;
	T1_ = src.len;
	setLen__y5G129bGEFh1qNKyeVIxRtg((&(*dest)), T1_);
	colontmp_ = ((NI) 0);
	{
		while (1) {
			NI T4_;
			T4_ = (*dest).len;
			if (!(colontmp_ < T4_)) goto LA3;
			(*dest).p->data[colontmp_].Field0 = src.p->data[colontmp_].Field0;
			(*dest).p->data[colontmp_].Field1 = src.p->data[colontmp_].Field1;
			(*dest).p->data[colontmp_].Field2 = src.p->data[colontmp_].Field2;
			colontmp_ += ((NI) 1);
		} LA3: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___71gLqJJRAXmB7dO800Kngg)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A* dest, tyObject_Table__b4vpoerBR7V29ajKx2FDs6A src) {
	eqcopy___1Zp2RxHLXcmaoTqnxTPf9cw((&(*dest).data), src.data);
	(*dest).counter = src.counter;
}
N_LIB_PRIVATE N_NIMCALL(NI, len__CFEeD1cbzlG3EqLWcLD4eg)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w t) {
	NI result;
	result = (NI)0;
	result = t.counter;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, getOrDefault__rJcaoBQ5Dqs3bvDKIAnm9aA)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key, NI default_0) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI hcX60gensym65_;
	NI indexX60gensym65_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	hcX60gensym65_ = (NI)0;
	indexX60gensym65_ = rawGet__ja1IrNE5a39arNB35Q5H8ngtables(t, key, (&hcX60gensym65_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(((NI) 0) <= indexX60gensym65_)) goto LA3_;
		if ((NU)(indexX60gensym65_) >= (NU)t.data.len){ raiseIndexError2(indexX60gensym65_,t.data.len-1); goto BeforeRet_;
}
		colontmpD_ = t.data.p->data[indexX60gensym65_].Field2;
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		colontmpD__2 = default_0;
		result = colontmpD__2;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, X5BX5D___E3nu0mxbUgUihx3VzztAZQ)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A t, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w key) {
	NI result;
	NI hcX60gensym20_;
	NI indexX60gensym20_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	hcX60gensym20_ = (NI)0;
	indexX60gensym20_ = rawGet__ja1IrNE5a39arNB35Q5H8ngtables(t, key, (&hcX60gensym20_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		if (!(((NI) 0) <= indexX60gensym20_)) goto LA3_;
		if ((NU)(indexX60gensym20_) >= (NU)t.data.len){ raiseIndexError2(indexX60gensym20_,t.data.len-1); goto BeforeRet_;
}
		result = t.data.p->data[indexX60gensym20_].Field2;
	}
	goto LA1_;
	LA3_: ;
	{
		NimStringV2 colontmpD_;
		tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag* T7_;
		NimStringV2 T8_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		T7_ = (tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag*)0;
		T7_ = (tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag*) nimNewObj(sizeof(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag), NIM_ALIGNOF(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag));
		(*T7_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__t7nhKLvXTQS9cS8ByJU9bIag_);
		(*T7_).Sup.Sup.Sup.name = "KeyError";
		T8_.len = 0; T8_.p = NIM_NIL;
		colontmpD_ = dollar___qYzpYseuMj9cCKH1yCYQR2Q(key);
		T8_ = rawNewString(colontmpD_.len + 15);
appendString((&T8_), TM__4SoG2KRQy3oMm9aUzSLtGrA_35);
appendString((&T8_), colontmpD_);
		(*T7_).Sup.Sup.Sup.message = T8_;
		(*T7_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "KeyError", "[]", "tables.nim", 262);
		goto LA6_;
		{
			LA6_:;
		}
		{
			eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___XCKmUiS3Ov3AJGom9cXECmg)(tyObject_Table__b4vpoerBR7V29ajKx2FDs6A* dest) {
	eqdestroy___9bWzf0v8OmYlwSMXdUYENEg((&(*dest).data));
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___1eV9bfPFgzYvCGm9bXLSWubw)(tyObject_Table__CEbiADMtqwDYLcvZbib9b2w* dest) {
	eqdestroy___O8Va9cr5zuMR80E1G5hQtag((&(*dest).data));
}
