/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
#define nimfr_(x, y)
#define nimln_(x, y)

/* section: NIM_merge_FORWARD_TYPES */
typedef struct tySequence__edypeVHoNy9czAu9cukTSm3Q tySequence__edypeVHoNy9czAu9cukTSm3Q;
typedef struct tySequence__edypeVHoNy9czAu9cukTSm3Q_Content tySequence__edypeVHoNy9czAu9cukTSm3Q_Content;
typedef struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA tySequence__9bAGqSvkAaFL9bWjsEPslrFA;
typedef struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content;

/* section: NIM_merge_TYPES */
struct tySequence__edypeVHoNy9czAu9cukTSm3Q {
  NI len; tySequence__edypeVHoNy9czAu9cukTSm3Q_Content* p;
};
typedef NU8 tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w;
struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA {
  NI len; tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content* p;
};


#ifndef tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
#define tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
struct tySequence__edypeVHoNy9czAu9cukTSm3Q_Content { NI cap; tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
#define tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
struct tySequence__edypeVHoNy9czAu9cukTSm3Q_Content { NI cap; tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
#define tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
struct tySequence__edypeVHoNy9czAu9cukTSm3Q_Content { NI cap; tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
#define tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content { NI cap; NU32 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
#define tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content { NI cap; NU32 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
#define tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content { NI cap; NU32 data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize, NI elemAlign);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
N_LIB_PRIVATE N_NIMCALL(void, add__GzUH6O0SjRuWHzfOn1f8Tw)(tySequence__edypeVHoNy9czAu9cukTSm3Q* x, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w value);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, contains__euKUSGoRAiFSSauF1RMdtwsystem)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* a, NI aLen_0, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w item);
static N_INLINE(NI, find__Mx6kBeiWXyaSZ9c3wKZA1fAsystem)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* a, NI aLen_0, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w item);
N_LIB_PRIVATE N_NIMCALL(void, add__lY5DLRz4X2A2isf2LBd6tQ)(tySequence__9bAGqSvkAaFL9bWjsEPslrFA* x, NU32 value);
static N_INLINE(NIM_BOOL, contains__WCUX1CZgbeHASbBXkwW9aOQsystem)(NU32* a, NI aLen_0, NU32 item);
static N_INLINE(NI, find__iDzDj0pQJgr8e6Wa7f809aQsystem)(NU32* a, NI aLen_0, NU32 item);

/* section: NIM_merge_PROCS */
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU32)(((NU) (a))) + (NU32)(((NU) (b))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(r ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(r ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		(*res) = r;
	}
	goto LA1_;
	LA5_: ;
	{
		result = NIM_TRUE;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, find__Mx6kBeiWXyaSZ9c3wKZA1fAsystem)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* a, NI aLen_0, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w item) {
	NI result;
{	result = (NI)0;
	result = ((NI) 0);
	{
		tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* i;
		NI i_2;
		i = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w*)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI TM__77ITQxrABVT9b2GcbWeV4SQ_3;
				NI TM__77ITQxrABVT9b2GcbWeV4SQ_4;
				if (!(i_2 < aLen_0)) goto LA3;
				if ((NU)(i_2) >= (NU)(aLen_0)){ raiseIndexError2(i_2,aLen_0-1); goto BeforeRet_;
}
				i = (&a[i_2]);
				{
					if (!((*i) == item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				if (nimAddInt(result, ((NI) 1), &TM__77ITQxrABVT9b2GcbWeV4SQ_3)) { raiseOverflow(); goto BeforeRet_;
};
				result = (NI)(TM__77ITQxrABVT9b2GcbWeV4SQ_3);
				if (nimAddInt(i_2, ((NI) 1), &TM__77ITQxrABVT9b2GcbWeV4SQ_4)) { raiseOverflow(); goto BeforeRet_;
};
				i_2 = (NI)(TM__77ITQxrABVT9b2GcbWeV4SQ_4);
			} LA3: ;
		}
	}
	result = ((NI) -1);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, contains__euKUSGoRAiFSSauF1RMdtwsystem)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* a, NI aLen_0, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w item) {
	NIM_BOOL result;
	NI T1_;
{	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = find__Mx6kBeiWXyaSZ9c3wKZA1fAsystem(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__edypeVHoNy9czAu9cukTSm3Q, deduplicate__Ts9cgRykKmyvsc9brXQifXBw)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* s, NI sLen_0, NIM_BOOL isSorted) {
	tySequence__edypeVHoNy9czAu9cukTSm3Q result;
{	result.len = 0; result.p = NIM_NIL;
	result.len = 0; result.p = (tySequence__edypeVHoNy9czAu9cukTSm3Q_Content*) newSeqPayload(0, sizeof(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w), NIM_ALIGNOF(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w));
	{
		if (!(((NI) 0) < sLen_0)) goto LA3_;
		{
			tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w colontmpD_;
			tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w prev;
			if (!isSorted) goto LA7_;
			colontmpD_ = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
			if ((NU)(((NI) 0)) >= (NU)(sLen_0)){ raiseIndexError2(((NI) 0),sLen_0-1); goto BeforeRet_;
}
			prev = s[((NI) 0)];
			colontmpD_ = prev;
			add__GzUH6O0SjRuWHzfOn1f8Tw((&result), colontmpD_);
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (sLen_0-1);
				res = ((NI) 1);
				{
					while (1) {
						NI TM__77ITQxrABVT9b2GcbWeV4SQ_2;
						if (!(res <= colontmp_)) goto LA11;
						i = res;
						{
							tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w colontmpD__2;
							if ((NU)(i) >= (NU)(sLen_0)){ raiseIndexError2(i,sLen_0-1); goto BeforeRet_;
}
							if (!!((s[i] == prev))) goto LA14_;
							colontmpD__2 = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
							if ((NU)(i) >= (NU)(sLen_0)){ raiseIndexError2(i,sLen_0-1); goto BeforeRet_;
}
							prev = s[i];
							colontmpD__2 = prev;
							add__GzUH6O0SjRuWHzfOn1f8Tw((&result), colontmpD__2);
						}
						LA14_: ;
						if (nimAddInt(res, ((NI) 1), &TM__77ITQxrABVT9b2GcbWeV4SQ_2)) { raiseOverflow(); goto BeforeRet_;
};
						res = (NI)(TM__77ITQxrABVT9b2GcbWeV4SQ_2);
					} LA11: ;
				}
			}
		}
		goto LA5_;
		LA7_: ;
		{
			{
				tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* itm;
				NI i_2;
				itm = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w*)0;
				i_2 = ((NI) 0);
				{
					while (1) {
						NI TM__77ITQxrABVT9b2GcbWeV4SQ_5;
						if (!(i_2 < sLen_0)) goto LA19;
						if ((NU)(i_2) >= (NU)(sLen_0)){ raiseIndexError2(i_2,sLen_0-1); goto BeforeRet_;
}
						itm = (&s[i_2]);
						{
							NIM_BOOL T22_;
							tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w colontmpD__3;
							T22_ = (NIM_BOOL)0;
							T22_ = contains__euKUSGoRAiFSSauF1RMdtwsystem(result.p->data, result.len, (*itm));
							if (!!(T22_)) goto LA23_;
							colontmpD__3 = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
							colontmpD__3 = (*itm);
							add__GzUH6O0SjRuWHzfOn1f8Tw((&result), colontmpD__3);
						}
						LA23_: ;
						if (nimAddInt(i_2, ((NI) 1), &TM__77ITQxrABVT9b2GcbWeV4SQ_5)) { raiseOverflow(); goto BeforeRet_;
};
						i_2 = (NI)(TM__77ITQxrABVT9b2GcbWeV4SQ_5);
					} LA19: ;
				}
			}
		}
		LA5_: ;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, find__iDzDj0pQJgr8e6Wa7f809aQsystem)(NU32* a, NI aLen_0, NU32 item) {
	NI result;
{	result = (NI)0;
	result = ((NI) 0);
	{
		NU32* i;
		NI i_2;
		i = (NU32*)0;
		i_2 = ((NI) 0);
		{
			while (1) {
				NI TM__77ITQxrABVT9b2GcbWeV4SQ_7;
				NI TM__77ITQxrABVT9b2GcbWeV4SQ_8;
				if (!(i_2 < aLen_0)) goto LA3;
				if ((NU)(i_2) >= (NU)(aLen_0)){ raiseIndexError2(i_2,aLen_0-1); goto BeforeRet_;
}
				i = (&a[i_2]);
				{
					if (!((*i) == item)) goto LA6_;
					goto BeforeRet_;
				}
				LA6_: ;
				if (nimAddInt(result, ((NI) 1), &TM__77ITQxrABVT9b2GcbWeV4SQ_7)) { raiseOverflow(); goto BeforeRet_;
};
				result = (NI)(TM__77ITQxrABVT9b2GcbWeV4SQ_7);
				if (nimAddInt(i_2, ((NI) 1), &TM__77ITQxrABVT9b2GcbWeV4SQ_8)) { raiseOverflow(); goto BeforeRet_;
};
				i_2 = (NI)(TM__77ITQxrABVT9b2GcbWeV4SQ_8);
			} LA3: ;
		}
	}
	result = ((NI) -1);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, contains__WCUX1CZgbeHASbBXkwW9aOQsystem)(NU32* a, NI aLen_0, NU32 item) {
	NIM_BOOL result;
	NI T1_;
{	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = find__iDzDj0pQJgr8e6Wa7f809aQsystem(a, aLen_0, item);
	result = (((NI) 0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__9bAGqSvkAaFL9bWjsEPslrFA, deduplicate__HKntiik9czuNpOlIyPbbFUQ)(NU32* s, NI sLen_0, NIM_BOOL isSorted) {
	tySequence__9bAGqSvkAaFL9bWjsEPslrFA result;
{	result.len = 0; result.p = NIM_NIL;
	result.len = 0; result.p = (tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content*) newSeqPayload(0, sizeof(NU32), NIM_ALIGNOF(NU32));
	{
		if (!(((NI) 0) < sLen_0)) goto LA3_;
		{
			NU32 colontmpD_;
			NU32 prev;
			if (!isSorted) goto LA7_;
			colontmpD_ = (NU32)0;
			if ((NU)(((NI) 0)) >= (NU)(sLen_0)){ raiseIndexError2(((NI) 0),sLen_0-1); goto BeforeRet_;
}
			prev = s[((NI) 0)];
			colontmpD_ = prev;
			add__lY5DLRz4X2A2isf2LBd6tQ((&result), colontmpD_);
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (sLen_0-1);
				res = ((NI) 1);
				{
					while (1) {
						NI TM__77ITQxrABVT9b2GcbWeV4SQ_6;
						if (!(res <= colontmp_)) goto LA11;
						i = res;
						{
							NU32 colontmpD__2;
							if ((NU)(i) >= (NU)(sLen_0)){ raiseIndexError2(i,sLen_0-1); goto BeforeRet_;
}
							if (!!((s[i] == prev))) goto LA14_;
							colontmpD__2 = (NU32)0;
							if ((NU)(i) >= (NU)(sLen_0)){ raiseIndexError2(i,sLen_0-1); goto BeforeRet_;
}
							prev = s[i];
							colontmpD__2 = prev;
							add__lY5DLRz4X2A2isf2LBd6tQ((&result), colontmpD__2);
						}
						LA14_: ;
						if (nimAddInt(res, ((NI) 1), &TM__77ITQxrABVT9b2GcbWeV4SQ_6)) { raiseOverflow(); goto BeforeRet_;
};
						res = (NI)(TM__77ITQxrABVT9b2GcbWeV4SQ_6);
					} LA11: ;
				}
			}
		}
		goto LA5_;
		LA7_: ;
		{
			{
				NU32* itm;
				NI i_2;
				itm = (NU32*)0;
				i_2 = ((NI) 0);
				{
					while (1) {
						NI TM__77ITQxrABVT9b2GcbWeV4SQ_9;
						if (!(i_2 < sLen_0)) goto LA19;
						if ((NU)(i_2) >= (NU)(sLen_0)){ raiseIndexError2(i_2,sLen_0-1); goto BeforeRet_;
}
						itm = (&s[i_2]);
						{
							NIM_BOOL T22_;
							NU32 colontmpD__3;
							T22_ = (NIM_BOOL)0;
							T22_ = contains__WCUX1CZgbeHASbBXkwW9aOQsystem(result.p->data, result.len, (*itm));
							if (!!(T22_)) goto LA23_;
							colontmpD__3 = (NU32)0;
							colontmpD__3 = (*itm);
							add__lY5DLRz4X2A2isf2LBd6tQ((&result), colontmpD__3);
						}
						LA23_: ;
						if (nimAddInt(i_2, ((NI) 1), &TM__77ITQxrABVT9b2GcbWeV4SQ_9)) { raiseOverflow(); goto BeforeRet_;
};
						i_2 = (NI)(TM__77ITQxrABVT9b2GcbWeV4SQ_9);
					} LA19: ;
				}
			}
		}
		LA5_: ;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
