/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <signal.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
#define nimfr_(x, y)
#define nimln_(x, y)

/* section: NIM_merge_FORWARD_TYPES */
typedef struct Exception Exception;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct TSafePoint TSafePoint;
typedef struct GcFrameHeader GcFrameHeader;
typedef struct tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ;
typedef struct tyObject_ArithmeticDefect__cT9c9bHlHSpA1QTnKbHjnIkA tyObject_ArithmeticDefect__cT9c9bHlHSpA1QTnKbHjnIkA;
typedef struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content tySequence__uB9b75OUPRENsBAu4AnoePA_Content;
typedef struct tyObject_RangeDefect__Rp9adJYTsbbIUzQ8fWxwgdA tyObject_RangeDefect__Rp9adJYTsbbIUzQ8fWxwgdA;
typedef struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_NimSeqV2__A9aaPj3Ay2mWlTU3QheYz2w tyObject_NimSeqV2__A9aaPj3Ay2mWlTU3QheYz2w;
typedef struct tyObject_NimSeqPayload__T3NJfV3Yh9bN9cuVRNI5QtfQ tyObject_NimSeqPayload__T3NJfV3Yh9bN9cuVRNI5QtfQ;
typedef struct tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw;
typedef struct tyObject_DivByZeroDefect__n3A4gjRrFZBuNnTYx1h9a8w tyObject_DivByZeroDefect__n3A4gjRrFZBuNnTYx1h9a8w;
typedef struct tyObject_IndexDefect__n6tGEPHKkh7E1AP9bj30WrQ tyObject_IndexDefect__n6tGEPHKkh7E1AP9bj30WrQ;
typedef struct tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ;
typedef struct tySequence__edypeVHoNy9czAu9cukTSm3Q tySequence__edypeVHoNy9czAu9cukTSm3Q;
typedef struct tySequence__edypeVHoNy9czAu9cukTSm3Q_Content tySequence__edypeVHoNy9czAu9cukTSm3Q_Content;
typedef struct tyObject_NimSeqV2__Cznlc9aNZHkrRortstTd5dA tyObject_NimSeqV2__Cznlc9aNZHkrRortstTd5dA;
typedef struct tyObject_NimSeqPayload__vzeUId7VpZgOxblQgrHNLA tyObject_NimSeqPayload__vzeUId7VpZgOxblQgrHNLA;
typedef struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA tySequence__9bAGqSvkAaFL9bWjsEPslrFA;
typedef struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content;
typedef struct tyObject_NimSeqV2__fPXN5kjvqQrQGq2BBQ9anlw tyObject_NimSeqV2__fPXN5kjvqQrQGq2BBQ9anlw;
typedef struct tyObject_NimSeqPayload__ZR3g9axPGBSEUI126QLYUIg tyObject_NimSeqPayload__ZR3g9axPGBSEUI126QLYUIg;
typedef struct tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct tySequence__XMerIiAQb66xYd9a9cuy80SQ tySequence__XMerIiAQb66xYd9a9cuy80SQ;
typedef struct tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content;
typedef struct tyObject_NimSeqV2__VABqGxoJY4QkZ9cJjT9cJTLw tyObject_NimSeqV2__VABqGxoJY4QkZ9cJjT9cJTLw;
typedef struct tyObject_NimSeqPayload__Sk8I13hH69c7YfXxOuSgu8w tyObject_NimSeqPayload__Sk8I13hH69c7YfXxOuSgu8w;
typedef struct tyTuple__dxJdLbw7JUOttiF9cPJ6IjA tyTuple__dxJdLbw7JUOttiF9cPJ6IjA;

/* section: NIM_merge_TYPES */
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9axCnCRMUx32AHzFgBrzSMg) (Exception* e);
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef N_NIMCALL_PTR(void, tyProc__NFmM6mqUOVW3cJg4yvk8Fw) (Exception* e);
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef N_NIMCALL_PTR(void, tyProc__W6IXMh2CA4X1rFYGjUb4yg) (NimStringV2 msg);
struct TNimTypeV2 {
void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* disposeImpl;
void* typeInfoV1;
};
struct RootObj {
TNimTypeV2* m_type;
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  NI len; tySequence__uB9b75OUPRENsBAu4AnoePA_Content* p;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__uB9b75OUPRENsBAu4AnoePA trace;
Exception* up;
};
struct tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA {
  Exception Sup;
};
struct tyObject_ArithmeticDefect__cT9c9bHlHSpA1QTnKbHjnIkA {
  tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA Sup;
};
struct tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ {
  tyObject_ArithmeticDefect__cT9c9bHlHSpA1QTnKbHjnIkA Sup;
};
struct tyObject_RangeDefect__Rp9adJYTsbbIUzQ8fWxwgdA {
  tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA Sup;
};
struct tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A {
NI rc;
};
typedef N_NIMCALL_PTR(void, tyProc__4SVlZZPmetqBimNsH9cHcOA) (void* p);
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_NimSeqV2__A9aaPj3Ay2mWlTU3QheYz2w {
NI len;
tyObject_NimSeqPayload__T3NJfV3Yh9bN9cuVRNI5QtfQ* p;
};
struct tyObject_NimSeqPayload__T3NJfV3Yh9bN9cuVRNI5QtfQ {
NI cap;
tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw {
NI cap;
};
struct tyObject_DivByZeroDefect__n3A4gjRrFZBuNnTYx1h9a8w {
  tyObject_ArithmeticDefect__cT9c9bHlHSpA1QTnKbHjnIkA Sup;
};
typedef N_NOCONV_PTR(void, tyProc__ZEo3s9cIqJYP74f7GMZM2FA) (int a);
struct tyObject_IndexDefect__n6tGEPHKkh7E1AP9bj30WrQ {
  tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA Sup;
};
struct tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ {
  tyObject_Defect__LbeSGvgPzGzXnW9caIkJqMA Sup;
};
struct tySequence__edypeVHoNy9czAu9cukTSm3Q {
  NI len; tySequence__edypeVHoNy9czAu9cukTSm3Q_Content* p;
};
typedef NU8 tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w;
struct tyObject_NimSeqV2__Cznlc9aNZHkrRortstTd5dA {
NI len;
tyObject_NimSeqPayload__vzeUId7VpZgOxblQgrHNLA* p;
};
struct tyObject_NimSeqPayload__vzeUId7VpZgOxblQgrHNLA {
NI cap;
tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w data[SEQ_DECL_SIZE];
};
struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA {
  NI len; tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content* p;
};
struct tyObject_NimSeqV2__fPXN5kjvqQrQGq2BBQ9anlw {
NI len;
tyObject_NimSeqPayload__ZR3g9axPGBSEUI126QLYUIg* p;
};
struct tyObject_NimSeqPayload__ZR3g9axPGBSEUI126QLYUIg {
NI cap;
NU32 data[SEQ_DECL_SIZE];
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag {
  tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw Sup;
};
struct tySequence__XMerIiAQb66xYd9a9cuy80SQ {
  NI len; tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content* p;
};
struct tyObject_NimSeqV2__VABqGxoJY4QkZ9cJjT9cJTLw {
NI len;
tyObject_NimSeqPayload__Sk8I13hH69c7YfXxOuSgu8w* p;
};
struct tyTuple__dxJdLbw7JUOttiF9cPJ6IjA {
NI Field0;
tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w Field1;
NI Field2;
};
struct tyObject_NimSeqPayload__Sk8I13hH69c7YfXxOuSgu8w {
NI cap;
tyTuple__dxJdLbw7JUOttiF9cPJ6IjA data[SEQ_DECL_SIZE];
};


#ifndef tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
#define tySequence__uB9b75OUPRENsBAu4AnoePA_Content_PP
struct tySequence__uB9b75OUPRENsBAu4AnoePA_Content { NI cap; tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
#define tySequence__edypeVHoNy9czAu9cukTSm3Q_Content_PP
struct tySequence__edypeVHoNy9czAu9cukTSm3Q_Content { NI cap; tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
#define tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content_PP
struct tySequence__9bAGqSvkAaFL9bWjsEPslrFA_Content { NI cap; NU32 data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content_PP
#define tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content_PP
struct tySequence__XMerIiAQb66xYd9a9cuy80SQ_Content { NI cap; tyTuple__dxJdLbw7JUOttiF9cPJ6IjA data[SEQ_DECL_SIZE];};
#endif

      
/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(void, initStackBottom)(void);
N_LIB_PRIVATE N_NOCONV(void, signalHandler)(int sign);
N_LIB_PRIVATE N_NIMCALL(void, showErrorMessage__zsORN9crdKxsL9cHrQcdHSMw)(NCSTRING data);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toNimStr)(NCSTRING str, NI len);
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__aMIFDISudztFhhVWVqortg)(NI size);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, sysFatal__pO9abt7E7FWB3DInHeLgZeQsystem)(NimStringV2 message);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
N_LIB_PRIVATE N_NIMCALL(NI, align__vzThvqZajaR9ct9cQ7SOy1tQ)(NI address, NI alignment);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res);
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void*, alignedAlloc0__YbpLWudJqnECYmKZquJKyw)(NI size, NI align);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
static N_INLINE(void, sysFatal__Kx89alMoFPpWrEL9bx2cyJVwsystem)(NimStringV2 message);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___LZ4ekoCGfhYJ49aM9aFAL7AQ)(tyObject_RangeDefect__Rp9adJYTsbbIUzQ8fWxwgdA* dest);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p);
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p, NI alignment);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p, NI align);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p);
N_LIB_PRIVATE N_NOCONV(void, deallocImpl__SAtZpVrJ3o5FJvSdLQe9auA)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___4fQQqvAqifkWGVa4g39cI5A)(tySequence__uB9b75OUPRENsBAu4AnoePA* dest);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void, add__VHIeeMfqavFfKtbV1Wal0Q)(tySequence__uB9b75OUPRENsBAu4AnoePA* x, tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA value);
N_LIB_PRIVATE N_NIMCALL(void*, prepareSeqAdd)(NI len, void* p, NI addlen, NI elemSize, NI elemAlign);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize, NI elemAlign);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res);
static N_INLINE(NF, toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem)(NI i);
static N_INLINE(NF, abs__BRaAqinz6OWTHkALb4oj6Qsystem)(NF x);
static N_INLINE(NI, resize__cOCDWr16YD4j3dBrbbH3yQsystem)(NI old);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(void, sysFatal__hS39cHxXy8HTQIYRwfPrH3gsystem)(NimStringV2 message);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___BO2qxEc1Yf80x0M89aiw9cAQ)(tyObject_DivByZeroDefect__n3A4gjRrFZBuNnTYx1h9a8w* dest);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res);
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(void*, alignedRealloc0__CUuMVCxdCmrsVspc3L8xgw)(void* p, NI oldSize, NI newSize, NI align);
N_LIB_PRIVATE N_NOCONV(void*, realloc0Impl__Jvtux8Lvp7XxQp3KVEEn5A)(void* p, NI oldSize, NI newSize);
N_LIB_PRIVATE N_NOCONV(void*, reallocImpl__rECPuEN9bJi2ySIlkZO0kdA)(void* p, NI newSize);
static N_INLINE(void, zeroMem__9cLyRtoQz0YlIMEd4qW7Hdgsystem)(void* p, NI size);
N_LIB_PRIVATE N_NIMCALL(void*, alignedAlloc__YbpLWudJqnECYmKZquJKyw_2)(NI size, NI align);
N_LIB_PRIVATE N_NOCONV(void*, allocImpl__aMIFDISudztFhhVWVqortg_2)(NI size);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionAux__na8C8pUZ9cLQWVwk35l5vfw)(Exception* e);
static N_INLINE(void, pushCurrentException)(Exception* e);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___rR9boD7urcxl7uyUtE46AOA)(Exception** dest, Exception* src);
static N_INLINE(void, nimIncRef)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___rR9boD7urcxl7uyUtE46AOA_2)(Exception** dest, Exception* src);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimInt64ToStr)(NI64 x);
N_NIMCALL(NimStringV2, rawNewString)(NI cap);
N_LIB_PRIVATE N_NIMCALL(void, addInt__mftMOxbyu0h4yByfs3sqjA)(NimStringV2* result, NI64 x);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__C0YoABEefTaYbWLv9aVOzZA)(NimStringV2* s);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___iXyOdhIrs6C9bvzrDNqxI2g)(tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ* dest);
static N_INLINE(NI, nimCStrLen)(NCSTRING a);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, writeToStdErr__a2kDfqdSc1eYf0ZCWOGinQ)(NCSTRING msg);
static N_INLINE(void, rawWrite)(FILE* f, NCSTRING s);
N_LIB_PRIVATE N_NIMCALL(void, registerSignalHandler__amVlU9ajqZ06ujoesRBHcDg)(void);
static N_INLINE(void, sysFatal__BVaWgkQV7bsZ7qgkYxa9a0Asystem)(NimStringV2 message);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___qRVWt3jIAyom1VkyIWI7tA)(tyObject_IndexDefect__n6tGEPHKkh7E1AP9bj30WrQ* dest);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimIntToStr)(NI x);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___sUPxfcqVijR0WN3SH4QQ6A)(tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ* dest);
N_LIB_PRIVATE N_NIMCALL(void, nimAsgnStrV2)(NimStringV2* a, NimStringV2 b);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(void*, seqToPtr__OWrcycNEyUUgue13ItpQvgsystem)(tySequence__edypeVHoNy9czAu9cukTSm3Q x);
static N_INLINE(void*, seqToPtr__b4bBbdZpDc9bTWf9bgTld08Asystem)(tySequence__9bAGqSvkAaFL9bWjsEPslrFA x);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vttz8U9aaHVcOkTLV69bskjQ)(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag* dest);
N_LIB_PRIVATE N_NIMCALL(void, shrink__YjMr9cTZ2znYg9aJTDqDzgvg)(tySequence__XMerIiAQb66xYd9a9cuy80SQ* x, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, reportUnhandledError__na8C8pUZ9cLQWVwk35l5vfw_2)(Exception* e);

/* section: NIM_merge_DATA */
N_LIB_PRIVATE TNimTypeV2 NTIv2__Rp9adJYTsbbIUzQ8fWxwgdA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__n3A4gjRrFZBuNnTYx1h9a8w_;
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_17 = { 16 | NIM_STRLIT_FLAG, "division by zero" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_18 = {16, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_17};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_37 = { 20 | NIM_STRLIT_FLAG, "value out of range: " };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_38 = {20, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_37};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_54 = { 7 | NIM_STRLIT_FLAG, " notin " };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_55 = {7, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_54};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_56 = { 4 | NIM_STRLIT_FLAG, " .. " };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_57 = {4, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_56};
N_LIB_PRIVATE TNimTypeV2 NTIv2__9cxMi1BPLc3UKt9br86bGfGQ_;
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_61 = { 18 | NIM_STRLIT_FLAG, "over- or underflow" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_62 = {18, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_61};
N_LIB_PRIVATE TNimTypeV2 NTIv2__n6tGEPHKkh7E1AP9bj30WrQ_;
static const struct {
  NI cap; NIM_CHAR data[43+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_64 = { 43 | NIM_STRLIT_FLAG, "index out of bounds, the container is empty" };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_65 = {43, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_64};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_66 = { 6 | NIM_STRLIT_FLAG, "index " };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_67 = {6, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_66};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__Q5wkpxktOdTGvlSRo9bzt9aw_68 = { 13 | NIM_STRLIT_FLAG, " not in 0 .. " };
static const NimStringV2 TM__Q5wkpxktOdTGvlSRo9bzt9aw_69 = {13, (NimStrPayload*)&TM__Q5wkpxktOdTGvlSRo9bzt9aw_68};
N_LIB_PRIVATE TNimTypeV2 NTIv2__PtYxPmY5X0dorfvxAFbJpQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__t7nhKLvXTQS9cS8ByJU9bIag_;

/* section: NIM_merge_VARS */
N_LIB_PRIVATE NI nim_program_result;
N_LIB_PRIVATE tyProc__9axCnCRMUx32AHzFgBrzSMg globalRaiseHook__JbO1ti4ULxrw54m4zNPbpA;
N_LIB_PRIVATE tyProc__9axCnCRMUx32AHzFgBrzSMg localRaiseHook__EIvMhANBvB9cp2Ezvt29cADg;
N_LIB_PRIVATE tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ outOfMemHook__kZNaA7u1MfSW5ZeoGvw8xg;
N_LIB_PRIVATE tyProc__NFmM6mqUOVW3cJg4yvk8Fw unhandledExceptionHook__RJpSsXsRUH8ochbXTEhRIw;
N_LIB_PRIVATE Exception* currException__9bVPeDJlYTi9bQApZpfH8wjg;
N_LIB_PRIVATE tyProc__W6IXMh2CA4X1rFYGjUb4yg errorMessageWriter__ZXnv0JyrWe3HTd07wpSr7A;
N_LIB_PRIVATE TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
N_LIB_PRIVATE TSafePoint* excHandler__rqLlY5bs9atDw2OXYqJEn5g;
N_LIB_PRIVATE GcFrameHeader* gcFramePtr__ot48iojqko9aFxGhyjjjVaA;
N_LIB_PRIVATE tyProc__W6IXMh2CA4X1rFYGjUb4yg onUnhandledException__bFrawQlTKZhLweDD36j9b8g;
N_LIB_PRIVATE NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */
static N_INLINE(void, initStackBottom)(void) {
}
static N_INLINE(void, nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__JE6t4x7Z3v2iVz27Nx0MRAmemory(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__aMIFDISudztFhhVWVqortg)(NI size) {
	void* result;
	result = (void*)0;
	result = calloc(((size_t) (size)), ((size_t) 1));
	return result;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU32)(((NU) (a))) + (NU32)(((NU) (b))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(r ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(r ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		(*res) = r;
	}
	goto LA1_;
	LA5_: ;
	{
		result = NIM_TRUE;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	NI r;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU32)(((NU) (a))) - (NU32)(((NU) (b))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(r ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(r ^ (NI)((NU32) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		(*res) = r;
	}
	goto LA1_;
	LA5_: ;
	{
		result = NIM_TRUE;
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, align__vzThvqZajaR9ct9cQ7SOy1tQ)(NI address, NI alignment) {
	NI result;
{	result = (NI)0;
	{
		if (!(alignment == ((NI) 0))) goto LA3_;
		result = address;
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_3;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_4;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_5;
		if (nimSubInt(alignment, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_3)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt(address, (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_3), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_4)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimSubInt(alignment, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_5)) { raiseOverflow(); goto BeforeRet_;
};
		result = (NI)((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_4) & (NI)((NU32) ~((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_5))));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) + (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(NI, minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A* cell;
		NI T5_;
		if (!!((p == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (p)), ((NI) 4));
		cell = ((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T5_));
		{
			if (!((NI)((*cell).rc & ((NI) -8)) == ((NI) 0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
		LA8_: ;
		{
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_10;
			if (nimSubInt((*cell).rc, ((NI) 8), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_10)) { raiseOverflow(); goto BeforeRet_;
};
			(*cell).rc = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_10);
		}
		LA6_: ;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NOCONV(void, deallocImpl__SAtZpVrJ3o5FJvSdLQe9auA)(void* p) {
	free(p);
}
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p) {
	deallocImpl__SAtZpVrJ3o5FJvSdLQe9auA(p);
}
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p, NI align) {
	{
		if (!(align <= ((NI) 8))) goto LA3_;
		dealloc(p);
	}
	goto LA1_;
	LA3_: ;
	{
		NU16 offset;
		NI T6_;
		NI T7_;
		T6_ = (NI)0;
		T6_ = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (p)), ((NI) 2));
		offset = (*((NU16*) (((void*) (T6_)))));
		T7_ = (NI)0;
		T7_ = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (p)), ((NI) (offset)));
		dealloc(((void*) (T7_)));
	}
	LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p, NI alignment) {
	NI hdrSize;
	NI T1_;
	hdrSize = align__vzThvqZajaR9ct9cQ7SOy1tQ(((NI) 4), alignment);
	T1_ = (NI)0;
	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (p)), hdrSize);
	alignedDealloc(((void*) (T1_)), alignment);
}
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p) {
	TNimTypeV2** rti;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	rti = ((TNimTypeV2**) (p));
	{
		if (!!(((*(*rti)).destructor == NIM_NIL))) goto LA3_;
		((tyProc__4SVlZZPmetqBimNsH9cHcOA) ((*(*rti)).destructor))(p);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA3_: ;
	nimRawDispose(p, (*(*rti)).align);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest) {
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest).p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___4fQQqvAqifkWGVa4g39cI5A)(tySequence__uB9b75OUPRENsBAu4AnoePA* dest) {
	NI colontmp_;
	colontmp_ = ((NI) 0);
	{
		while (1) {
			NI T3_;
			T3_ = (*dest).len;
			if (!(colontmp_ < T3_)) goto LA2;
			colontmp_ += ((NI) 1);
		} LA2: ;
	}
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc((*dest).p, NIM_ALIGNOF(tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___LZ4ekoCGfhYJ49aM9aFAL7AQ)(tyObject_RangeDefect__Rp9adJYTsbbIUzQ8fWxwgdA* dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest).Sup.Sup.parent);
	}
	LA4_: ;
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).Sup.Sup.message));
	eqdestroy___4fQQqvAqifkWGVa4g39cI5A((&(*dest).Sup.Sup.trace));
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest).Sup.Sup.up);
	}
	LA9_: ;
}
static N_INLINE(NF, toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem)(NI i) {
	NF result;
	result = (NF)0;
	result = ((NF) (i));
	return result;
}
static N_INLINE(NF, abs__BRaAqinz6OWTHkALb4oj6Qsystem)(NF x) {
	NF result;
	NF colontmpD_;
	NF colontmpD__2;
	result = (NF)0;
	colontmpD_ = (NF)0;
	colontmpD__2 = (NF)0;
	{
		if (!(x < 0.0)) goto LA3_;
		colontmpD_ = -(x);
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		colontmpD__2 = x;
		result = colontmpD__2;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	NI r;
	NF floatProd;
	NF T1_;
	NF T2_;
	NF resAsFloat;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU32)(((NU) (a))) * (NU32)(((NU) (b))))));
	T1_ = (NF)0;
	T1_ = toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem(a);
	T2_ = (NF)0;
	T2_ = toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem(b);
	floatProd = ((NF)(T1_) * (NF)(T2_));
	resAsFloat = toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem(r);
	{
		if (!(resAsFloat == floatProd)) goto LA5_;
		(*res) = r;
	}
	goto LA3_;
	LA5_: ;
	{
		{
			NF T10_;
			NF T11_;
			T10_ = (NF)0;
			T10_ = abs__BRaAqinz6OWTHkALb4oj6Qsystem(((NF)(resAsFloat) - (NF)(floatProd)));
			T11_ = (NF)0;
			T11_ = abs__BRaAqinz6OWTHkALb4oj6Qsystem(floatProd);
			if (!(((NF)(3.2000000000000000e+01) * (NF)(T10_)) <= T11_)) goto LA12_;
			(*res) = r;
		}
		goto LA8_;
		LA12_: ;
		{
			result = NIM_TRUE;
		}
		LA8_: ;
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap, NI elemSize, NI elemAlign) {
	void* result;
{	result = (void*)0;
	{
		tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw* p;
		NI T5_;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_12;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_13;
		void* T6_;
		if (!(((NI) 0) < cap)) goto LA3_;
		T5_ = (NI)0;
		T5_ = align__vzThvqZajaR9ct9cQ7SOy1tQ(((NI) 4), elemAlign);
		if (nimMulInt(cap, elemSize, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_12)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt(T5_, (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_12), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_13)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_13)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_13)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_13), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		if ((elemAlign) < ((NI) 0) || (elemAlign) > ((NI) 2147483647)){ raiseRangeErrorI(elemAlign, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		T6_ = (void*)0;
		T6_ = alignedAlloc0__YbpLWudJqnECYmKZquJKyw(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_13))), ((NI) (elemAlign)));
		p = ((tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw*) (T6_));
		(*p).cap = cap;
		result = ((void*) (p));
	}
	goto LA1_;
	LA3_: ;
	{
		result = NIM_NIL;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___BO2qxEc1Yf80x0M89aiw9cAQ)(tyObject_DivByZeroDefect__n3A4gjRrFZBuNnTYx1h9a8w* dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest).Sup.Sup.Sup.parent);
	}
	LA4_: ;
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).Sup.Sup.Sup.message));
	eqdestroy___4fQQqvAqifkWGVa4g39cI5A((&(*dest).Sup.Sup.Sup.trace));
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest).Sup.Sup.Sup.up);
	}
	LA9_: ;
}
static N_INLINE(void, sysFatal__hS39cHxXy8HTQIYRwfPrH3gsystem)(NimStringV2 message) {
	tyObject_DivByZeroDefect__n3A4gjRrFZBuNnTYx1h9a8w* T2_;
	NimStringV2 blitTmp;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T2_ = (tyObject_DivByZeroDefect__n3A4gjRrFZBuNnTYx1h9a8w*)0;
	T2_ = (tyObject_DivByZeroDefect__n3A4gjRrFZBuNnTYx1h9a8w*) nimNewObj(sizeof(tyObject_DivByZeroDefect__n3A4gjRrFZBuNnTYx1h9a8w), NIM_ALIGNOF(tyObject_DivByZeroDefect__n3A4gjRrFZBuNnTYx1h9a8w));
	(*T2_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__n3A4gjRrFZBuNnTYx1h9a8w_);
	(*T2_).Sup.Sup.Sup.name = "DivByZeroDefect";
	blitTmp = message;
	message.len = 0; message.p = NIM_NIL;
	(*T2_).Sup.Sup.Sup.message = blitTmp;
	raiseExceptionEx((Exception*)T2_, "DivByZeroDefect", "sysFatal", "fatal.nim", 49);
	goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&message));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void) {
	sysFatal__hS39cHxXy8HTQIYRwfPrH3gsystem(TM__Q5wkpxktOdTGvlSRo9bzt9aw_18);
}
static N_INLINE(NIM_BOOL, nimDivInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a == ((NI) (-2147483647 -1)));
		if (!(T3_)) goto LA4_;
		T3_ = (b == ((NI) -1));
		LA4_: ;
		if (!T3_) goto LA5_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA5_: ;
	{
		(*res) = (NI)(a / b);
	}
	LA1_: ;
	return result;
}
static N_INLINE(NI, resize__cOCDWr16YD4j3dBrbbH3yQsystem)(NI old) {
	NI result;
{	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_15;
		if (!(old < ((NI) 65536))) goto LA6_;
		if (nimMulInt(old, ((NI) 2), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_15)) { raiseOverflow(); goto BeforeRet_;
};
		result = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_15);
	}
	goto LA1_;
	LA6_: ;
	{
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_16;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_19;
		if (nimMulInt(old, ((NI) 3), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_16)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI) 2) == 0){ raiseDivByZero(); goto BeforeRet_;
}
		if (nimDivInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_16), ((NI) 2), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_19)) { raiseOverflow(); goto BeforeRet_;
};
		result = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_19);
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__M04YC71iJg1N7gBF3HZTngsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
N_LIB_PRIVATE N_NOCONV(void*, reallocImpl__rECPuEN9bJi2ySIlkZO0kdA)(void* p, NI newSize) {
	void* result;
	result = (void*)0;
	result = realloc(p, ((size_t) (newSize)));
	return result;
}
static N_INLINE(void, zeroMem__9cLyRtoQz0YlIMEd4qW7Hdgsystem)(void* p, NI size) {
	nimZeroMem(p, size);
}
N_LIB_PRIVATE N_NOCONV(void*, realloc0Impl__Jvtux8Lvp7XxQp3KVEEn5A)(void* p, NI oldSize, NI newSize) {
	void* result;
	result = (void*)0;
	result = reallocImpl__rECPuEN9bJi2ySIlkZO0kdA(p, ((NI) (((size_t) (newSize)))));
	{
		void* T5_;
		if (!(((NI) (oldSize)) < ((NI) (newSize)))) goto LA3_;
		T5_ = (void*)0;
		T5_ = ((void*) ((NI)(((NI) (ptrdiff_t) (result)) + ((NI) (oldSize)))));
		zeroMem__9cLyRtoQz0YlIMEd4qW7Hdgsystem(T5_, ((NI) ((NI)(((NI) (newSize)) - ((NI) (oldSize))))));
	}
	LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NOCONV(void*, allocImpl__aMIFDISudztFhhVWVqortg_2)(NI size) {
	void* result;
	result = (void*)0;
	result = malloc(((size_t) (size)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, alignedAlloc__YbpLWudJqnECYmKZquJKyw_2)(NI size, NI align) {
	void* result;
{	result = (void*)0;
	{
		if (!(((NI) (align)) <= ((NI) 8))) goto LA3_;
		result = allocImpl__aMIFDISudztFhhVWVqortg_2(size);
	}
	goto LA1_;
	LA3_: ;
	{
		void* base;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_28;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_29;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_30;
		NI offset;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_31;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_32;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_33;
		NI T6_;
		NI T7_;
		if (nimAddInt(((NI) (size)), ((NI) (align)), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_28)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimSubInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_28), ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_29)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_29), ((NI) 2), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_30)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_30)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_30)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_30), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		base = allocImpl__aMIFDISudztFhhVWVqortg_2(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_30))));
		if (nimSubInt(((NI) (align)), ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_31)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimSubInt(((NI) (align)), (NI)(((NI) (ptrdiff_t) (base)) & (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_31)), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_32)) { raiseOverflow(); goto BeforeRet_;
};
		offset = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_32);
		if (nimSubInt(offset, ((NI) 2), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_33)) { raiseOverflow(); goto BeforeRet_;
};
		T6_ = (NI)0;
		T6_ = pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (base)), (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_33));
		(*((NU16*) (((void*) (T6_))))) = ((NU16) (offset));
		T7_ = (NI)0;
		T7_ = pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (base)), offset);
		result = ((void*) (T7_));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, alignedRealloc0__CUuMVCxdCmrsVspc3L8xgw)(void* p, NI oldSize, NI newSize, NI align) {
	void* result;
{	result = (void*)0;
	{
		if (!(((NI) (align)) <= ((NI) 8))) goto LA3_;
		result = realloc0Impl__Jvtux8Lvp7XxQp3KVEEn5A(p, oldSize, newSize);
	}
	goto LA1_;
	LA3_: ;
	{
		NI T6_;
		void* T7_;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_34;
		result = alignedAlloc__YbpLWudJqnECYmKZquJKyw_2(newSize, align);
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(result, p, oldSize);
		T6_ = (NI)0;
		T6_ = pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (result)), ((NI) (oldSize)));
		T7_ = (void*)0;
		T7_ = ((void*) (T6_));
		if (nimSubInt(((NI) (newSize)), ((NI) (oldSize)), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_34)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_34)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_34)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_34), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		zeroMem__9cLyRtoQz0YlIMEd4qW7Hdgsystem(T7_, ((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_34))));
		alignedDealloc(p, ((NI) (align)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, prepareSeqAdd)(NI len, void* p, NI addlen, NI elemSize, NI elemAlign) {
	void* result;
	NI headerSize;
{	result = (void*)0;
	headerSize = align__vzThvqZajaR9ct9cQ7SOy1tQ(((NI) 4), elemAlign);
	{
		if (!(addlen <= ((NI) 0))) goto LA3_;
		result = p;
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_14;
		if (!(p == NIM_NIL)) goto LA6_;
		if (nimAddInt(len, addlen, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_14)) { raiseOverflow(); goto BeforeRet_;
};
		result = newSeqPayload((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_14), elemSize, elemAlign);
	}
	goto LA1_;
	LA6_: ;
	{
		tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw* p_2;
		NI oldCap;
		NI newCap;
		NI T9_;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_20;
		p_2 = ((tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw*) (p));
		oldCap = (NI)((*p_2).cap & ((NI) -1073741825));
		T9_ = (NI)0;
		T9_ = resize__cOCDWr16YD4j3dBrbbH3yQsystem(oldCap);
		if (nimAddInt(len, addlen, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_20)) { raiseOverflow(); goto BeforeRet_;
};
		newCap = ((T9_ >= (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_20)) ? T9_ : (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_20));
		{
			tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw* q;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_21;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_22;
			void* T14_;
			NI T15_;
			void* T16_;
			NI T17_;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_23;
			if (!((NI)((*p_2).cap & ((NI) 1073741824)) == ((NI) 1073741824))) goto LA12_;
			if (nimMulInt(elemSize, newCap, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_21)) { raiseOverflow(); goto BeforeRet_;
};
			if (nimAddInt(headerSize, (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_21), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_22)) { raiseOverflow(); goto BeforeRet_;
};
			if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_22)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_22)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_22), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			if ((elemAlign) < ((NI) 0) || (elemAlign) > ((NI) 2147483647)){ raiseRangeErrorI(elemAlign, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			T14_ = (void*)0;
			T14_ = alignedAlloc0__YbpLWudJqnECYmKZquJKyw(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_22))), ((NI) (elemAlign)));
			q = ((tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw*) (T14_));
			T15_ = (NI)0;
			T15_ = pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (q)), headerSize);
			T16_ = (void*)0;
			T16_ = ((void*) (T15_));
			T17_ = (NI)0;
			T17_ = pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (p_2)), headerSize);
			if (nimMulInt(len, elemSize, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_23)) { raiseOverflow(); goto BeforeRet_;
};
			if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_23)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_23)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_23), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			copyMem__M04YC71iJg1N7gBF3HZTngsystem(T16_, ((void*) (T17_)), ((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_23))));
			(*q).cap = newCap;
			result = ((void*) (q));
		}
		goto LA10_;
		LA12_: ;
		{
			NI oldSize;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_24;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_25;
			NI newSize;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_26;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_27;
			tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw* q_2;
			void* T19_;
			if (nimMulInt(elemSize, oldCap, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_24)) { raiseOverflow(); goto BeforeRet_;
};
			if (nimAddInt(headerSize, (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_24), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_25)) { raiseOverflow(); goto BeforeRet_;
};
			oldSize = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_25);
			if (nimMulInt(elemSize, newCap, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_26)) { raiseOverflow(); goto BeforeRet_;
};
			if (nimAddInt(headerSize, (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_26), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_27)) { raiseOverflow(); goto BeforeRet_;
};
			newSize = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_27);
			if ((oldSize) < ((NI) 0) || (oldSize) > ((NI) 2147483647)){ raiseRangeErrorI(oldSize, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			if ((newSize) < ((NI) 0) || (newSize) > ((NI) 2147483647)){ raiseRangeErrorI(newSize, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			if ((elemAlign) < ((NI) 0) || (elemAlign) > ((NI) 2147483647)){ raiseRangeErrorI(elemAlign, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			T19_ = (void*)0;
			T19_ = alignedRealloc0__CUuMVCxdCmrsVspc3L8xgw(((void*) (p_2)), ((NI) (oldSize)), ((NI) (newSize)), ((NI) (elemAlign)));
			q_2 = ((tyObject_NimSeqPayloadBase__W32WJdQK8sr3oL2BppHZqw*) (T19_));
			(*q_2).cap = newCap;
			result = ((void*) (q_2));
		}
		LA10_: ;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, add__VHIeeMfqavFfKtbV1Wal0Q)(tySequence__uB9b75OUPRENsBAu4AnoePA* x, tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA value) {
	NI oldLen;
	NI T1_;
	tyObject_NimSeqV2__A9aaPj3Ay2mWlTU3QheYz2w* xu;
	NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_35;
{	T1_ = (*x).len;
	oldLen = T1_;
	xu = ((tyObject_NimSeqV2__A9aaPj3Ay2mWlTU3QheYz2w*) (x));
	{
		NIM_BOOL T4_;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_11;
		void* T8_;
		T4_ = (NIM_BOOL)0;
		T4_ = ((*xu).p == ((tyObject_NimSeqPayload__T3NJfV3Yh9bN9cuVRNI5QtfQ*) NIM_NIL));
		if (T4_) goto LA5_;
		if (nimAddInt(oldLen, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_11)) { raiseOverflow(); goto BeforeRet_;
};
		T4_ = ((*(*xu).p).cap < (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_11));
		LA5_: ;
		if (!T4_) goto LA6_;
		T8_ = (void*)0;
		T8_ = prepareSeqAdd(oldLen, ((void*) ((*xu).p)), ((NI) 1), ((NI) 12), ((NI) 4));
		(*xu).p = ((tyObject_NimSeqPayload__T3NJfV3Yh9bN9cuVRNI5QtfQ*) (T8_));
	}
	LA6_: ;
	if (nimAddInt(oldLen, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_35)) { raiseOverflow(); goto BeforeRet_;
};
	(*xu).len = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_35);
	(*(*xu).p).data[oldLen] = value;
	}BeforeRet_: ;
}
static N_INLINE(void, nimIncRef)(void* p) {
	NI T1_;
	NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_36;
{	T1_ = (NI)0;
	T1_ = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (p)), ((NI) 4));
	if (nimAddInt((*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T1_))).rc, ((NI) 8), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_36)) { raiseOverflow(); goto BeforeRet_;
};
	(*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T1_))).rc = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_36);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___rR9boD7urcxl7uyUtE46AOA)(Exception** dest, Exception* src) {
	{
		if (!src) goto LA3_;
		nimIncRef(src);
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest));
		if (!T7_) goto LA8_;
		nimDestroyAndDispose((*dest));
	}
	LA8_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___rR9boD7urcxl7uyUtE46AOA_2)(Exception** dest, Exception* src) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest));
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest));
	}
	LA4_: ;
	(*dest) = src;
}
static N_INLINE(void, pushCurrentException)(Exception* e) {
	eqcopy___rR9boD7urcxl7uyUtE46AOA(&(*e).up, currException__9bVPeDJlYTi9bQApZpfH8wjg);
	eqsink___rR9boD7urcxl7uyUtE46AOA_2(&currException__9bVPeDJlYTi9bQApZpfH8wjg, e);
}
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionAux__na8C8pUZ9cLQWVwk35l5vfw)(Exception* e) {
{	{
		if (!!((localRaiseHook__EIvMhANBvB9cp2Ezvt29cADg == NIM_NIL))) goto LA3_;
		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = localRaiseHook__EIvMhANBvB9cp2Ezvt29cADg(e);
			if (!!(T7_)) goto LA8_;
			goto BeforeRet_;
		}
		LA8_: ;
	}
	LA3_: ;
	{
		if (!!((globalRaiseHook__JbO1ti4ULxrw54m4zNPbpA == NIM_NIL))) goto LA12_;
		{
			NIM_BOOL T16_;
			T16_ = (NIM_BOOL)0;
			T16_ = globalRaiseHook__JbO1ti4ULxrw54m4zNPbpA(e);
			if (!!(T16_)) goto LA17_;
			goto BeforeRet_;
		}
		LA17_: ;
	}
	LA12_: ;
	{
		if (!!((e == currException__9bVPeDJlYTi9bQApZpfH8wjg))) goto LA21_;
		pushCurrentException(e);
	}
	LA21_: ;
	nimInErrorMode__759bT87luu8XGcbkw13FUjA += ((NI) 1);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line) {
	{
		if (!((*e).name == 0)) goto LA3_;
		(*e).name = ename;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA T11_;
		T7_ = (NIM_BOOL)0;
		T7_ = !((((void*) (procname)) == NIM_NIL));
		if (!(T7_)) goto LA8_;
		T7_ = !((((void*) (filename)) == NIM_NIL));
		LA8_: ;
		if (!T7_) goto LA9_;
		nimZeroMem((void*)(&T11_), sizeof(tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA));
		T11_.procname = procname;
		T11_.filename = filename;
		T11_.line = line;
		add__VHIeeMfqavFfKtbV1Wal0Q((&(*e).trace), T11_);
	}
	LA9_: ;
	raiseExceptionAux__na8C8pUZ9cLQWVwk35l5vfw(e);
}
static N_INLINE(void, sysFatal__Kx89alMoFPpWrEL9bx2cyJVwsystem)(NimStringV2 message) {
	tyObject_RangeDefect__Rp9adJYTsbbIUzQ8fWxwgdA* T2_;
	NimStringV2 blitTmp;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T2_ = (tyObject_RangeDefect__Rp9adJYTsbbIUzQ8fWxwgdA*)0;
	T2_ = (tyObject_RangeDefect__Rp9adJYTsbbIUzQ8fWxwgdA*) nimNewObj(sizeof(tyObject_RangeDefect__Rp9adJYTsbbIUzQ8fWxwgdA), NIM_ALIGNOF(tyObject_RangeDefect__Rp9adJYTsbbIUzQ8fWxwgdA));
	(*T2_).Sup.Sup.Sup.m_type = (&NTIv2__Rp9adJYTsbbIUzQ8fWxwgdA_);
	(*T2_).Sup.Sup.name = "RangeDefect";
	blitTmp = message;
	message.len = 0; message.p = NIM_NIL;
	(*T2_).Sup.Sup.message = blitTmp;
	raiseExceptionEx((Exception*)T2_, "RangeDefect", "sysFatal", "fatal.nim", 49);
	goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&message));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {
{	{
		void* T5_;
		void* T6_;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_39;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_40;
		if (!(((NI) 0) < src.len)) goto LA3_;
		T5_ = (void*)0;
		T5_ = ((void*) ((&(*(*dest).p).data[(*dest).len])));
		T6_ = (void*)0;
		T6_ = ((void*) ((&(*src.p).data[((NI) 0)])));
		if (nimAddInt(src.len, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_39)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_39)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_39)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_39), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(T5_, T6_, ((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_39))));
		if (nimAddInt((*dest).len, src.len, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_40)) { raiseOverflow(); goto BeforeRet_;
};
		(*dest).len = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_40);
	}
	LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space) {
	NimStringV2 result;
{	nimZeroMem((void*)(&result), sizeof(NimStringV2));
	{
		if (!(space <= ((NI) 0))) goto LA3_;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		result.len = ((NI) 0);
		result.p = ((NimStrPayload*) NIM_NIL);
	}
	goto LA1_;
	LA3_: ;
	{
		NimStrPayload* p;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_41;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_42;
		void* T6_;
		if (nimAddInt(space, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_41)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_41), ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_42)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_42)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_42)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_42), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		T6_ = (void*)0;
		T6_ = alloc0Impl__aMIFDISudztFhhVWVqortg(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_42))));
		p = ((NimStrPayload*) (T6_));
		(*p).cap = space;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		result.len = ((NI) 0);
		result.p = p;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen) {
	NI newLen;
	NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_43;
{	if (nimAddInt((*s).len, addlen, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_43)) { raiseOverflow(); goto BeforeRet_;
};
	newLen = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_43);
	{
		NIM_BOOL T3_;
		NimStrPayload* oldP;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_44;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_45;
		void* T7_;
		T3_ = (NIM_BOOL)0;
		T3_ = ((*s).p == ((NimStrPayload*) NIM_NIL));
		if (T3_) goto LA4_;
		T3_ = ((NI)((*(*s).p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
		LA4_: ;
		if (!T3_) goto LA5_;
		oldP = (*s).p;
		if (nimAddInt(newLen, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_44)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_44), ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_45)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_45)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_45)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_45), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		T7_ = (void*)0;
		T7_ = alloc0Impl__aMIFDISudztFhhVWVqortg(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_45))));
		(*s).p = ((NimStrPayload*) (T7_));
		(*(*s).p).cap = newLen;
		{
			void* T12_;
			if (!(((NI) 0) < (*s).len)) goto LA10_;
			T12_ = (void*)0;
			T12_ = ((void*) ((&(*(*s).p).data[((NI) 0)])));
			if (((((*s).len <= newLen) ? (*s).len : newLen)) < ((NI) 0) || ((((*s).len <= newLen) ? (*s).len : newLen)) > ((NI) 2147483647)){ raiseRangeErrorI((((*s).len <= newLen) ? (*s).len : newLen), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			copyMem__M04YC71iJg1N7gBF3HZTngsystem(T12_, ((void*) ((&(*oldP).data[((NI) 0)]))), ((NI) ((((*s).len <= newLen) ? (*s).len : newLen))));
		}
		LA10_: ;
	}
	goto LA1_;
	LA5_: ;
	{
		NI oldCap;
		oldCap = (NI)((*(*s).p).cap & ((NI) -1073741825));
		{
			NI newCap;
			NI T18_;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_46;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_47;
			NI T19_;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_48;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_49;
			void* T20_;
			if (!(oldCap < newLen)) goto LA16_;
			T18_ = (NI)0;
			T18_ = resize__cOCDWr16YD4j3dBrbbH3yQsystem(oldCap);
			newCap = ((newLen >= T18_) ? newLen : T18_);
			if (nimAddInt(oldCap, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_46)) { raiseOverflow(); goto BeforeRet_;
};
			if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_46), ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_47)) { raiseOverflow(); goto BeforeRet_;
};
			if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_47)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_47)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_47), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			T19_ = (NI)0;
			T19_ = ((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_47)));
			if (nimAddInt(newCap, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_48)) { raiseOverflow(); goto BeforeRet_;
};
			if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_48), ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_49)) { raiseOverflow(); goto BeforeRet_;
};
			if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_49)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_49)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_49), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			T20_ = (void*)0;
			T20_ = realloc0Impl__Jvtux8Lvp7XxQp3KVEEn5A(((void*) ((*s).p)), T19_, ((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_49))));
			(*s).p = ((NimStrPayload*) (T20_));
			(*(*s).p).cap = newCap;
		}
		LA16_: ;
	}
	LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen) {
{	{
		if (!(newLen == ((NI) 0))) goto LA3_;
	}
	goto LA1_;
	LA3_: ;
	{
		{
			NIM_BOOL T8_;
			NIM_BOOL T10_;
			NimStringV2* T14_;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_50;
			T8_ = (NIM_BOOL)0;
			T8_ = ((*s).len < newLen);
			if (T8_) goto LA9_;
			T10_ = (NIM_BOOL)0;
			T10_ = ((*s).p == ((NimStrPayload*) NIM_NIL));
			if (T10_) goto LA11_;
			T10_ = ((NI)((*(*s).p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
			LA11_: ;
			T8_ = T10_;
			LA9_: ;
			if (!T8_) goto LA12_;
			T14_ = (NimStringV2*)0;
			T14_ = s;
			if (nimSubInt(newLen, (*s).len, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_50)) { raiseOverflow(); goto BeforeRet_;
};
			prepareAdd(T14_, (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_50));
		}
		LA12_: ;
		(*(*s).p).data[newLen] = 0;
	}
	LA1_: ;
	(*s).len = newLen;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__C0YoABEefTaYbWLv9aVOzZA)(NimStringV2* s) {
	NimStrPayload* oldP;
	NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_51;
	NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_52;
	void* T1_;
	void* T2_;
	NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_53;
{	oldP = (*s).p;
	if (nimAddInt((*s).len, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_51)) { raiseOverflow(); goto BeforeRet_;
};
	if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_51), ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_52)) { raiseOverflow(); goto BeforeRet_;
};
	if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_52)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_52)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_52), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	T1_ = (void*)0;
	T1_ = alloc0Impl__aMIFDISudztFhhVWVqortg(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_52))));
	(*s).p = ((NimStrPayload*) (T1_));
	(*(*s).p).cap = (*s).len;
	T2_ = (void*)0;
	T2_ = ((void*) ((&(*(*s).p).data[((NI) 0)])));
	if (nimAddInt((*s).len, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_53)) { raiseOverflow(); goto BeforeRet_;
};
	if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_53)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_53)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_53), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	copyMem__M04YC71iJg1N7gBF3HZTngsystem(T2_, ((void*) ((&(*oldP).data[((NI) 0)]))), ((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_53))));
	}BeforeRet_: ;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s).p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__C0YoABEefTaYbWLv9aVOzZA(s);
	}
	LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, addInt__mftMOxbyu0h4yByfs3sqjA)(NimStringV2* result, NI64 x) {
	NI base;
	NI i;
	NI64 y;
	base = (*result).len;
	setLengthStrV2((&(*result)), ((NI) ((NI)(base + ((NI) 32)))));
	i = ((NI) 0);
	y = x;
	{
		while (1) {
			NI64 d;
			d = (NI64)(y / IL64(10));
			nimPrepareStrMutationV2((&(*result)));
			(*result).p->data[(NI)(base + i)] = ((NIM_CHAR) (((NI) ((NI)((((NI) ((NI64)(y - (NI64)(d * IL64(10))))) > 0? (((NI) ((NI64)(y - (NI64)(d * IL64(10)))))) : -(((NI) ((NI64)(y - (NI64)(d * IL64(10))))))) + ((NI) 48))))));
			i += ((NI) 1);
			y = d;
			{
				if (!(y == IL64(0))) goto LA5_;
				goto LA1;
			}
			LA5_: ;
		}
	} LA1: ;
	{
		if (!(x < IL64(0))) goto LA9_;
		nimPrepareStrMutationV2((&(*result)));
		(*result).p->data[(NI)(base + i)] = 45;
		i += ((NI) 1);
	}
	LA9_: ;
	setLengthStrV2((&(*result)), ((NI) ((NI)(base + i))));
	{
		NI j;
		NI colontmp_;
		NI res;
		j = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)((NI)(i / ((NI) 2)) - ((NI) 1));
		res = ((NI) 0);
		{
			while (1) {
				NIM_CHAR T14_;
				if (!(res <= colontmp_)) goto LA13;
				j = res;
				nimPrepareStrMutationV2((&(*result)));
				nimPrepareStrMutationV2((&(*result)));
				T14_ = (NIM_CHAR)0;
				T14_ = (*result).p->data[(NI)(base + j)];
				(*result).p->data[(NI)(base + j)] = (*result).p->data[(NI)((NI)((NI)(base + i) - j) - ((NI) 1))];
				(*result).p->data[(NI)((NI)((NI)(base + i) - j) - ((NI) 1))] = T14_;
				res += ((NI) 1);
			} LA13: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimInt64ToStr)(NI64 x) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	result = rawNewString(((NI) 32));
	addInt__mftMOxbyu0h4yByfs3sqjA((&result), x);
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 colontmpD__3;
	NimStringV2 T1_;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	colontmpD_ = nimInt64ToStr(i);
	colontmpD__2 = nimInt64ToStr(a);
	colontmpD__3 = nimInt64ToStr(b);
	T1_ = rawNewString(colontmpD_.len + colontmpD__2.len + colontmpD__3.len + 31);
appendString((&T1_), TM__Q5wkpxktOdTGvlSRo9bzt9aw_38);
appendString((&T1_), colontmpD_);
appendString((&T1_), TM__Q5wkpxktOdTGvlSRo9bzt9aw_55);
appendString((&T1_), colontmpD__2);
appendString((&T1_), TM__Q5wkpxktOdTGvlSRo9bzt9aw_57);
appendString((&T1_), colontmpD__3);
	sysFatal__Kx89alMoFPpWrEL9bx2cyJVwsystem(T1_);
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__3));
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__2));
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
}
N_LIB_PRIVATE N_NIMCALL(void*, alignedAlloc0__YbpLWudJqnECYmKZquJKyw)(NI size, NI align) {
	void* result;
{	result = (void*)0;
	{
		if (!(((NI) (align)) <= ((NI) 8))) goto LA3_;
		result = alloc0Impl__aMIFDISudztFhhVWVqortg(size);
	}
	goto LA1_;
	LA3_: ;
	{
		void* base;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_7;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_8;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_9;
		NI offset;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_58;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_59;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_60;
		NI T6_;
		NI T7_;
		if (nimAddInt(((NI) (size)), ((NI) (align)), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_7)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimSubInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_7), ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_8)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_8), ((NI) 2), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_9)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_9)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_9)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_9), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		base = alloc0Impl__aMIFDISudztFhhVWVqortg(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_9))));
		if (nimSubInt(((NI) (align)), ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_58)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimSubInt(((NI) (align)), (NI)(((NI) (ptrdiff_t) (base)) & (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_58)), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_59)) { raiseOverflow(); goto BeforeRet_;
};
		offset = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_59);
		if (nimSubInt(offset, ((NI) 2), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_60)) { raiseOverflow(); goto BeforeRet_;
};
		T6_ = (NI)0;
		T6_ = pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (base)), (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_60));
		(*((NU16*) (((void*) (T6_))))) = ((NU16) (offset));
		T7_ = (NI)0;
		T7_ = pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (base)), offset);
		result = ((void*) (T7_));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment) {
	void* result;
	NI hdrSize;
	NI s;
	NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_6;
	void* T1_;
	NI T2_;
{	result = (void*)0;
	hdrSize = align__vzThvqZajaR9ct9cQ7SOy1tQ(((NI) 4), alignment);
	if (nimAddInt(size, hdrSize, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_6)) { raiseOverflow(); goto BeforeRet_;
};
	s = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_6);
	if ((s) < ((NI) 0) || (s) > ((NI) 2147483647)){ raiseRangeErrorI(s, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	if ((alignment) < ((NI) 0) || (alignment) > ((NI) 2147483647)){ raiseRangeErrorI(alignment, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	T1_ = (void*)0;
	T1_ = alignedAlloc0__YbpLWudJqnECYmKZquJKyw(((NI) (s)), ((NI) (alignment)));
	T2_ = (NI)0;
	T2_ = pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (T1_)), hdrSize);
	result = ((void*) (T2_));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___iXyOdhIrs6C9bvzrDNqxI2g)(tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ* dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest).Sup.Sup.Sup.parent);
	}
	LA4_: ;
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).Sup.Sup.Sup.message));
	eqdestroy___4fQQqvAqifkWGVa4g39cI5A((&(*dest).Sup.Sup.Sup.trace));
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest).Sup.Sup.Sup.up);
	}
	LA9_: ;
}
static N_INLINE(void, sysFatal__pO9abt7E7FWB3DInHeLgZeQsystem)(NimStringV2 message) {
	tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ* T2_;
	NimStringV2 blitTmp;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T2_ = (tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ*)0;
	T2_ = (tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ*) nimNewObj(sizeof(tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ), NIM_ALIGNOF(tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ));
	(*T2_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__9cxMi1BPLc3UKt9br86bGfGQ_);
	(*T2_).Sup.Sup.Sup.name = "OverflowDefect";
	blitTmp = message;
	message.len = 0; message.p = NIM_NIL;
	(*T2_).Sup.Sup.Sup.message = blitTmp;
	raiseExceptionEx((Exception*)T2_, "OverflowDefect", "sysFatal", "fatal.nim", 49);
	goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&message));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void) {
	sysFatal__pO9abt7E7FWB3DInHeLgZeQsystem(TM__Q5wkpxktOdTGvlSRo9bzt9aw_62);
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toNimStr)(NCSTRING str, NI len) {
	NimStringV2 result;
{	nimZeroMem((void*)(&result), sizeof(NimStringV2));
	{
		if (!(len <= ((NI) 0))) goto LA3_;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		result.len = ((NI) 0);
		result.p = ((NimStrPayload*) NIM_NIL);
	}
	goto LA1_;
	LA3_: ;
	{
		NI colontmpD_;
		NimStrPayload* p;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_2;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_63;
		void* T6_;
		colontmpD_ = (NI)0;
		if (nimAddInt(len, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_2)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_2), ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_63)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_63)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_63)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_63), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		T6_ = (void*)0;
		T6_ = alloc0Impl__aMIFDISudztFhhVWVqortg(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_63))));
		p = ((NimStrPayload*) (T6_));
		(*p).cap = len;
		{
			if (!(((NI) 0) < len)) goto LA9_;
			if ((len) < ((NI) 0) || (len) > ((NI) 2147483647)){ raiseRangeErrorI(len, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			copyMem__M04YC71iJg1N7gBF3HZTngsystem(((void*) ((&(*p).data[((NI) 0)]))), ((void*) (str)), ((NI) (len)));
		}
		LA9_: ;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		colontmpD_ = len;
		result.len = colontmpD_;
		result.p = p;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, nimCStrLen)(NCSTRING a) {
	NI result;
	size_t T1_;
	result = (NI)0;
	T1_ = (size_t)0;
	T1_ = strlen(a);
	result = ((NI) (T1_));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	nimZeroMem((void*)(&result), sizeof(NimStringV2));
	nimZeroMem((void*)(&colontmpD_), sizeof(NimStringV2));
	nimZeroMem((void*)(&colontmpD__2), sizeof(NimStringV2));
	{
		if (!(((void*) (str)) == NIM_NIL)) goto LA3_;
		colontmpD_ = toNimStr(str, ((NI) 0));
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		NCSTRING T6_;
		T6_ = (NCSTRING)0;
		T6_ = str;
		colontmpD__2 = toNimStr(T6_, (str ? nimCStrLen(str) : 0));
		result = colontmpD__2;
	}
	LA1_: ;
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___rR9boD7urcxl7uyUtE46AOA(&currException__9bVPeDJlYTi9bQApZpfH8wjg, (*currException__9bVPeDJlYTi9bQApZpfH8wjg).up);
}
static N_INLINE(void, rawWrite)(FILE* f, NCSTRING s) {
	void* T1_;
	int T2_;
	int T3_;
	T1_ = (void*)0;
	T1_ = ((void*) (s));
	T2_ = (int)0;
	T2_ = fwrite(T1_, ((size_t) 1), ((size_t) ((s ? nimCStrLen(s) : 0))), f);
	(void)(T2_);
	T3_ = (int)0;
	T3_ = fflush(f);
	(void)(T3_);
}
N_LIB_PRIVATE N_NIMCALL(void, writeToStdErr__a2kDfqdSc1eYf0ZCWOGinQ)(NCSTRING msg) {
	rawWrite(stderr, msg);
}
N_LIB_PRIVATE N_NIMCALL(void, showErrorMessage__zsORN9crdKxsL9cHrQcdHSMw)(NCSTRING data) {
	NIM_BOOL toWrite;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	toWrite = NIM_TRUE;
	{
		NimStringV2 colontmpD_;
		if (!!((errorMessageWriter__ZXnv0JyrWe3HTd07wpSr7A == NIM_NIL))) goto LA3_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD_ = cstrToNimstr(data);
		errorMessageWriter__ZXnv0JyrWe3HTd07wpSr7A(colontmpD_);
		toWrite = NIM_FALSE;
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD_));
		if (NIM_UNLIKELY(*nimErr_)) {
			LA5_:;
			{
				*nimErr_ = NIM_FALSE;
				popCurrentException();
				LA7_:;
			}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	LA3_: ;
	{
		if (!toWrite) goto LA11_;
		writeToStdErr__a2kDfqdSc1eYf0ZCWOGinQ(data);
	}
	LA11_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NOCONV(void, signalHandler)(int sign) {
	NCSTRING msg;
	msg = (NCSTRING)0;
	{
		if (!(sign == SIGINT)) goto LA3_;
		msg = "SIGINT: Interrupted by Ctrl-C.\012";
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(sign == SIGSEGV)) goto LA6_;
		msg = "SIGSEGV: Illegal storage access. (Attempt to read from nil\?)\012";
	}
	goto LA1_;
	LA6_: ;
	{
		if (!(sign == SIGABRT)) goto LA9_;
		msg = "SIGABRT: Abnormal termination.\012";
	}
	goto LA1_;
	LA9_: ;
	{
		if (!(sign == SIGFPE)) goto LA12_;
		msg = "SIGFPE: Arithmetic error.\012";
	}
	goto LA1_;
	LA12_: ;
	{
		if (!(sign == SIGILL)) goto LA15_;
		msg = "SIGILL: Illegal operation.\012";
	}
	goto LA1_;
	LA15_: ;
	{
		if (!NIM_FALSE) goto LA18_;
		msg = "SIGBUS: Illegal storage access. (Attempt to read from nil\?)\012";
	}
	goto LA1_;
	LA18_: ;
	{
		{
			msg = "unknown signal\012";
		}
	}
	LA1_: ;
	showErrorMessage__zsORN9crdKxsL9cHrQcdHSMw(msg);
	exit(((NI) 1));
}
N_LIB_PRIVATE N_NIMCALL(void, registerSignalHandler__amVlU9ajqZ06ujoesRBHcDg)(void) {
	tyProc__ZEo3s9cIqJYP74f7GMZM2FA T1_;
	tyProc__ZEo3s9cIqJYP74f7GMZM2FA T2_;
	tyProc__ZEo3s9cIqJYP74f7GMZM2FA T3_;
	tyProc__ZEo3s9cIqJYP74f7GMZM2FA T4_;
	tyProc__ZEo3s9cIqJYP74f7GMZM2FA T5_;
	T1_ = (tyProc__ZEo3s9cIqJYP74f7GMZM2FA)0;
	T1_ = signal(SIGINT, signalHandler);
	T2_ = (tyProc__ZEo3s9cIqJYP74f7GMZM2FA)0;
	T2_ = signal(SIGSEGV, signalHandler);
	T3_ = (tyProc__ZEo3s9cIqJYP74f7GMZM2FA)0;
	T3_ = signal(SIGABRT, signalHandler);
	T4_ = (tyProc__ZEo3s9cIqJYP74f7GMZM2FA)0;
	T4_ = signal(SIGFPE, signalHandler);
	T5_ = (tyProc__ZEo3s9cIqJYP74f7GMZM2FA)0;
	T5_ = signal(SIGILL, signalHandler);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___qRVWt3jIAyom1VkyIWI7tA)(tyObject_IndexDefect__n6tGEPHKkh7E1AP9bj30WrQ* dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest).Sup.Sup.parent);
	}
	LA4_: ;
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).Sup.Sup.message));
	eqdestroy___4fQQqvAqifkWGVa4g39cI5A((&(*dest).Sup.Sup.trace));
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest).Sup.Sup.up);
	}
	LA9_: ;
}
static N_INLINE(void, sysFatal__BVaWgkQV7bsZ7qgkYxa9a0Asystem)(NimStringV2 message) {
	tyObject_IndexDefect__n6tGEPHKkh7E1AP9bj30WrQ* T2_;
	NimStringV2 blitTmp;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T2_ = (tyObject_IndexDefect__n6tGEPHKkh7E1AP9bj30WrQ*)0;
	T2_ = (tyObject_IndexDefect__n6tGEPHKkh7E1AP9bj30WrQ*) nimNewObj(sizeof(tyObject_IndexDefect__n6tGEPHKkh7E1AP9bj30WrQ), NIM_ALIGNOF(tyObject_IndexDefect__n6tGEPHKkh7E1AP9bj30WrQ));
	(*T2_).Sup.Sup.Sup.m_type = (&NTIv2__n6tGEPHKkh7E1AP9bj30WrQ_);
	(*T2_).Sup.Sup.name = "IndexDefect";
	blitTmp = message;
	message.len = 0; message.p = NIM_NIL;
	(*T2_).Sup.Sup.message = blitTmp;
	raiseExceptionEx((Exception*)T2_, "IndexDefect", "sysFatal", "fatal.nim", 49);
	goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&message));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimIntToStr)(NI x) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	result = rawNewString(((NI) 16));
	addInt__mftMOxbyu0h4yByfs3sqjA((&result), ((NI64) (x)));
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n) {
	NimStringV2 colontmpD_;
	NimStringV2 colontmpD__2;
	NimStringV2 T1_;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
	T1_.len = 0; T1_.p = NIM_NIL;
	{
		NimStringV2 blitTmp;
		if (!(n < ((NI) 0))) goto LA4_;
		colontmpD_ = TM__Q5wkpxktOdTGvlSRo9bzt9aw_65;
		blitTmp = colontmpD_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		T1_ = blitTmp;
	}
	goto LA2_;
	LA4_: ;
	{
		NimStringV2 colontmpD__3;
		NimStringV2 colontmpD__4;
		NimStringV2 T7_;
		NimStringV2 blitTmp_2;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
		T7_.len = 0; T7_.p = NIM_NIL;
		colontmpD__3 = nimIntToStr(i);
		colontmpD__4 = nimIntToStr(n);
		T7_ = rawNewString(colontmpD__3.len + colontmpD__4.len + 19);
appendString((&T7_), TM__Q5wkpxktOdTGvlSRo9bzt9aw_67);
appendString((&T7_), colontmpD__3);
appendString((&T7_), TM__Q5wkpxktOdTGvlSRo9bzt9aw_69);
appendString((&T7_), colontmpD__4);
		colontmpD__2 = T7_;
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__4));
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&colontmpD__3));
		blitTmp_2 = colontmpD__2;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		T1_ = blitTmp_2;
	}
	LA2_: ;
	sysFatal__BVaWgkQV7bsZ7qgkYxa9a0Asystem(T1_);
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___sUPxfcqVijR0WN3SH4QQ6A)(tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ* dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest).Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest).Sup.Sup.parent);
	}
	LA4_: ;
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).Sup.Sup.message));
	eqdestroy___4fQQqvAqifkWGVa4g39cI5A((&(*dest).Sup.Sup.trace));
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest).Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest).Sup.Sup.up);
	}
	LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nimAsgnStrV2)(NimStringV2* a, NimStringV2 b) {
{	{
		if (!((*a).p == b.p)) goto LA3_;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (b.p == ((NimStrPayload*) NIM_NIL));
		if (T7_) goto LA8_;
		T7_ = ((NI)((*b.p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
		LA8_: ;
		if (!T7_) goto LA9_;
		{
			NIM_BOOL T13_;
			T13_ = (NIM_BOOL)0;
			T13_ = ((*a).p == ((NimStrPayload*) NIM_NIL));
			if (T13_) goto LA14_;
			T13_ = ((NI)((*(*a).p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
			LA14_: ;
			if (!!(T13_)) goto LA15_;
			dealloc(((void*) ((*a).p)));
		}
		LA15_: ;
		(*a).len = b.len;
		(*a).p = b.p;
	}
	goto LA5_;
	LA9_: ;
	{
		void* T33_;
		void* T34_;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_72;
		{
			NIM_BOOL T20_;
			NIM_BOOL T21_;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_70;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_71;
			void* T32_;
			T20_ = (NIM_BOOL)0;
			T21_ = (NIM_BOOL)0;
			T21_ = ((*a).p == ((NimStrPayload*) NIM_NIL));
			if (T21_) goto LA22_;
			T21_ = ((NI)((*(*a).p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
			LA22_: ;
			T20_ = T21_;
			if (T20_) goto LA23_;
			T20_ = ((NI)((*(*a).p).cap & ((NI) -1073741825)) < b.len);
			LA23_: ;
			if (!T20_) goto LA24_;
			{
				NIM_BOOL T28_;
				T28_ = (NIM_BOOL)0;
				T28_ = ((*a).p == ((NimStrPayload*) NIM_NIL));
				if (T28_) goto LA29_;
				T28_ = ((NI)((*(*a).p).cap & ((NI) 1073741824)) == ((NI) 1073741824));
				LA29_: ;
				if (!!(T28_)) goto LA30_;
				dealloc(((void*) ((*a).p)));
			}
			LA30_: ;
			if (nimAddInt(b.len, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_70)) { raiseOverflow(); goto BeforeRet_;
};
			if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_70), ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_71)) { raiseOverflow(); goto BeforeRet_;
};
			if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_71)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_71)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_71), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
			T32_ = (void*)0;
			T32_ = alloc0Impl__aMIFDISudztFhhVWVqortg(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_71))));
			(*a).p = ((NimStrPayload*) (T32_));
			(*(*a).p).cap = b.len;
		}
		LA24_: ;
		(*a).len = b.len;
		T33_ = (void*)0;
		T33_ = ((void*) ((&(*(*a).p).data[((NI) 0)])));
		T34_ = (void*)0;
		T34_ = ((void*) ((&(*b.p).data[((NI) 0)])));
		if (nimAddInt(b.len, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_72)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_72)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_72)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_72), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		copyMem__M04YC71iJg1N7gBF3HZTngsystem(T33_, T34_, ((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_72))));
	}
	LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___aBBXmHFBEivKqERloP6zmA)(NimStringV2* dest, NimStringV2 src) {
	nimAsgnStrV2(dest, src);
}
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObjUninit)(NI size, NI alignment) {
	void* result;
	NI hdrSize;
	NI s;
	NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_73;
	void* T1_;
	NI T2_;
	NI T3_;
{	result = (void*)0;
	hdrSize = align__vzThvqZajaR9ct9cQ7SOy1tQ(((NI) 4), alignment);
	if (nimAddInt(size, hdrSize, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_73)) { raiseOverflow(); goto BeforeRet_;
};
	s = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_73);
	if ((s) < ((NI) 0) || (s) > ((NI) 2147483647)){ raiseRangeErrorI(s, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	if ((alignment) < ((NI) 0) || (alignment) > ((NI) 2147483647)){ raiseRangeErrorI(alignment, ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
	T1_ = (void*)0;
	T1_ = alignedAlloc__YbpLWudJqnECYmKZquJKyw_2(((NI) (s)), ((NI) (alignment)));
	T2_ = (NI)0;
	T2_ = pluspercent___dgYAo7RfdUVVpvkfKDym8wsystem(((NI) (ptrdiff_t) (T1_)), hdrSize);
	result = ((void*) (((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (((void*) (T2_))))));
	T3_ = (NI)0;
	T3_ = minuspercent___dgYAo7RfdUVVpvkfKDym8w_2system(((NI) (ptrdiff_t) (result)), ((NI) 4));
	(*((tyObject_RefHeader__Gi7WQzlT1ZRToh9a2ueYb4A*) (T3_))).rc = ((NI) 0);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, add__GzUH6O0SjRuWHzfOn1f8Tw)(tySequence__edypeVHoNy9czAu9cukTSm3Q* x, tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w value) {
	NI oldLen;
	NI T1_;
	tyObject_NimSeqV2__Cznlc9aNZHkrRortstTd5dA* xu;
	NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_75;
{	T1_ = (*x).len;
	oldLen = T1_;
	xu = ((tyObject_NimSeqV2__Cznlc9aNZHkrRortstTd5dA*) (x));
	{
		NIM_BOOL T4_;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_74;
		void* T8_;
		T4_ = (NIM_BOOL)0;
		T4_ = ((*xu).p == ((tyObject_NimSeqPayload__vzeUId7VpZgOxblQgrHNLA*) NIM_NIL));
		if (T4_) goto LA5_;
		if (nimAddInt(oldLen, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_74)) { raiseOverflow(); goto BeforeRet_;
};
		T4_ = ((*(*xu).p).cap < (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_74));
		LA5_: ;
		if (!T4_) goto LA6_;
		T8_ = (void*)0;
		T8_ = prepareSeqAdd(oldLen, ((void*) ((*xu).p)), ((NI) 1), ((NI) 1), ((NI) 1));
		(*xu).p = ((tyObject_NimSeqPayload__vzeUId7VpZgOxblQgrHNLA*) (T8_));
	}
	LA6_: ;
	if (nimAddInt(oldLen, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_75)) { raiseOverflow(); goto BeforeRet_;
};
	(*xu).len = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_75);
	(*(*xu).p).data[oldLen] = value;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w, max__uzMVnGTMOUt5oPTqbZlJ8w)(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w* x, NI xLen_0) {
	tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w result;
{	result = (tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w)0;
	if ((NU)(((NI) 0)) >= (NU)(xLen_0)){ raiseIndexError2(((NI) 0),xLen_0-1); goto BeforeRet_;
}
	result = x[((NI) 0)];
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (xLen_0-1);
		res = ((NI) 1);
		{
			while (1) {
				NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_76;
				if (!(res <= colontmp_)) goto LA3;
				i = res;
				{
					if ((NU)(i) >= (NU)(xLen_0)){ raiseIndexError2(i,xLen_0-1); goto BeforeRet_;
}
					if (!(result < x[i])) goto LA6_;
					if ((NU)(i) >= (NU)(xLen_0)){ raiseIndexError2(i,xLen_0-1); goto BeforeRet_;
}
					result = x[i];
				}
				LA6_: ;
				if (nimAddInt(res, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_76)) { raiseOverflow(); goto BeforeRet_;
};
				res = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_76);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void*, seqToPtr__OWrcycNEyUUgue13ItpQvgsystem)(tySequence__edypeVHoNy9czAu9cukTSm3Q x) {
	void* result;
	union { tySequence__edypeVHoNy9czAu9cukTSm3Q source; tyObject_NimSeqV2__Cznlc9aNZHkrRortstTd5dA dest; } LOC1;
	result = (void*)0;
	LOC1.source = x;
	result = ((void*) (LOC1.dest.p));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___DSAPP3F10saUnzfSrl2Q2A)(tySequence__edypeVHoNy9czAu9cukTSm3Q x, tySequence__edypeVHoNy9czAu9cukTSm3Q y) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		void* T3_;
		void* T4_;
		T3_ = (void*)0;
		T3_ = seqToPtr__OWrcycNEyUUgue13ItpQvgsystem(x);
		T4_ = (void*)0;
		T4_ = seqToPtr__OWrcycNEyUUgue13ItpQvgsystem(y);
		if (!(T3_ == T4_)) goto LA5_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA5_: ;
	{
		NI T9_;
		NI T10_;
		T9_ = x.len;
		T10_ = y.len;
		if (!!((T9_ == T10_))) goto LA11_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA11_: ;
	{
		NI i;
		NI colontmp_;
		NI T14_;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_77;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T14_ = x.len;
		if (nimSubInt(T14_, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_77)) { raiseOverflow(); goto BeforeRet_;
};
		colontmp_ = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_77);
		res = ((NI) 0);
		{
			while (1) {
				NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_78;
				if (!(res <= colontmp_)) goto LA16;
				i = res;
				{
					if ((NU)(i) >= (NU)x.len){ raiseIndexError2(i,x.len-1); goto BeforeRet_;
}
					if ((NU)(i) >= (NU)y.len){ raiseIndexError2(i,y.len-1); goto BeforeRet_;
}
					if (!!((x.p->data[i] == y.p->data[i]))) goto LA19_;
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA19_: ;
				if (nimAddInt(res, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_78)) { raiseOverflow(); goto BeforeRet_;
};
				res = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_78);
			} LA16: ;
		}
	}
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, add__lY5DLRz4X2A2isf2LBd6tQ)(tySequence__9bAGqSvkAaFL9bWjsEPslrFA* x, NU32 value) {
	NI oldLen;
	NI T1_;
	tyObject_NimSeqV2__fPXN5kjvqQrQGq2BBQ9anlw* xu;
	NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_80;
{	T1_ = (*x).len;
	oldLen = T1_;
	xu = ((tyObject_NimSeqV2__fPXN5kjvqQrQGq2BBQ9anlw*) (x));
	{
		NIM_BOOL T4_;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_79;
		void* T8_;
		T4_ = (NIM_BOOL)0;
		T4_ = ((*xu).p == ((tyObject_NimSeqPayload__ZR3g9axPGBSEUI126QLYUIg*) NIM_NIL));
		if (T4_) goto LA5_;
		if (nimAddInt(oldLen, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_79)) { raiseOverflow(); goto BeforeRet_;
};
		T4_ = ((*(*xu).p).cap < (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_79));
		LA5_: ;
		if (!T4_) goto LA6_;
		T8_ = (void*)0;
		T8_ = prepareSeqAdd(oldLen, ((void*) ((*xu).p)), ((NI) 1), ((NI) 4), ((NI) 4));
		(*xu).p = ((tyObject_NimSeqPayload__ZR3g9axPGBSEUI126QLYUIg*) (T8_));
	}
	LA6_: ;
	if (nimAddInt(oldLen, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_80)) { raiseOverflow(); goto BeforeRet_;
};
	(*xu).len = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_80);
	(*(*xu).p).data[oldLen] = value;
	}BeforeRet_: ;
}
static N_INLINE(void*, seqToPtr__b4bBbdZpDc9bTWf9bgTld08Asystem)(tySequence__9bAGqSvkAaFL9bWjsEPslrFA x) {
	void* result;
	union { tySequence__9bAGqSvkAaFL9bWjsEPslrFA source; tyObject_NimSeqV2__fPXN5kjvqQrQGq2BBQ9anlw dest; } LOC1;
	result = (void*)0;
	LOC1.source = x;
	result = ((void*) (LOC1.dest.p));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___xG9c4bgU9bPyp4lp8VsxF5Sw)(tySequence__9bAGqSvkAaFL9bWjsEPslrFA x, tySequence__9bAGqSvkAaFL9bWjsEPslrFA y) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		void* T3_;
		void* T4_;
		T3_ = (void*)0;
		T3_ = seqToPtr__b4bBbdZpDc9bTWf9bgTld08Asystem(x);
		T4_ = (void*)0;
		T4_ = seqToPtr__b4bBbdZpDc9bTWf9bgTld08Asystem(y);
		if (!(T3_ == T4_)) goto LA5_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA5_: ;
	{
		NI T9_;
		NI T10_;
		T9_ = x.len;
		T10_ = y.len;
		if (!!((T9_ == T10_))) goto LA11_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA11_: ;
	{
		NI i;
		NI colontmp_;
		NI T14_;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_81;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T14_ = x.len;
		if (nimSubInt(T14_, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_81)) { raiseOverflow(); goto BeforeRet_;
};
		colontmp_ = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_81);
		res = ((NI) 0);
		{
			while (1) {
				NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_82;
				if (!(res <= colontmp_)) goto LA16;
				i = res;
				{
					if ((NU)(i) >= (NU)x.len){ raiseIndexError2(i,x.len-1); goto BeforeRet_;
}
					if ((NU)(i) >= (NU)y.len){ raiseIndexError2(i,y.len-1); goto BeforeRet_;
}
					if (!!((x.p->data[i] == y.p->data[i]))) goto LA19_;
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA19_: ;
				if (nimAddInt(res, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_82)) { raiseOverflow(); goto BeforeRet_;
};
				res = (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_82);
			} LA16: ;
		}
	}
	result = NIM_TRUE;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___GdYovzyz9cvmRV9aK4h9a2piA)(tySequence__9bAGqSvkAaFL9bWjsEPslrFA* dest) {
	NI colontmp_;
	colontmp_ = ((NI) 0);
	{
		while (1) {
			NI T3_;
			T3_ = (*dest).len;
			if (!(colontmp_ < T3_)) goto LA2;
			colontmp_ += ((NI) 1);
		} LA2: ;
	}
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc((*dest).p, NIM_ALIGNOF(NU32));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___IlJSuVMKrFhfOcKQWcYQXQ)(tySequence__edypeVHoNy9czAu9cukTSm3Q* dest) {
	NI colontmp_;
	colontmp_ = ((NI) 0);
	{
		while (1) {
			NI T3_;
			T3_ = (*dest).len;
			if (!(colontmp_ < T3_)) goto LA2;
			colontmp_ += ((NI) 1);
		} LA2: ;
	}
	if ((*dest).p && !((*dest).p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc((*dest).p, NIM_ALIGNOF(tyEnum_EEPROM_Pins__qTgGTcbQ5wyEhl7Wbivu3w));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___vttz8U9aaHVcOkTLV69bskjQ)(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag* dest) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest).Sup.Sup.Sup.parent);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose((*dest).Sup.Sup.Sup.parent);
	}
	LA4_: ;
	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&(*dest).Sup.Sup.Sup.message));
	eqdestroy___4fQQqvAqifkWGVa4g39cI5A((&(*dest).Sup.Sup.Sup.trace));
	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = nimDecRefIsLast((*dest).Sup.Sup.Sup.up);
		if (!T8_) goto LA9_;
		nimDestroyAndDispose((*dest).Sup.Sup.Sup.up);
	}
	LA9_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, shrink__YjMr9cTZ2znYg9aJTDqDzgvg)(tySequence__XMerIiAQb66xYd9a9cuy80SQ* x, NI newLen) {
	(*((tyObject_NimSeqV2__VABqGxoJY4QkZ9cJjT9cJTLw*) (x))).len = ((NI) (newLen));
}
N_LIB_PRIVATE N_NIMCALL(void, setLen__y5G129bGEFh1qNKyeVIxRtg)(tySequence__XMerIiAQb66xYd9a9cuy80SQ* s, NI newlen) {
{	{
		NI T3_;
		T3_ = (*s).len;
		if (!(((NI) (newlen)) < T3_)) goto LA4_;
		shrink__YjMr9cTZ2znYg9aJTDqDzgvg(s, newlen);
	}
	goto LA1_;
	LA4_: ;
	{
		NI oldLen;
		NI T7_;
		tyObject_NimSeqV2__VABqGxoJY4QkZ9cJjT9cJTLw* xu;
		T7_ = (*s).len;
		oldLen = T7_;
		{
			if (!(((NI) (newlen)) <= oldLen)) goto LA10_;
			goto BeforeRet_;
		}
		LA10_: ;
		xu = ((tyObject_NimSeqV2__VABqGxoJY4QkZ9cJjT9cJTLw*) (s));
		{
			NIM_BOOL T14_;
			NI T18_;
			NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_83;
			void* T19_;
			T14_ = (NIM_BOOL)0;
			T14_ = ((*xu).p == ((tyObject_NimSeqPayload__Sk8I13hH69c7YfXxOuSgu8w*) NIM_NIL));
			if (T14_) goto LA15_;
			T14_ = ((*(*xu).p).cap < ((NI) (newlen)));
			LA15_: ;
			if (!T14_) goto LA16_;
			T18_ = (NI)0;
			T18_ = oldLen;
			if (nimSubInt(((NI) (newlen)), oldLen, &TM__Q5wkpxktOdTGvlSRo9bzt9aw_83)) { raiseOverflow(); goto BeforeRet_;
};
			T19_ = (void*)0;
			T19_ = prepareSeqAdd(T18_, ((void*) ((*xu).p)), (NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_83), ((NI) 12), ((NI) 4));
			(*xu).p = ((tyObject_NimSeqPayload__Sk8I13hH69c7YfXxOuSgu8w*) (T19_));
		}
		LA16_: ;
		(*xu).len = ((NI) (newlen));
	}
	LA1_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___aBBXmHFBEivKqERloP6zmA_2)(NimStringV2* dest, NimStringV2 src) {
	if ((*dest).p != src.p) {	eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ(dest);
	}
(*dest).len = src.len; (*dest).p = src.p;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, mnewString)(NI len) {
	NimStringV2 result;
{	nimZeroMem((void*)(&result), sizeof(NimStringV2));
	{
		if (!(len <= ((NI) 0))) goto LA3_;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		result.len = ((NI) 0);
		result.p = ((NimStrPayload*) NIM_NIL);
	}
	goto LA1_;
	LA3_: ;
	{
		NI colontmpD_;
		NimStrPayload* p;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_84;
		NI TM__Q5wkpxktOdTGvlSRo9bzt9aw_85;
		void* T6_;
		colontmpD_ = (NI)0;
		if (nimAddInt(len, ((NI) 1), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_84)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimAddInt((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_84), ((NI) 4), &TM__Q5wkpxktOdTGvlSRo9bzt9aw_85)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_85)) < ((NI) 0) || ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_85)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_85), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
		T6_ = (void*)0;
		T6_ = alloc0Impl__aMIFDISudztFhhVWVqortg(((NI) ((NI)(TM__Q5wkpxktOdTGvlSRo9bzt9aw_85))));
		p = ((NimStrPayload*) (T6_));
		(*p).cap = len;
		nimZeroMem((void*)(&result), sizeof(NimStringV2));
		colontmpD_ = len;
		result.len = colontmpD_;
		result.p = p;
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, reportUnhandledError__na8C8pUZ9cLQWVwk35l5vfw_2)(Exception* e) {
	{
		if (!!((unhandledExceptionHook__RJpSsXsRUH8ochbXTEhRIw == NIM_NIL))) goto LA3_;
		unhandledExceptionHook__RJpSsXsRUH8ochbXTEhRIw(e);
	}
	LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimInErrorMode__759bT87luu8XGcbkw13FUjA;
		if (!(T3_)) goto LA4_;
		T3_ = !((currException__9bVPeDJlYTi9bQApZpfH8wjg == ((Exception*) NIM_NIL)));
		LA4_: ;
		if (!T3_) goto LA5_;
		reportUnhandledError__na8C8pUZ9cLQWVwk35l5vfw_2(currException__9bVPeDJlYTi9bQApZpfH8wjg);
		eqsink___rR9boD7urcxl7uyUtE46AOA_2(&currException__9bVPeDJlYTi9bQApZpfH8wjg, ((Exception*) NIM_NIL));
		exit(((NI) 1));
	}
	LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void) {
{
	initStackBottom();
	registerSignalHandler__amVlU9ajqZ06ujoesRBHcDg();
}
}

N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void) {

/* section: NIM_merge_TYPE_INIT3 */
NTIv2__Rp9adJYTsbbIUzQ8fWxwgdA_.destructor = (void*)eqdestroy___LZ4ekoCGfhYJ49aM9aFAL7AQ; NTIv2__Rp9adJYTsbbIUzQ8fWxwgdA_.size = sizeof(tyObject_RangeDefect__Rp9adJYTsbbIUzQ8fWxwgdA); NTIv2__Rp9adJYTsbbIUzQ8fWxwgdA_.align = NIM_ALIGNOF(tyObject_RangeDefect__Rp9adJYTsbbIUzQ8fWxwgdA); NTIv2__Rp9adJYTsbbIUzQ8fWxwgdA_.name = "|RangeDefect|Defect|Exception|RootObj|";
; NTIv2__Rp9adJYTsbbIUzQ8fWxwgdA_.traceImpl = (void*)NIM_NIL; NTIv2__Rp9adJYTsbbIUzQ8fWxwgdA_.disposeImpl = (void*)NIM_NIL;NTIv2__n3A4gjRrFZBuNnTYx1h9a8w_.destructor = (void*)eqdestroy___BO2qxEc1Yf80x0M89aiw9cAQ; NTIv2__n3A4gjRrFZBuNnTYx1h9a8w_.size = sizeof(tyObject_DivByZeroDefect__n3A4gjRrFZBuNnTYx1h9a8w); NTIv2__n3A4gjRrFZBuNnTYx1h9a8w_.align = NIM_ALIGNOF(tyObject_DivByZeroDefect__n3A4gjRrFZBuNnTYx1h9a8w); NTIv2__n3A4gjRrFZBuNnTYx1h9a8w_.name = "|DivByZeroDefect|ArithmeticDefect|Defect|Exception|RootObj|";
; NTIv2__n3A4gjRrFZBuNnTYx1h9a8w_.traceImpl = (void*)NIM_NIL; NTIv2__n3A4gjRrFZBuNnTYx1h9a8w_.disposeImpl = (void*)NIM_NIL;NTIv2__9cxMi1BPLc3UKt9br86bGfGQ_.destructor = (void*)eqdestroy___iXyOdhIrs6C9bvzrDNqxI2g; NTIv2__9cxMi1BPLc3UKt9br86bGfGQ_.size = sizeof(tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ); NTIv2__9cxMi1BPLc3UKt9br86bGfGQ_.align = NIM_ALIGNOF(tyObject_OverflowDefect__9cxMi1BPLc3UKt9br86bGfGQ); NTIv2__9cxMi1BPLc3UKt9br86bGfGQ_.name = "|OverflowDefect|ArithmeticDefect|Defect|Exception|RootObj|";
; NTIv2__9cxMi1BPLc3UKt9br86bGfGQ_.traceImpl = (void*)NIM_NIL; NTIv2__9cxMi1BPLc3UKt9br86bGfGQ_.disposeImpl = (void*)NIM_NIL;NTIv2__n6tGEPHKkh7E1AP9bj30WrQ_.destructor = (void*)eqdestroy___qRVWt3jIAyom1VkyIWI7tA; NTIv2__n6tGEPHKkh7E1AP9bj30WrQ_.size = sizeof(tyObject_IndexDefect__n6tGEPHKkh7E1AP9bj30WrQ); NTIv2__n6tGEPHKkh7E1AP9bj30WrQ_.align = NIM_ALIGNOF(tyObject_IndexDefect__n6tGEPHKkh7E1AP9bj30WrQ); NTIv2__n6tGEPHKkh7E1AP9bj30WrQ_.name = "|IndexDefect|Defect|Exception|RootObj|";
; NTIv2__n6tGEPHKkh7E1AP9bj30WrQ_.traceImpl = (void*)NIM_NIL; NTIv2__n6tGEPHKkh7E1AP9bj30WrQ_.disposeImpl = (void*)NIM_NIL;NTIv2__PtYxPmY5X0dorfvxAFbJpQ_.destructor = (void*)eqdestroy___sUPxfcqVijR0WN3SH4QQ6A; NTIv2__PtYxPmY5X0dorfvxAFbJpQ_.size = sizeof(tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ); NTIv2__PtYxPmY5X0dorfvxAFbJpQ_.align = NIM_ALIGNOF(tyObject_AssertionDefect__PtYxPmY5X0dorfvxAFbJpQ); NTIv2__PtYxPmY5X0dorfvxAFbJpQ_.name = "|AssertionDefect|Defect|Exception|RootObj|";
; NTIv2__PtYxPmY5X0dorfvxAFbJpQ_.traceImpl = (void*)NIM_NIL; NTIv2__PtYxPmY5X0dorfvxAFbJpQ_.disposeImpl = (void*)NIM_NIL;NTIv2__t7nhKLvXTQS9cS8ByJU9bIag_.destructor = (void*)eqdestroy___vttz8U9aaHVcOkTLV69bskjQ; NTIv2__t7nhKLvXTQS9cS8ByJU9bIag_.size = sizeof(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag); NTIv2__t7nhKLvXTQS9cS8ByJU9bIag_.align = NIM_ALIGNOF(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag); NTIv2__t7nhKLvXTQS9cS8ByJU9bIag_.name = "|KeyError|ValueError|CatchableError|Exception|RootObj|";
; NTIv2__t7nhKLvXTQS9cS8ByJU9bIag_.traceImpl = (void*)NIM_NIL; NTIv2__t7nhKLvXTQS9cS8ByJU9bIag_.disposeImpl = (void*)NIM_NIL;}

