/* Generated by Nim Compiler v1.4.6 */
/*   (c) 2020 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
#define nimfr_(x, y)
#define nimln_(x, y)

/* section: NIM_merge_FORWARD_TYPES */
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;

/* section: NIM_merge_TYPES */
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};

/* section: NIM_merge_PROC_HEADERS */
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res);
static N_INLINE(NF, toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem)(NI i);
static N_INLINE(NF, abs__BRaAqinz6OWTHkALb4oj6Qsystem)(NF x);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, stareq___ogcC1Md4c289bEhAZWpmZUwsystem)(NI* x, NI y);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);

/* section: NIM_merge_PROCS */
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__v2qC0V55wqa9bmqc7eHTz8A)(NI x) {
	NI result;
	result = (NI)0;
	result = (NI)(x - ((NI) 1));
	result = (NI)(result | (NI)((NI32)(result) >> (NU32)(((NI) 16))));
	result = (NI)(result | (NI)((NI32)(result) >> (NU32)(((NI) 8))));
	result = (NI)(result | (NI)((NI32)(result) >> (NU32)(((NI) 4))));
	result = (NI)(result | (NI)((NI32)(result) >> (NU32)(((NI) 2))));
	result = (NI)(result | (NI)((NI32)(result) >> (NU32)(((NI) 1))));
	result += (NI)(((NI) 1) + (x <= ((NI) 0)));
	return result;
}
static N_INLINE(NF, toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem)(NI i) {
	NF result;
	result = (NF)0;
	result = ((NF) (i));
	return result;
}
static N_INLINE(NF, abs__BRaAqinz6OWTHkALb4oj6Qsystem)(NF x) {
	NF result;
	NF colontmpD_;
	NF colontmpD__2;
	result = (NF)0;
	colontmpD_ = (NF)0;
	colontmpD__2 = (NF)0;
	{
		if (!(x < 0.0)) goto LA3_;
		colontmpD_ = -(x);
		result = colontmpD_;
	}
	goto LA1_;
	LA3_: ;
	{
		colontmpD__2 = x;
		result = colontmpD__2;
	}
	LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a, NI b, NI* res) {
	NIM_BOOL result;
	NI r;
	NF floatProd;
	NF T1_;
	NF T2_;
	NF resAsFloat;
	result = (NIM_BOOL)0;
	r = ((NI) ((NU)((NU32)(((NU) (a))) * (NU32)(((NU) (b))))));
	T1_ = (NF)0;
	T1_ = toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem(a);
	T2_ = (NF)0;
	T2_ = toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem(b);
	floatProd = ((NF)(T1_) * (NF)(T2_));
	resAsFloat = toFloat__y1Fm9aHmxw9bS2jir137Fu5gsystem(r);
	{
		if (!(resAsFloat == floatProd)) goto LA5_;
		(*res) = r;
	}
	goto LA3_;
	LA5_: ;
	{
		{
			NF T10_;
			NF T11_;
			T10_ = (NF)0;
			T10_ = abs__BRaAqinz6OWTHkALb4oj6Qsystem(((NF)(resAsFloat) - (NF)(floatProd)));
			T11_ = (NF)0;
			T11_ = abs__BRaAqinz6OWTHkALb4oj6Qsystem(floatProd);
			if (!(((NF)(3.2000000000000000e+01) * (NF)(T10_)) <= T11_)) goto LA12_;
			(*res) = r;
		}
		goto LA8_;
		LA12_: ;
		{
			result = NIM_TRUE;
		}
		LA8_: ;
	}
	LA3_: ;
	return result;
}
static N_INLINE(void, stareq___ogcC1Md4c289bEhAZWpmZUwsystem)(NI* x, NI y) {
	NI TM__YqBQIdfvZX5pt75kDBsDLg_5;
{	if (nimMulInt((*x), y, &TM__YqBQIdfvZX5pt75kDBsDLg_5)) { raiseOverflow(); goto BeforeRet_;
};
	(*x) = (NI)(TM__YqBQIdfvZX5pt75kDBsDLg_5);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, roof___M1yk6GvJhRrReRZgYouX8g)(NI x, NI y) {
	NI result;
{	result = (NI)0;
	switch (y) {
	case ((NI) 0):
	{
		result = ((NI) 1);
	}
	break;
	case ((NI) 1):
	{
		result = x;
	}
	break;
	case ((NI) 2):
	{
		NI TM__YqBQIdfvZX5pt75kDBsDLg_2;
		if (nimMulInt(x, x, &TM__YqBQIdfvZX5pt75kDBsDLg_2)) { raiseOverflow(); goto BeforeRet_;
};
		result = (NI)(TM__YqBQIdfvZX5pt75kDBsDLg_2);
	}
	break;
	case ((NI) 3):
	{
		NI TM__YqBQIdfvZX5pt75kDBsDLg_3;
		NI TM__YqBQIdfvZX5pt75kDBsDLg_4;
		if (nimMulInt(x, x, &TM__YqBQIdfvZX5pt75kDBsDLg_3)) { raiseOverflow(); goto BeforeRet_;
};
		if (nimMulInt((NI)(TM__YqBQIdfvZX5pt75kDBsDLg_3), x, &TM__YqBQIdfvZX5pt75kDBsDLg_4)) { raiseOverflow(); goto BeforeRet_;
};
		result = (NI)(TM__YqBQIdfvZX5pt75kDBsDLg_4);
	}
	break;
	default:
	{
		tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ T6_;
		NI x_2;
		NI y_2;
		T6_.Field0 = x;
		T6_.Field1 = y;
		x_2 = T6_.Field0;
		y_2 = T6_.Field1;
		result = ((NI) 1);
		{
			while (1) {
				{
					if (!!(((NI)(((NI) (y_2)) & ((NI) 1)) == ((NI) 0)))) goto LA11_;
					stareq___ogcC1Md4c289bEhAZWpmZUwsystem((&result), x_2);
				}
				LA11_: ;
				if (((NI)((NI32)(((NI) (y_2))) >> (NU32)(((NI) 1)))) < ((NI) 0) || ((NI)((NI32)(((NI) (y_2))) >> (NU32)(((NI) 1)))) > ((NI) 2147483647)){ raiseRangeErrorI((NI)((NI32)(((NI) (y_2))) >> (NU32)(((NI) 1))), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;
}
				y_2 = ((NI) ((NI)((NI32)(((NI) (y_2))) >> (NU32)(((NI) 1)))));
				{
					if (!(((NI) (y_2)) == ((NI) 0))) goto LA15_;
					goto LA7;
				}
				LA15_: ;
				stareq___ogcC1Md4c289bEhAZWpmZUwsystem((&x_2), x_2);
			}
		} LA7: ;
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
